var searchData=
[
  ['écarté_20à_20la_20relecture_20des_20livres_0',['Écarté à la relecture des livres',['../roadmap.html#autotoc_md941',1,'']]],
  ['écarté_20et_20pourquoi_1',['Écarté, et pourquoi',['../lot-09.html#autotoc_md367',1,'']]],
  ['écarts_20par_20rapport_20au_20texte_20de_20la_20feuille_20de_20route_2',['Écarts par rapport au texte de la feuille de route',['../lot-88.html#autotoc_md708',1,'']]],
  ['échanger_3',['2. Échanger',['../spec-inventaire.html#autotoc_md270',1,'']]],
  ['échantillonner_20plutôt_20que_20réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_4',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md100',1,'']]],
  ['échelles_5',['6. Échelles',['../spec-regles-d20.html#autotoc_md282',1,'']]],
  ['écrans_20navigation_20et_20boucle_20de_20jeu_6',['Écrans, navigation et boucle de jeu',['../guide-ecrans.html',1,'guide']]],
  ['écriture_20canonique_20lot_20editor_2012_7',['Écriture canonique (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)',['../classcore_1_1LevelWriter.html#autotoc_md1150',1,'']]],
  ['éditer_20un_20écran_20sans_20rien_20reconstruire_8',['Éditer un écran sans rien reconstruire',['../guide-ihm-qt.html#autotoc_md111',1,'']]],
  ['éditeur_9',['2. Éditeur',['../spec-interface-ihm.html#autotoc_md255',1,'']]],
  ['éditeur_20de_20cartes_10',['Éditeur de cartes',['../spec-editeur.html',1,'specifications']]],
  ['éditeur_20de_20niveaux_11',['Éditeur de niveaux',['../guide-editeur.html',1,'guide']]],
  ['éditeur_20de_20niveaux_20—_20test_5fparcours_5fedition_5frpg_20cpp_201_12',['Éditeur de niveaux — &lt;span class=&quot;tt&quot;&gt;test_parcours_edition_rpg.cpp&lt;/span&gt; (1)',['../cahiertest.html#autotoc_md30',1,'']]],
  ['éditeur_20multi_20couches_20et_20placement_20d_20entités_13',['LOT-11 — Éditeur multi-couches et placement d&apos;entités',['../lot-11.html',1,'']]],
  ['égalité_20approchée_14',['Égalité approchée',['../guide-maths.html#autotoc_md132',1,'']]],
  ['équilibrage_15',['Équilibrage',['../roadmap.html#autotoc_md991',1,'']]],
  ['équipement_20monnaie_20objets_20magiques_16',['LOT-34 — Équipement, monnaie, objets magiques',['../lot-34.html',1,'lots']]],
  ['étapes_17',['Étapes',['../manuel-telecharger.html#autotoc_md1106',1,'']]],
  ['étapes_20du_20socle_18',['Étapes du socle',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html#autotoc_md893',1,'']]],
  ['état_20d_20avancement_19',['État d&apos;avancement',['../roadmap.html#roadmap-avancement',1,'']]],
  ['états_20de_20jeu_20',['2. États de jeu',['../spec-gameplay.html#autotoc_md252',1,'']]],
  ['écarté_21',['Le piège, et la façon dont il est écarté',['../lot-14.html#autotoc_md408',1,'']]],
  ['écarté_20et_20pourquoi_22',['Ce qui est écarté, et pourquoi',['../lot-87.html#autotoc_md672',1,'']]],
  ['écartées_23',['8. Risques et pistes écartées',['../roadmap-editeur.html#roadmap-editeur-risques',1,'']]],
  ['écartées_20et_20pourquoi_24',['Les deux directions écartées, et pourquoi',['../lot-86.html#autotoc_md646',1,'']]],
  ['échafaudage_20assumé_25',['Le personnage affiché : une donnée, et un échafaudage assumé',['../lot-38.html#autotoc_md561',1,'']]],
  ['échafaudage_20et_20il_20est_20écrit_26',['« Nouvelle partie » : un échafaudage, et il est écrit',['../lot-68.html#autotoc_md616',1,'']]],
  ['échafaudage_20et_20le_20dit_27',['Ce qui est un échafaudage, et le dit',['../classhmi_1_1DialogueModel.html#autotoc_md1203',1,'']]],
  ['échantillonnage_20nearest_28',['Sommets, shaders, et échantillonnage &lt;em&gt;nearest&lt;/em&gt;',['../guide-rendu.html#autotoc_md157',1,'']]],
  ['échelle_29',['2. Repères d&apos;échelle',['../spec-exploration.html#autotoc_md250',1,'']]],
  ['échelle_20lot_2066_30',['Deux identités, deux règles d&apos;échelle (LOT-66)',['../guide-design-ihm.html#autotoc_md65',1,'']]],
  ['économie_31',['économie',['../spec-inventaire.html',1,'Inventaire et économie'],['../roadmap.html#lot-26',1,'LOT-26 — Butin, marchands, économie']]],
  ['économie_20d_20action_20est_20une_20liste_32',['L&apos;économie d&apos;action est une liste',['../lot-20.html#autotoc_md455',1,'']]],
  ['écran_33',['écran',['../lot-14.html#autotoc_md411',1,'L&apos;écran'],['../lot-15.html#autotoc_md421',1,'L&apos;écran'],['../guide-rendu.html',1,'Rendu 2D : de la scène à l&apos;écran'],['../lot-68.html#autotoc_md617',1,'Trois défauts d&apos;agencement, trouvés en regardant l&apos;écran']]],
  ['écran_20«_20carte_20»_20_3a_20le_20monde_20une_20région_20une_20ville_20lot_2094_34',['11. L&apos;écran « Carte » : le monde, une région, une ville (LOT-94)',['../spec-interface-ihm.html#ihm-carte',1,'']]],
  ['écran_20«_20carte_20»_20revient_20sur_20les_20cartes_20de_20l_20auteur_20_3a_20monde_20région_20ville_35',['LOT-94 — Les images du corpus quittent le dépôt ; l&apos;écran « Carte » revient sur les cartes de l&apos;auteur : monde, région, ville',['../lot-94.html',1,'lots']]],
  ['écran_20à_20honorer_36',['Décisions d&apos;écran à honorer',['../lot-86.html#autotoc_md647',1,'']]],
  ['écran_20compose_20et_20ce_20qu_20il_20ne_20compose_20pas_37',['Ce que l&apos;écran compose, et ce qu&apos;il ne compose pas',['../lot-50.html#autotoc_md587',1,'']]],
  ['écran_20des_20options_20au_20moteur_38',['Le volume : de l&apos;écran des options au moteur',['../guide-audio.html#autotoc_md33',1,'']]],
  ['écran_20est_20donc_20aujourd_20hui_39',['Ce que l&apos;écran est donc aujourd&apos;hui',['../lot-38.html#autotoc_md559',1,'']]],
  ['écran_20et_20non_20par_20l_20appelant_40',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md615',1,'']]],
  ['écran_20sans_20rien_20reconstruire_41',['Éditer un écran sans rien reconstruire',['../guide-ihm-qt.html#autotoc_md111',1,'']]],
  ['écrans_42',['écrans',['../guide-ecrans.html#autotoc_md69',1,'Le routeur et la pile d&apos;écrans'],['../lot-76.html#autotoc_md625',1,'Le titre devient son bandeau, sur les six écrans'],['../lot-87.html#autotoc_md682',1,'Phase 3 — les écrans']]],
  ['écrans_20écrits_20à_20la_20main_43',['Une table, et non huit écrans écrits à la main',['../RpgScreens_8h.html#autotoc_md1192',1,'']]],
  ['écrans_20dans_20qt_20design_20studio_44',['Concevoir les écrans dans Qt Design Studio',['../guide-conception-qds.html',1,'guide']]],
  ['écrans_20dessinés_20mais_20pas_20encore_20alimentés_45',['Les écrans dessinés mais pas encore alimentés',['../guide-conception-qds.html#autotoc_md52',1,'']]],
  ['écrans_20du_20jeu_46',['7. Identité visuelle des écrans du jeu',['../spec-interface-ihm.html#autotoc_md260',1,'']]],
  ['écrans_20du_20rpg_47',['LOT-68 — Le châssis des écrans du RPG',['../lot-68.html',1,'lots']]],
  ['écrans_20du_20rpg_20lot_2068_48',['9. Le châssis des écrans du RPG (LOT-68)',['../spec-interface-ihm.html#autotoc_md262',1,'']]],
  ['écrans_20pour_20les_20dessiner_49',['Ouvrir les écrans pour les dessiner',['../guide-ihm-qt.html#autotoc_md112',1,'']]],
  ['écrire_50',['écrire',['../classhmi_1_1GamepadNavigator.html#autotoc_md1204',1,'Pourquoi il fallait l&apos;écrire'],['../lot-87.html#autotoc_md664',1,'T1.1 — Le diagnostic, avant d&apos;écrire']]],
  ['écrire_20jamais_20l_20inverse_51',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md93',1,'']]],
  ['écrit_52',['écrit',['../lot-68.html#autotoc_md616',1,'« Nouvelle partie » : un échafaudage, et il est écrit'],['../lot-37.html#autotoc_md549',1,'Le voisinage est déclaré, et c&apos;est écrit']]],
  ['écrit_20comme_20non_20alimenté_53',['Un champ affiché, ou écrit comme non alimenté',['../lot-38.html#autotoc_md555',1,'']]],
  ['écrit_20de_20classdefinition_20_3a_20elle_20existait_20déjà_54',['Le lot n&apos;a pas écrit de &lt;span class=&quot;tt&quot;&gt;ClassDefinition&lt;/span&gt; : elle existait déjà',['../lot-13.html#autotoc_md400',1,'']]],
  ['écrit_20et_20qu_20un_20schéma_20refusait_55',['Trois cas que le livre écrit et qu&apos;un schéma refusait',['../lot-34.html#autotoc_md525',1,'']]],
  ['écrit_20une_20couleur_56',['Les jetons : le seul endroit où s&apos;écrit une couleur',['../guide-conception-qds.html#autotoc_md49',1,'']]],
  ['écrite_57',['écrite',['../lot-14.html#autotoc_md409',1,'Ce que la règle dit, et où elle est écrite'],['../lot-20.html#autotoc_md453',1,'L&apos;initiative : jetée une fois, départagée par une règle écrite']]],
  ['écrites_20là_20où_20on_20les_20lit_58',['Trois décisions de règle, écrites là où on les lit',['../lot-13.html#autotoc_md404',1,'']]],
  ['écrits_20à_20la_20main_59',['Une table, et non huit écrans écrits à la main',['../RpgScreens_8h.html#autotoc_md1192',1,'']]],
  ['éditer_20une_20carte_20sans_20re_20coder_20le_20moteur_60',['Le problème : éditer une carte sans (re)coder le moteur',['../guide-editeur.html#autotoc_md84',1,'']]],
  ['éditeur_61',['éditeur',['../manuel-partager-niveau.html#autotoc_md1100',1,'2. Lancer l&apos;éditeur'],['../guide-usage-editeur.html#autotoc_md1030',1,'Ce qui ne se fait pas encore dans l&apos;éditeur'],['../guide-editeur.html#autotoc_md92',1,'Essai immédiat : jouer sans quitter l&apos;éditeur'],['../guide-usage-editeur.html',1,'Faire une carte dans l&apos;éditeur'],['../spec-conventions.html#autotoc_md209',1,'IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur']]],
  ['éditeur_20_3a_20hmi_3a_3aeditorkeybindings_20editorkeybindings_62',['Les raccourcis de l&apos;éditeur : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt;',['../guide-entrees.html#autotoc_md105',1,'']]],
  ['éditeur_20_3a_20un_20outil_20pas_20un_20produit_63',['L&apos;éditeur : un outil, pas un produit',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['éditeur_20de_20cartes_64',['Feuille de route de l&apos;éditeur de cartes',['../roadmap-editeur.html',1,'']]],
  ['éditeur_20joue_20le_20jeu_65',['1. L&apos;essai de l&apos;éditeur joue le jeu',['../lot-88.html#autotoc_md704',1,'']]],
  ['éditeur_20lot_20editor_2006_66',['15. Les cartes se font dans l&apos;éditeur (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-06&lt;/span&gt;)',['../spec-editeur.html#autotoc_md236',1,'']]],
  ['éditeur_20sans_20fenêtre_67',['éditeur sans fenêtre',['../lot-editor-13.html',1,'LOT-EDITOR-13 — L&apos;éditeur sans fenêtre'],['../roadmap-editeur.html#autotoc_md1014',1,'LOT-EDITOR-13 — L&apos;éditeur sans fenêtre']]],
  ['éditeur_20sans_20fenêtre_20lot_20editor_2013_68',['14. L&apos;éditeur sans fenêtre (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-13&lt;/span&gt;)',['../spec-editeur.html#autotoc_md235',1,'']]],
  ['éditeur_20sur_20le_20dépôt_69',['0. Ouvrir l&apos;éditeur sur le dépôt',['../guide-usage-editeur.html#autotoc_md1020',1,'']]],
  ['édition_70',['6. Robustesse et confort d&apos;édition',['../spec-editeur.html#autotoc_md227',1,'']]],
  ['égalité_20stricte_20est_20dangereuse_71',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md135',1,'']]],
  ['élément_20composé_20avec_20l_20interface_72',['Les surfaces de dessin : un élément composé avec l&apos;interface',['../guide-rendu.html#autotoc_md151',1,'']]],
  ['énumération_20et_20non_20un_20nom_20de_20fichier_73',['Pourquoi une énumération et non un nom de fichier',['../classhmi_1_1ScreenRouter.html#autotoc_md1216',1,'']]],
  ['équipe_20de_20mercenaires_20maquette_2009_74',['T3.7 — L&apos;équipe de mercenaires (maquette 09)',['../lot-87.html#autotoc_md689',1,'']]],
  ['équipe_20et_20quartier_20général_75',['&lt;span class=&quot;tt&quot;&gt;LOT-83&lt;/span&gt; — Compagnie : rangs de Guilde, niveau d&apos;équipe et quartier général',['../roadmap.html#lot-83',1,'']]],
  ['équipement_76',['LOT-14 — Inventaire et équipement',['../lot-14.html',1,'lots']]],
  ['équipement_20maquette_2004_77',['T3.5 — L&apos;inventaire et l&apos;équipement (maquette 04)',['../lot-87.html#autotoc_md687',1,'']]],
  ['été_20fait_78',['été fait',['../lot-88.html#autotoc_md703',1,'Ce qui a été fait'],['../lot-87.html#autotoc_md665',1,'T1.2 à T1.4 — Ce qui a été fait']]],
  ['été_20faite_79',['Comment la classification a été faite',['../lot-78.html#autotoc_md634',1,'']]],
  ['été_20livré_20à_20l_20ouverture_80',['Ce qui a été livré à l&apos;ouverture',['../lot-93.html#autotoc_md752',1,'']]],
  ['été_20retiré_20du_20code_81',['Ce qui a été retiré du code',['../lot-67.html#autotoc_md607',1,'']]],
  ['établit_82',['Ce que l’essai établit',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html#autotoc_md1225',1,'']]],
  ['étaient_20consommées_20sans_20être_20produites_83',['9.2 Six mécaniques étaient consommées sans être produites',['../roadmap.html#autotoc_md946',1,'']]],
  ['était_20périmé_84',['Attention : le texte des maquettes était périmé',['../lot-86.html#autotoc_md645',1,'']]],
  ['étape_20e1_20à_20la_20main_85',['2. Les références (étape E1, à la main)',['../lot-91-poc.html#autotoc_md725',1,'']]],
  ['étape_20e2_20bloc_20a_86',['3. Le style commun v1 (étape E2, bloc A)',['../lot-91-poc.html#autotoc_md726',1,'']]],
  ['étape_20e3_87',['5. Le tour 1 (étape E3)',['../lot-91-poc.html#autotoc_md728',1,'']]],
  ['étape_20e4_20en_20mode_20manuel_88',['6. Le contrôle mécanique (étape E4, en mode manuel)',['../lot-91-poc.html#autotoc_md729',1,'']]],
  ['étape_20r_89',['4. La référence canonique : Anariel (étape R)',['../lot-91-poc.html#autotoc_md727',1,'']]],
  ['état_90',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md101',1,'']]],
  ['état_20de_20production_91',['PoC Fabrique d’assets — état de production',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2rapport-poc.html',1,'']]],
  ['état_20du_20dépôt_92',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap.html#autotoc_md944',1,'']]],
  ['état_20structurée_93',['Une barre d&apos;état structurée',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['état_20un_20contrôle_94',['Un état, un contrôle',['../guide-design-ihm.html#autotoc_md64',1,'']]],
  ['états_95',['états',['../roadmap.html#lot-35',1,'&lt;span class=&quot;tt&quot;&gt;LOT-35&lt;/span&gt; — Sorts et états'],['../lot-21.html',1,'LOT-21 — Attaques, dégâts et états']]],
  ['états_20_3a_20hmi_3a_3ascreenflow_96',['La machine à états : &lt;span class=&quot;tt&quot;&gt;hmi::ScreenFlow&lt;/span&gt;',['../guide-ecrans.html#autotoc_md68',1,'']]],
  ['étendu_20aux_20images_20produites_97',['T2.5 — Le manifeste étendu aux images produites',['../lot-87.html#autotoc_md678',1,'']]],
  ['éviter_20la_20racine_20carrée_98',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html#a5f3517fe219407f73a3ed5542091c31c&quot; title=&quot;core::Vector2::lengthSquared&quot;&gt;lengthSquared&lt;/a&gt; : éviter la racine carrée',['../guide-maths.html#autotoc_md131',1,'']]]
];
