var searchData=
[
  ['vérifié_0',['Livré, et vérifié',['../lot-09.html#autotoc_md368',1,'']]],
  ['vérifié_20et_20ce_20qu_20elle_20a_20démenti_1',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md502',1,'']]],
  ['vérifié_20le_2013_20septembre_202026_2',['Où en est la phase 2 — vérifié le 13 septembre 2026',['../lot-87.html#autotoc_md683',1,'']]],
  ['vérifiée_3',['Acceptation, telle que vérifiée',['../lot-94.html#autotoc_md766',1,'']]],
  ['vérifiable_4',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md430',1,'']]],
  ['vérification_5',['Vérification',['../lot-88.html#autotoc_md713',1,'']]],
  ['vérification_6',['3. Qualité &amp;amp; vérification',['../spec-exigences.html#autotoc_md244',1,'']]],
  ['vérifie_20et_20pourquoi_20il_20s_20auto_20teste_7',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md504',1,'']]],
  ['vérifie_20pas_8',['Ce qu&apos;elle ne vérifie pas',['../namespacecore.html#autotoc_md1163',1,'']]],
  ['vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_9',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md403',1,'']]],
  ['vérifier_20le_20relevé_10',['Vérifier le relevé',['../lot-87-cahier-assets.html#autotoc_md658',1,'']]],
  ['vérifier_20une_20interface_20sans_20la_20regarder_11',['Vérifier une interface sans la regarder',['../guide-ihm-qt.html#autotoc_md116',1,'']]],
  ['vérité_20pour_20«_20peut_20on_20se_20tenir_20ici_20»_12',['vérité pour « peut on se tenir ici »',['../lot-19.html#autotoc_md448',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1139',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['v1_20étape_20e2_20bloc_20a_13',['3. Le style commun v1 (étape E2, bloc A)',['../lot-91-poc.html#autotoc_md728',1,'']]],
  ['v2_14',['v2',['../lot-87-cahier-assets.html',1,'LOT-87 — Cahier des assets de la charte v2'],['../lot-87.html#autotoc_md671',1,'T2.1 — La charte v2'],['../lot-87.html#autotoc_md682',1,'T2.7 — Les briques de la charte v2']]],
  ['v2_20et_20intégration_20des_20maquettes_15',['LOT-87 — Charte v2 et intégration des maquettes',['../lot-87.html',1,'lots']]],
  ['v2_20et_20matière_20première_16',['Phase 2 — charte v2 et matière première',['../lot-87.html#autotoc_md670',1,'']]],
  ['v4_20et_20sa_20garde_20en_20ci_17',['v4 et sa garde en CI',['../lot-editor-12.html',1,'LOT-EDITOR-12 — Le format v4 et sa garde en CI'],['../roadmap-editeur.html#autotoc_md1012',1,'LOT-EDITOR-12 — Le format v4 et sa garde en CI']]],
  ['v4_20lot_20editor_2012_18',['v4 LOT EDITOR 12',['../PlaceAppearance_8h.html#autotoc_md1208',1,'Depuis le format v4 (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)'],['../spec-niveaux.html#autotoc_md275',1,'Format v4 (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)']]],
  ['v4_20lot_20editor_2012_20ex_20lvl_20019_19',['Une case = un type et une pièce (format v4, &lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-LVL-019&lt;/span&gt;)',['../structcore_1_1TileLayer.html#autotoc_md1170',1,'']]],
  ['va_20le_20geste_20',['Où va le geste',['../BrushGesture_8h.html#autotoc_md1181',1,'']]],
  ['va_20où_21',['va où',['../ArenaSceneComposer_8h.html#autotoc_md1198',1,'Ce qui va où'],['../WorldSceneComposer_8h.html#autotoc_md1209',1,'Ce qui va où']]],
  ['vaincu_20est_20un_20drapeau_20de_20monde_20pas_20un_20booléen_22',['Un ennemi vaincu est un drapeau de monde, pas un booléen',['../lot-18.html#autotoc_md432',1,'']]],
  ['valait_20mieux_23',['Le renversement du milieu du lot, et pourquoi il valait mieux',['../lot-76.html#autotoc_md623',1,'']]],
  ['valeur_20de_20règle_20dans_20le_20c_20»_20se_20vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_24',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md403',1,'']]],
  ['valeur_20jamais_20dessus_25',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md543',1,'']]],
  ['validateur_20s_20auto_20teste_20faute_20de_20données_20à_20valider_26',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md511',1,'']]],
  ['validation_27',['Validation',['../guide-niveaux.html#autotoc_md146',1,'']]],
  ['validation_28',['Capacités, branches et validation',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html#autotoc_md781',1,'']]],
  ['valider_29',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md511',1,'']]],
  ['valider_20avant_20d_20écrire_20jamais_20l_20inverse_30',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md93',1,'']]],
  ['variable_31',['Le piège du framerate variable',['../guide-boucle.html#autotoc_md37',1,'']]],
  ['vector2_20_3a_20un_20point_20ou_20une_20direction_20dans_20le_20monde_32',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md130',1,'']]],
  ['verdict_2016_20septembre_33',['Verdict (16 septembre)',['../lot-91-poc.html#autotoc_md737',1,'']]],
  ['verdict_20bloquant_34',['Verdict bloquant',['../md_Lot_2LOT-CREATION-ASSETS_2tache-01-carte-test-textures.html#autotoc_md898',1,'']]],
  ['verdict_20et_20ce_20qu_20il_20déclenche_35',['10. Le verdict, et ce qu&apos;il déclenche',['../lot-91-poc.html#autotoc_md735',1,'']]],
  ['version_200_200_201_36',['version 0 0 1',['../lot-93.html#autotoc_md756',1,'Les trois de la version 0.0.1'],['../roadmap.html#lot-28',1,'LOT-28 — Audio, effets et version &lt;span class=&quot;tt&quot;&gt;0.0.1&lt;/span&gt;']]],
  ['version_3a_203_20multi_20couches_37',['LOT-04 — Format de carte `version: 3`, multi-couches',['../lot-04.html',1,'lots']]],
  ['versionné_38',['1. Le corpus n&apos;est pas versionné',['../roadmap.html#autotoc_md913',1,'']]],
  ['versionnée_39',['Références visuelles hors Git et mémoire versionnée',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md784',1,'']]],
  ['vertical_20slice_40',['vertical slice',['../spec-vision.html#autotoc_md305',1,'Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)'],['../roadmap.html#autotoc_md935',1,'Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;'],['../roadmap.html#lot-27',1,'LOT-27 — La Capitale : contenu du &lt;em&gt;vertical slice&lt;/em&gt;'],['../spec-vision.html#autotoc_md303',1,'Objectifs (&lt;em&gt;vertical slice&lt;/em&gt;)']]],
  ['victoire_20l_20acquiert_41',['Seule une victoire l&apos;acquiert',['../lot-18.html#autotoc_md433',1,'']]],
  ['vidé_20n_20est_20plus_20une_20cible_42',['Un coffre vidé n&apos;est plus une cible',['../lot-10.html#autotoc_md376',1,'']]],
  ['vidéo_43',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md118',1,'']]],
  ['viennent_20les_20formules_44',['D&apos;où viennent les formules',['../IsoProjection_8h.html#autotoc_md1155',1,'']]],
  ['vigilance_45',['Points de vigilance',['../lot-02.html#autotoc_md321',1,'']]],
  ['ville_46',['ville',['../lot-94.html',1,'LOT-94 — Les images du corpus quittent le dépôt ; l&apos;écran « Carte » revient sur les cartes de l&apos;auteur : monde, région, ville'],['../lot-editor-09.html',1,'LOT-EDITOR-09 — Le monde : onglets, portails, ville'],['../roadmap-editeur.html#autotoc_md1021',1,'LOT-EDITOR-09 — Le monde : onglets, portails, ville']]],
  ['ville_20lot_2094_47',['11. L&apos;écran « Carte » : le monde, une région, une ville (LOT-94)',['../spec-interface-ihm.html#ihm-carte',1,'']]],
  ['ville_20lot_20editor_2009_48',['19. Le monde : onglets, portails, ville (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-09&lt;/span&gt;)',['../spec-editeur.html#autotoc_md240',1,'']]],
  ['virtuelle_20ajoutées_20le_207_20septembre_202026_49',['Les ressources de table virtuelle (ajoutées le 7 septembre 2026)',['../roadmap.html#autotoc_md916',1,'']]],
  ['vision_20contre_20une_20liste_20fermée_50',['7. La revue par vision, contre une liste fermée',['../lot-91-poc.html#autotoc_md732',1,'']]],
  ['vision_20périmètre_51',['Vision &amp;amp; périmètre',['../spec-vision.html',1,'specifications']]],
  ['visuelle_20_3a_20sortir_20de_20l_20identité_20pixel_20art_52',['LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art',['../lot-66.html',1,'lots']]],
  ['visuelle_20des_20écrans_20du_20jeu_53',['7. Identité visuelle des écrans du jeu',['../spec-interface-ihm.html#autotoc_md262',1,'']]],
  ['visuelles_54',['Identités visuelles',['../spec-vision.html#autotoc_md301',1,'']]],
  ['visuelles_20hors_20git_20et_20mémoire_20versionnée_55',['Références visuelles hors Git et mémoire versionnée',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md784',1,'']]],
  ['visuelles_20inspectées_56',['visuelles inspectées',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md790',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md796',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md803',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md809',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md821',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md834',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md882',1,'Références visuelles inspectées']]],
  ['vit_57',['vit',['../Attack_8h.html#autotoc_md1135',1,'Ce que dit le Manuel, et où chaque règle vit'],['../lot-23.html#autotoc_md486',1,'Les règles du Guide, et où chacune vit'],['../lot-21.html#autotoc_md467',1,'Les règles du Manuel, et où chacune vit'],['../lot-22.html#autotoc_md476',1,'Les règles du Manuel, et où chacune vit']]],
  ['vocabulaire_20_3a_20«_20niveau_20»_20devient_20«_20carte_20»_20partout_58',['Le vocabulaire : « niveau » devient « carte », partout',['../lot-67.html#autotoc_md611',1,'']]],
  ['vocabulaire_20d_20un_20rpg_59',['LOT-67 — Menus et vocabulaire d&apos;un RPG',['../lot-67.html',1,'lots']]],
  ['vocabulaire_20de_20base_20_3a_20gpu_20swap_20chain_20back_20buffer_60',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md149',1,'']]],
  ['vocabulaire_20de_20tuiles_20rpg_61',['LOT-08 — Vocabulaire de tuiles RPG',['../lot-08.html',1,'lots']]],
  ['vocabulaire_20des_20cases_62',['&lt;a class=&quot;el&quot; href=&quot;namespacecore.html#ace99a1be913e6294e42e9ebb145eb875&quot; title=&quot;core::TileType&quot;&gt;core::TileType&lt;/a&gt; : le vocabulaire des cases',['../guide-niveaux.html#autotoc_md139',1,'']]],
  ['voient_20pas_63',['Deux arrondis qui ne se voient pas',['../lot-12.html#autotoc_md394',1,'']]],
  ['voir_20aussi_64',['Voir aussi',['../guide-audio.html#autotoc_md35',1,'Voir aussi'],['../guide-boucle.html#autotoc_md45',1,'Voir aussi'],['../guide-conception-qds.html#autotoc_md59',1,'Voir aussi'],['../guide-design-ihm.html#autotoc_md67',1,'Voir aussi'],['../guide-ecrans.html#autotoc_md74',1,'Voir aussi'],['../guide-ecs.html#autotoc_md83',1,'Voir aussi'],['../guide-editeur.html#autotoc_md97',1,'Voir aussi'],['../guide-entrees.html#autotoc_md107',1,'Voir aussi'],['../guide-ihm-qt.html#autotoc_md117',1,'Voir aussi'],['../guide-journalisation.html#autotoc_md129',1,'Voir aussi'],['../guide-maths.html#autotoc_md136',1,'Voir aussi'],['../guide-niveaux.html#autotoc_md148',1,'Voir aussi'],['../guide-rendu.html#autotoc_md170',1,'Voir aussi']]],
  ['voisinage_20est_20déclaré_20et_20c_20est_20écrit_65',['Le voisinage est déclaré, et c&apos;est écrit',['../lot-37.html#autotoc_md551',1,'']]],
  ['voit_66',['voit',['../lot-67.html#autotoc_md607',1,'Ce que le joueur voit'],['../lot-68.html#autotoc_md615',1,'Ce que le joueur voit'],['../guide-rendu.html#autotoc_md162',1,'Ce qui manque se voit']]],
  ['voit_20_3a_20le_20culling_67',['Ne dessiner que ce qui se voit : le culling',['../guide-rendu.html#autotoc_md167',1,'']]],
  ['voit_20n_20est_20pas_20ce_20qui_20bloque_68',['Couches : ce qu&apos;on voit n&apos;est pas ce qui bloque',['../guide-niveaux.html#autotoc_md142',1,'']]],
  ['volume_20_3a_20de_20l_20écran_20des_20options_20au_20moteur_69',['Le volume : de l&apos;écran des options au moteur',['../guide-audio.html#autotoc_md33',1,'']]],
  ['votre_20carte_70',['4. Publier votre carte',['../manuel-partager-niveau.html#autotoc_md1120',1,'']]],
  ['vous_20cache_71',['Ce que le projet vous montre, et ce qu&apos;il vous cache',['../guide-conception-qds.html#autotoc_md47',1,'']]],
  ['vous_20montre_20et_20ce_20qu_20il_20vous_20cache_72',['Ce que le projet vous montre, et ce qu&apos;il vous cache',['../guide-conception-qds.html#autotoc_md47',1,'']]],
  ['vous_20pouvez_20importer_73',['Les modules que vous pouvez importer',['../guide-conception-qds.html#autotoc_md55',1,'']]],
  ['voyage_20et_20carte_20du_20monde_74',['&lt;span class=&quot;tt&quot;&gt;LOT-42&lt;/span&gt; — Voyage et carte du monde',['../roadmap.html#lot-42',1,'']]],
  ['vraiment_20et_20qu_20il_20ne_20faut_20pas_20se_20cacher_75',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md1228',1,'']]],
  ['vu_76',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md393',1,'']]],
  ['vue_77',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md602',1,'']]],
  ['vue_20de_20jeu_20et_20la_20session_20qui_20lui_20survit_78',['La vue de jeu et la session qui lui survit',['../guide-ecrans.html#autotoc_md70',1,'']]],
  ['vue_20et_20zones_20d_20effet_79',['LOT-22 — Portée, ligne de vue et zones d&apos;effet',['../lot-22.html',1,'lots']]],
  ['vues_20_3a_20core_3a_3aview_80',['Les vues : core::View&amp;lt;Components...&amp;gt;',['../guide-ecs.html#autotoc_md81',1,'']]],
  ['vues_20un_20repère_20de_20cases_81',['Deux vues, un repère de cases',['../CanvasPicking_8h.html#autotoc_md1182',1,'']]]
];
