var searchData=
[
  ['jadg_5fassert_20jadg_5fassert_20un_20outil_20différent_0',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md128',1,'']]],
  ['jadg_5fassert_20un_20outil_20différent_1',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md128',1,'']]],
  ['jalon_2',['Jalon',['../lot-07.html#autotoc_md354',1,'']]],
  ['jamais_20coder_20«_20en_20dur_20»_20une_20touche_20dans_20le_20gameplay_3',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md98',1,'']]],
  ['jamais_20dessus_4',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md543',1,'']]],
  ['jamais_20l_20inverse_5',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md93',1,'']]],
  ['jamais_20où_6',['Une rencontre dit QUI, jamais OÙ',['../lot-18.html#autotoc_md435',1,'']]],
  ['jamais_20perdu_20de_20vue_7',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md602',1,'']]],
  ['jamais_20tenu_20à_20la_20main_8',['Le manifeste est dérivé, jamais tenu à la main',['../lot-39.html#autotoc_md570',1,'']]],
  ['jamais_20un_20chemin_9',['Une clé, jamais un chemin',['../lot-39.html#autotoc_md568',1,'']]],
  ['jamais_20un_20singleton_20joueur_10',['&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur',['../lot-13.html#autotoc_md404',1,'']]],
  ['jamais_20une_20case_11',['Deux créatures ne partagent jamais une case',['../lot-19.html#autotoc_md444',1,'']]],
  ['jamais_20une_20chaîne_12',['Une statistique est une liste, jamais une chaîne',['../lot-37.html#autotoc_md550',1,'']]],
  ['jamais_20une_20géométrie_13',['jamais une géométrie',['../lot-19.html#autotoc_md443',1,'L&apos;altitude est un attribut, jamais une géométrie'],['../namespacecore.html#autotoc_md1138',1,'L&apos;altitude est un attribut, jamais une géométrie']]],
  ['jauges_14',['Jauges',['../lot-87-cahier-assets.html#lot-87-cahier-gauge',1,'']]],
  ['jetée_20une_20fois_20départagée_20par_20une_20règle_20écrite_15',['L&apos;initiative : jetée une fois, départagée par une règle écrite',['../lot-20.html#autotoc_md455',1,'']]],
  ['jet_16',['1. Le jet',['../spec-regles-d20.html#autotoc_md279',1,'']]],
  ['jet_20qui_20est_20un_20objet_17',['jet qui est un objet',['../lot-21.html#autotoc_md468',1,'Un jet qui est un objet'],['../Attack_8h.html#autotoc_md1136',1,'Un jet qui est un objet']]],
  ['jetons_18',['jetons',['../guide-conception-qds.html#autotoc_md53',1,'Les contrôles Qt prennent la couleur des jetons'],['../lot-87.html#autotoc_md678',1,'T2.2 — Les jetons']]],
  ['jetons_20_3a_20le_20seul_20endroit_20où_20s_20écrit_20une_20couleur_19',['Les jetons : le seul endroit où s&apos;écrit une couleur',['../guide-conception-qds.html#autotoc_md49',1,'']]],
  ['jets_20',['LOT-12 — Dés, caractéristiques, jets',['../lot-12.html',1,'lots']]],
  ['jets_20trois_20usages_21',['3. Trois jets, trois usages',['../spec-regles-d20.html#autotoc_md281',1,'']]],
  ['jeu_22',['jeu',['../guide-ecrans.html',1,'Écrans, navigation et boucle de jeu'],['../lot-88.html#autotoc_md706',1,'1. L&apos;essai de l&apos;éditeur joue le jeu'],['../spec-gameplay.html#autotoc_md254',1,'2. États de jeu'],['../spec-controles.html#autotoc_md198',1,'2. Commandes du jeu'],['../spec-interface-ihm.html#autotoc_md262',1,'7. Identité visuelle des écrans du jeu'],['../roadmap-editeur.html#roadmap-editeur-contacts',1,'7. Points de contact avec le jeu'],['../CanvasScene_8h.html#autotoc_md1185',1,'La même scène que le jeu'],['../ExplorationReach_8h.html#autotoc_md1178',1,'La règle, et pourquoi c&apos;est celle du jeu'],['../guide-ihm-qt.html#autotoc_md109',1,'Les trois couches du jeu'],['../lot-05.html',1,'LOT-05 — Modes de jeu'],['../roadmap-editeur.html#lot-editor-10',1,'LOT-EDITOR-10 — Essai complet dans le jeu'],['../guide-boucle.html#autotoc_md36',1,'Qu&apos;est-ce qu&apos;une boucle de jeu ?'],['../manuel-telecharger.html',1,'Télécharger et lancer le jeu'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-01-carte-test-textures.html',1,'T01 — Carte de test des textures dans le jeu']]],
  ['jeu_20d_20animations_23',['Le jeu d&apos;animations',['../lot-91.html#autotoc_md717',1,'']]],
  ['jeu_20d_20origine_24',['Tags du jeu d&apos;origine',['../lot-88.html#autotoc_md712',1,'']]],
  ['jeu_20en_20code_20pour_20l_20éditeur_25',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['jeu_20et_20la_20session_20qui_20lui_20survit_26',['La vue de jeu et la session qui lui survit',['../guide-ecrans.html#autotoc_md70',1,'']]],
  ['jeu_20et_20pas_20de_20temps_20fixe_27',['Boucle de jeu et pas de temps fixe',['../guide-boucle.html',1,'guide']]],
  ['jeu_20et_20première_20carte_28',['LOT-09 — Le Colisée se parcourt : exploration dans le jeu et première carte',['../lot-09.html',1,'lots']]],
  ['jeu_20maquette_2001_20sans_20la_20scène_29',['T4.1 — Le HUD de jeu (maquette 01), sans la scène',['../lot-87.html#autotoc_md696',1,'']]],
  ['jeu_20vidéo_30',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md118',1,'']]],
  ['jeux_20une_20planche_20chacun_31',['Les textures — trois jeux, une planche chacun',['../roadmap.html#autotoc_md983',1,'']]],
  ['jouées_32',['LOT-CREATION-ASSETS — Produire selon les régions jouées',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html',1,'']]],
  ['joue_20le_20jeu_33',['1. L&apos;essai de l&apos;éditeur joue le jeu',['../lot-88.html#autotoc_md706',1,'']]],
  ['jouer_34',['Jouer',['../manuel-jouer.html',1,'manuel']]],
  ['jouer_20sans_20quitter_20l_20éditeur_35',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md92',1,'']]],
  ['joueur_36',['&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur',['../lot-13.html#autotoc_md404',1,'']]],
  ['joueur_20ne_20s_20arrête_20que_20sur_20une_20réplique_37',['Le joueur ne s&apos;arrête que sur une réplique',['../classcore_1_1DialogueRunner.html#autotoc_md1174',1,'']]],
  ['joueur_20voit_38',['joueur voit',['../lot-67.html#autotoc_md607',1,'Ce que le joueur voit'],['../lot-68.html#autotoc_md615',1,'Ce que le joueur voit']]],
  ['joueurs_20est_20un_20scan_20et_20sa_20graisse_20ment_39',['Le &lt;em&gt;Manuel des Joueurs&lt;/em&gt; est un scan, et sa graisse ment',['../lot-36.html#autotoc_md536',1,'']]],
  ['jour_40',['jour',['../lot-33.html#autotoc_md519',1,'Cinq défauts du lexique que les 94 noms ont mis au jour'],['../lot-94.html#autotoc_md761',1,'Deux temps, le même jour'],['../lot-43.html#autotoc_md578',1,'Trois défauts du corpus que ce lot a mis au jour']]],
  ['journal_41',['Journal',['../lot-09.html#autotoc_md372',1,'Journal'],['../lot-91-poc.html#autotoc_md736',1,'Journal'],['../lot-92.html#autotoc_md745',1,'Journal'],['../lot-94.html#autotoc_md768',1,'Journal'],['../lot-96.html#autotoc_md776',1,'Journal']]],
  ['journal_20_3a_20restylés_42',['T3.9 — Pause, dialogue, marchand, journal : restylés',['../lot-87.html#autotoc_md693',1,'']]],
  ['journal_20c_20est_20une_20exigence_43',['La restitution n&apos;est pas un journal, c&apos;est une exigence',['../lot-12.html#autotoc_md396',1,'']]],
  ['journalisation_44',['10. Assertions &amp;amp; journalisation',['../spec-conventions.html#autotoc_md218',1,'']]],
  ['journalisation_20et_20assertions_45',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['journalisation_20par_20catégorie_46',['Les macros de journalisation, par catégorie',['../guide-journalisation.html#autotoc_md122',1,'']]],
  ['journaliser_20dans_20un_20jeu_20vidéo_47',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md118',1,'']]],
  ['jours_48',['9.6 Second audit, 14 septembre 2026 : ce qui avait dérivé en dix jours',['../roadmap.html#autotoc_md952',1,'']]],
  ['json_49',['Chargement JSON',['../guide-niveaux.html#autotoc_md144',1,'']]],
  ['json_20liste_20de_20tuiles_20objets_50',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md276',1,'']]],
  ['jumeau_20qt_20quick_20de_20qrhiwidget_51',['Le jumeau Qt Quick de &lt;span class=&quot;tt&quot;&gt;QRhiWidget&lt;/span&gt;',['../classhmi_1_1GameViewportItem.html#autotoc_md1227',1,'']]],
  ['jusqu_20au_20vertical_20slice_52',['Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;',['../roadmap.html#autotoc_md935',1,'']]],
  ['justanotherrpggame_53',['JustAnotherRpgGame',['../index.html',1,'']]]
];
