var searchData=
[
  ['hérités_0',['LOT-78 — Désambiguïsation des numéros de lots hérités',['../lot-78.html',1,'lots']]],
  ['héritage_20_3a_20code_20assets_20et_20spécifications_1',['LOT-88 — Retrait de l&apos;héritage : code, assets et spécifications',['../lot-88.html',1,'lots']]],
  ['héros_20unique_2',['héros unique',['../lot-20.html#autotoc_md463',1,'Sans héros unique'],['../classcore_1_1CombatState.html#autotoc_md1027',1,'Sans héros unique']]],
  ['habillage_3',['5. Système de design et habillage',['../spec-interface-ihm.html#autotoc_md262',1,'']]],
  ['habillage_20d_20interface_20extrait_20des_20livres_4',['LOT-76 — Habillage d&apos;interface extrait des livres',['../lot-76.html',1,'lots']]],
  ['habillage_20de_20l_20arène_2014_20septembre_202026_20après_20livraison_5',['Habillage de l&apos;arène (14 septembre 2026, après livraison)',['../lot-50.html#autotoc_md594',1,'']]],
  ['habiller_6',['Maquetter, jouer, puis habiller',['../guide-editeur.html#guide-editeur-maquette',1,'']]],
  ['habitants_20—_20les_20figurines_20de_20l_20atelier_7',['Les habitants — les figurines de l&apos;atelier',['../roadmap.html#autotoc_md853',1,'']]],
  ['hasard_8',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md1041',1,'']]],
  ['haut_20se_20désigne_20par_20son_20pied_9',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md1063',1,'']]],
  ['hauteur_20réservée_20d11_10',['La hauteur, réservée (D11)',['../CanvasPicking_8h.html#autotoc_md1064',1,'']]],
  ['header_20commentaires_20simples_20dans_20le_20cpp_11',['Doxygen dans le header, commentaires simples // dans le .cpp',['../spec-conventions.html#autotoc_md214',1,'']]],
  ['historique_12',['2. Espèce et historique',['../spec-rpg.html#autotoc_md295',1,'']]],
  ['historiques_20et_20classes_20provisoires_13',['LOT-36 — Espèces, historiques et classes provisoires',['../lot-36.html',1,'lots']]],
  ['hmi_14',['HMI',['../spec-rendu-technique.html#autotoc_md290',1,'4. Interface (HMI)'],['../cahiertest.html#autotoc_md18',1,'HMI']]],
  ['hmi_3a_3aaudioengine_15',['Le socle : &lt;span class=&quot;tt&quot;&gt;hmi::AudioEngine&lt;/span&gt;',['../guide-audio.html#autotoc_md33',1,'']]],
  ['hmi_3a_3acamera2d_16',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md153',1,'']]],
  ['hmi_3a_3acamera2d_20hmi_3a_3acamera2d_17',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md153',1,'']]],
  ['hmi_3a_3aeditorkeybindings_20editorkeybindings_18',['Les raccourcis de l&apos;éditeur : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt;',['../guide-entrees.html#autotoc_md106',1,'']]],
  ['hmi_3a_3aeditortool_20editortool_19',['Quatre outils, une même grille : &lt;a class=&quot;el&quot; href=&quot;namespacehmi.html#a02048ad8ad69a87a10e8307ac2bd68dd&quot; title=&quot;hmi::EditorTool&quot;&gt;EditorTool&lt;/a&gt;',['../guide-editeur.html#autotoc_md90',1,'']]],
  ['hmi_3a_3ainputstate_20',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md101',1,'']]],
  ['hmi_3a_3ainputstate_20hmi_3a_3ainputstate_21',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md101',1,'']]],
  ['hmi_3a_3alinequad_20linequad_20_3a_20un_20segment_20orienté_22',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1LineQuad.html&quot; title=&quot;hmi::LineQuad&quot;&gt;LineQuad&lt;/a&gt; : un segment orienté',['../guide-rendu.html#autotoc_md159',1,'']]],
  ['hmi_3a_3alocalization_23',['La langue de l&apos;interface : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Localization.html&quot; title=&quot;hmi::Localization&quot;&gt;hmi::Localization&lt;/a&gt;',['../guide-entrees.html#autotoc_md107',1,'']]],
  ['hmi_3a_3alocalization_20hmi_3a_3alocalization_24',['La langue de l&apos;interface : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Localization.html&quot; title=&quot;hmi::Localization&quot;&gt;hmi::Localization&lt;/a&gt;',['../guide-entrees.html#autotoc_md107',1,'']]],
  ['hmi_3a_3ascreenflow_25',['La machine à états : &lt;span class=&quot;tt&quot;&gt;hmi::ScreenFlow&lt;/span&gt;',['../guide-ecrans.html#autotoc_md69',1,'']]],
  ['hmi_3a_3aspritebatch_26',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_27',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['hmi_3a_3aspritequad_20spritequad_20_3a_20un_20rectangle_20texturé_28',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md157',1,'']]],
  ['hmi_3a_3atextureatlas_20_3a_20l_20atlas_20des_20couleurs_20plates_29',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : l&apos;atlas des couleurs plates',['../guide-rendu.html#autotoc_md161',1,'']]],
  ['hmi_3a_3atextureatlas_20hmi_3a_3atextureatlas_20_3a_20l_20atlas_20des_20couleurs_20plates_30',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : l&apos;atlas des couleurs plates',['../guide-rendu.html#autotoc_md161',1,'']]],
  ['hmilib_31',['LOT-02 — Bibliothèque `HmiLib`',['../lot-02.html',1,'lots']]],
  ['hmilib_20»_32',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md321',1,'']]],
  ['honorer_33',['Décisions d&apos;écran à honorer',['../lot-86.html#autotoc_md651',1,'']]],
  ['honorer_20progressivement_34',['Importer tout, honorer progressivement',['../roadmap.html#autotoc_md797',1,'']]],
  ['horloge_20calendrier_20et_20lune_35',['&lt;span class=&quot;tt&quot;&gt;LOT-70&lt;/span&gt; — Horloge, calendrier et lune',['../roadmap.html#lot-70',1,'']]],
  ['hors_20code_20pour_20le_20jeu_20en_20code_20pour_20l_20éditeur_36',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md210',1,'']]],
  ['hors_20de_20ce_20fichier_37',['Hors de ce fichier',['../AreaOfEffect_8h.html#autotoc_md1012',1,'']]],
  ['hors_20de_20ce_20fichier_20nommément_38',['Hors de ce fichier, nommément',['../Attack_8h.html#autotoc_md1017',1,'']]],
  ['hors_20du_20lot_20nommément_39',['Hors du lot, nommément',['../lot-91.html#autotoc_md725',1,'']]],
  ['hors_20du_20lot_20nommément_40',['hors du lot nommément',['../lot-11.html#autotoc_md391',1,'Ce qui reste hors du lot, nommément'],['../lot-15.html#autotoc_md428',1,'Ce qui reste hors du lot, nommément'],['../lot-19.html#autotoc_md451',1,'Ce qui reste hors du lot, nommément'],['../lot-20.html#autotoc_md465',1,'Ce qui reste hors du lot, nommément'],['../lot-21.html#autotoc_md474',1,'Ce qui reste hors du lot, nommément'],['../lot-22.html#autotoc_md484',1,'Ce qui reste hors du lot, nommément'],['../lot-23.html#autotoc_md493',1,'Ce qui reste hors du lot, nommément'],['../lot-24.html#autotoc_md500',1,'Ce qui reste hors du lot, nommément'],['../lot-50.html#autotoc_md595',1,'Ce qui reste hors du lot, nommément'],['../lot-92.html#autotoc_md742',1,'Ce qui reste hors du lot, nommément'],['../lot-94.html#autotoc_md766',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-01.html#autotoc_md914',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-02.html#autotoc_md920',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-03.html#autotoc_md927',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-04.html#autotoc_md933',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-05.html#autotoc_md939',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-06.html#autotoc_md945',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-07.html#autotoc_md951',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-08.html#autotoc_md957',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-09.html#autotoc_md963',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-12.html#autotoc_md978',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-13.html#autotoc_md984',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-14.html#autotoc_md990',1,'Ce qui reste hors du lot, nommément']]],
  ['hors_20périmètre_20vertical_20slice_41',['Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)',['../spec-vision.html#autotoc_md307',1,'']]],
  ['hud_42',['Phase 4 — le cadre du HUD',['../lot-87.html#autotoc_md697',1,'']]],
  ['hud_20de_20jeu_20maquette_2001_20sans_20la_20scène_43',['T4.1 — Le HUD de jeu (maquette 01), sans la scène',['../lot-87.html#autotoc_md698',1,'']]],
  ['hui_44',['Ce que l&apos;écran est donc aujourd&apos;hui',['../lot-38.html#autotoc_md563',1,'']]],
  ['huit_20«_20oui_20»_45',['La revue (huit « oui »)',['../lot-93.html#autotoc_md753',1,'']]],
  ['huit_20écrans_20écrits_20à_20la_20main_46',['Une table, et non huit écrans écrits à la main',['../RpgScreens_8h.html#autotoc_md1097',1,'']]]
];
