var searchData=
[
  ['a_0',['3. Le style commun v1 (étape E2, bloc A)',['../lot-91-poc.html#autotoc_md730',1,'']]],
  ['a_20été_20fait_1',['a été fait',['../lot-88.html#autotoc_md707',1,'Ce qui a été fait'],['../lot-editor-10.html#autotoc_md1099',1,'Ce qui a été fait'],['../lot-87.html#autotoc_md669',1,'T1.2 à T1.4 — Ce qui a été fait']]],
  ['a_20été_20faite_2',['Comment la classification a été faite',['../lot-78.html#autotoc_md638',1,'']]],
  ['a_20été_20livré_20à_20l_20ouverture_3',['Ce qui a été livré à l&apos;ouverture',['../lot-93.html#autotoc_md756',1,'']]],
  ['a_20été_20retiré_20du_20code_4',['Ce qui a été retiré du code',['../lot-67.html#autotoc_md611',1,'']]],
  ['a_20appris_5',['4. Ce que l&apos;extraction a appris',['../roadmap.html#autotoc_md923',1,'']]],
  ['a_20arrêtée_6',['Ce qui l&apos;a arrêtée',['../lot-38.html#autotoc_md562',1,'']]],
  ['a_20changé_20et_20pourquoi_7',['Ce qui a changé, et pourquoi',['../spec-interface-ihm.html#autotoc_md267',1,'']]],
  ['a_20composé_20_3a_20tampons_20et_20préfabriqués_8',['Répéter ce qu&apos;on a composé : tampons et préfabriqués',['../guide-usage-editeur.html#autotoc_md1036',1,'']]],
  ['a_20démenti_9',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md504',1,'']]],
  ['a_20livré_10',['Ce que le lot a livré',['../lot-96.html#autotoc_md775',1,'']]],
  ['a_20livré_20et_20ce_20qu_20il_20n_20a_20pas_20livré_11',['Ce que le lot a livré, et ce qu&apos;il n&apos;a pas livré',['../lot-09.html#autotoc_md369',1,'']]],
  ['a_20mis_20au_20jour_12',['Trois défauts du corpus que ce lot a mis au jour',['../lot-43.html#autotoc_md580',1,'']]],
  ['a_20pas_20écrit_20de_20classdefinition_20_3a_20elle_20existait_20déjà_13',['Le lot n&apos;a pas écrit de &lt;span class=&quot;tt&quot;&gt;ClassDefinition&lt;/span&gt; : elle existait déjà',['../lot-13.html#autotoc_md404',1,'']]],
  ['a_20pas_20livré_14',['Ce que le lot a livré, et ce qu&apos;il n&apos;a pas livré',['../lot-09.html#autotoc_md369',1,'']]],
  ['a_20pas_20tenu_15',['Ce que la feuille de route supposait, et qui n&apos;a pas tenu',['../lot-19.html#autotoc_md443',1,'']]],
  ['a_20révélé_16',['Ce que l&apos;ordre a révélé',['../roadmap.html#autotoc_md936',1,'']]],
  ['a_20révélé_20sur_20l_20état_20du_20dépôt_17',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap.html#autotoc_md948',1,'']]],
  ['a_20retiré_18',['Ce que le &lt;span class=&quot;tt&quot;&gt;LOT-67&lt;/span&gt; a retiré',['../guide-ecrans.html#autotoc_md73',1,'']]],
  ['a_20sa_20propre_20catégorie_19',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md124',1,'']]],
  ['a_20tranché_20',['a tranché',['../lot-87-cahier-assets.html#autotoc_md658',1,'Ce que la lecture des maquettes a tranché'],['../lot-04.html#autotoc_md338',1,'Ce que la réalisation a tranché'],['../lot-05.html#autotoc_md345',1,'Ce que la réalisation a tranché'],['../lot-06.html#autotoc_md352',1,'Ce que la réalisation a tranché'],['../lot-08.html#autotoc_md364',1,'Ce que la réalisation a tranché'],['../lot-32.html#autotoc_md512',1,'Ce que la réalisation a tranché'],['../lot-79.html#autotoc_md644',1,'Ce que la réalisation a tranché'],['../lot-77.html#autotoc_md634',1,'Ce que la rédaction a tranché']]],
  ['a_20trouvé_21',['2. Ce que l&apos;audit a trouvé',['../roadmap-editeur.html#roadmap-editeur-audit',1,'']]],
  ['a_20trouvé_20à_20trancher_20par_20l_20auteur_22',['Ce que la migration a trouvé, à trancher par l&apos;auteur',['../lot-editor-12.html#autotoc_md1108',1,'']]],
  ['a_20vérifié_20et_20ce_20qu_20elle_20a_20démenti_23',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md504',1,'']]],
  ['abri_20_3a_20ce_20que_20la_20grille_20compte_24',['L&apos;abri : ce que la grille compte',['../lot-22.html#autotoc_md480',1,'']]],
  ['abstraction_20de_20rendu_25',['6. Abstraction de rendu',['../spec-architecture.html#autotoc_md180',1,'']]],
  ['accès_20au_20gpu_20pas_20un_20changement_20de_20cible_26',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md151',1,'']]],
  ['accentué_20reste_20tracé_20à_20l_20ancienne_20et_20ce_20n_20est_20pas_20un_20oubli_27',['L&apos;accentué reste tracé à l&apos;ancienne, et ce n&apos;est pas un oubli',['../lot-76.html#autotoc_md628',1,'']]],
  ['acceptation_28',['acceptation',['../lot-01.html#autotoc_md318',1,'Critères d&apos;acceptation'],['../lot-02.html#autotoc_md325',1,'Critères d&apos;acceptation'],['../lot-03.html#autotoc_md331',1,'Critères d&apos;acceptation'],['../lot-04.html#autotoc_md337',1,'Critères d&apos;acceptation'],['../lot-05.html#autotoc_md344',1,'Critères d&apos;acceptation'],['../lot-06.html#autotoc_md351',1,'Critères d&apos;acceptation'],['../lot-07.html#autotoc_md358',1,'Critères d&apos;acceptation'],['../lot-08.html#autotoc_md363',1,'Critères d&apos;acceptation'],['../lot-09.html#autotoc_md373',1,'Critères d&apos;acceptation'],['../lot-10.html#autotoc_md382',1,'Critères d&apos;acceptation'],['../lot-11.html#autotoc_md392',1,'Critères d&apos;acceptation'],['../lot-12.html#autotoc_md401',1,'Critères d&apos;acceptation'],['../lot-13.html#autotoc_md410',1,'Critères d&apos;acceptation'],['../lot-14.html#autotoc_md417',1,'Critères d&apos;acceptation'],['../lot-15.html#autotoc_md429',1,'Critères d&apos;acceptation'],['../lot-18.html#autotoc_md440',1,'Critères d&apos;acceptation'],['../lot-19.html#autotoc_md452',1,'Critères d&apos;acceptation'],['../lot-20.html#autotoc_md466',1,'Critères d&apos;acceptation'],['../lot-21.html#autotoc_md475',1,'Critères d&apos;acceptation'],['../lot-22.html#autotoc_md485',1,'Critères d&apos;acceptation'],['../lot-23.html#autotoc_md494',1,'Critères d&apos;acceptation'],['../lot-24.html#autotoc_md501',1,'Critères d&apos;acceptation'],['../lot-30.html#autotoc_md508',1,'Critères d&apos;acceptation'],['../lot-32.html#autotoc_md515',1,'Critères d&apos;acceptation'],['../lot-33.html#autotoc_md524',1,'Critères d&apos;acceptation'],['../lot-34.html#autotoc_md534',1,'Critères d&apos;acceptation'],['../lot-36.html#autotoc_md547',1,'Critères d&apos;acceptation'],['../lot-38.html#autotoc_md568',1,'Critères d&apos;acceptation'],['../lot-39.html#autotoc_md576',1,'Critères d&apos;acceptation'],['../lot-43.html#autotoc_md584',1,'Critères d&apos;acceptation'],['../lot-50.html#autotoc_md596',1,'Critères d&apos;acceptation'],['../lot-66.html#autotoc_md607',1,'Critères d&apos;acceptation'],['../lot-67.html#autotoc_md615',1,'Critères d&apos;acceptation'],['../lot-68.html#autotoc_md623',1,'Critères d&apos;acceptation'],['../lot-76.html#autotoc_md631',1,'Critères d&apos;acceptation'],['../lot-77.html#autotoc_md635',1,'Critères d&apos;acceptation'],['../lot-78.html#autotoc_md640',1,'Critères d&apos;acceptation'],['../lot-79.html#autotoc_md645',1,'Critères d&apos;acceptation'],['../lot-86.html#autotoc_md654',1,'Critères d&apos;acceptation'],['../lot-91.html#autotoc_md726',1,'Critères d&apos;acceptation'],['../lot-93.html#autotoc_md761',1,'Critères d&apos;acceptation'],['../lot-96.html#autotoc_md777',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md964',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md970',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md975',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md980',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md990',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md999',1,'Critères d&apos;acceptation'],['../roadmap.html#autotoc_md1005',1,'Critères d&apos;acceptation'],['../lot-editor-01.html#autotoc_md1044',1,'Critères d&apos;acceptation'],['../lot-editor-02.html#autotoc_md1050',1,'Critères d&apos;acceptation'],['../lot-editor-03.html#autotoc_md1056',1,'Critères d&apos;acceptation'],['../lot-editor-04.html#autotoc_md1063',1,'Critères d&apos;acceptation'],['../lot-editor-05.html#autotoc_md1069',1,'Critères d&apos;acceptation'],['../lot-editor-06.html#autotoc_md1075',1,'Critères d&apos;acceptation'],['../lot-editor-07.html#autotoc_md1081',1,'Critères d&apos;acceptation'],['../lot-editor-08.html#autotoc_md1087',1,'Critères d&apos;acceptation'],['../lot-editor-09.html#autotoc_md1093',1,'Critères d&apos;acceptation'],['../lot-editor-12.html#autotoc_md1107',1,'Critères d&apos;acceptation'],['../lot-editor-13.html#autotoc_md1114',1,'Critères d&apos;acceptation'],['../lot-editor-14.html#autotoc_md1120',1,'Critères d&apos;acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html#autotoc_md903',1,'Préparation, production et acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-02-arenarea-galender.html#autotoc_md905',1,'Préparation, production et acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html#autotoc_md898',1,'Production et acceptation']]],
  ['acceptation_20de_20la_20phase_200_29',['Critères d&apos;acceptation de la phase 0',['../lot-87.html#autotoc_md704',1,'']]],
  ['acceptation_20telle_20que_20vérifiée_30',['Acceptation, telle que vérifiée',['../lot-94.html#autotoc_md768',1,'']]],
  ['accumulateur_20_3a_20core_3a_3afixedtimestep_20core_3a_3afixedtimestep_31',['L&apos;accumulateur : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1FixedTimestep.html&quot; title=&quot;core::FixedTimestep&quot;&gt;core::FixedTimestep&lt;/a&gt;',['../guide-boucle.html#autotoc_md40',1,'']]],
  ['achète_32',['Rejouable à graine fixée : ce que cela achète',['../lot-50.html#autotoc_md588',1,'']]],
  ['acquiert_33',['Seule une victoire l&apos;acquiert',['../lot-18.html#autotoc_md435',1,'']]],
  ['action_20est_20une_20liste_34',['L&apos;économie d&apos;action est une liste',['../lot-20.html#autotoc_md459',1,'']]],
  ['action_20un_20fichier_35',['Une action, un fichier',['../ArenaAnimationDriver_8h.html#autotoc_md1207',1,'']]],
  ['actions_20logiques_36',['Entrées et actions logiques',['../guide-entrees.html',1,'guide']]],
  ['adversaire_37',['6. L&apos;adversaire',['../spec-combat.html#autotoc_md190',1,'']]],
  ['affaires_20de_20la_20capitale_20_3a_20quêtes_20et_20drapeaux_20de_20monde_38',['LOT-16 — Les affaires de la Capitale : quêtes et drapeaux de monde',['../roadmap.html#lot-16',1,'']]],
  ['affiché_20_3a_20une_20donnée_20et_20un_20échafaudage_20assumé_39',['Le personnage affiché : une donnée, et un échafaudage assumé',['../lot-38.html#autotoc_md565',1,'']]],
  ['affiché_20ou_20écrit_20comme_20non_20alimenté_40',['Un champ affiché, ou écrit comme non alimenté',['../lot-38.html#autotoc_md559',1,'']]],
  ['agencement_20trouvés_20en_20regardant_20l_20écran_41',['Trois défauts d&apos;agencement, trouvés en regardant l&apos;écran',['../lot-68.html#autotoc_md621',1,'']]],
  ['agonie_20et_20mort_42',['5. Agonie et mort',['../spec-combat.html#autotoc_md189',1,'']]],
  ['agonie_20et_20mort_43',['&lt;span class=&quot;tt&quot;&gt;LOT-72&lt;/span&gt; — Conditions, agonie et mort',['../roadmap.html#lot-72',1,'']]],
  ['agonie_20trouvera_20en_20place_44',['Ce que l&apos;agonie trouvera en place',['../lot-21.html#autotoc_md472',1,'']]],
  ['agrégat_20leveldata_45',['LOT-03 — Agrégat `LevelData`',['../lot-03.html',1,'lots']]],
  ['agrandissement_46',['Le facteur d&apos;agrandissement',['../guide-conception-qds.html#autotoc_md51',1,'']]],
  ['agrandissement_20reste_20entier_20pour_20une_20autre_20raison_47',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md602',1,'']]],
  ['ailleurs_20qu_20en_20dur_48',['Ce qui est figé ailleurs qu&apos;en dur',['../lot-12.html#autotoc_md399',1,'']]],
  ['ajoutées_20le_207_20septembre_202026_49',['Les ressources de table virtuelle (ajoutées le 7 septembre 2026)',['../roadmap.html#autotoc_md918',1,'']]],
  ['ajout_20et_20suppression_20_3a_20swap_20and_20pop_50',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md80',1,'']]],
  ['ajout_20pas_20une_20refonte_51',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md1001',1,'']]],
  ['aléatoires_20et_20contenu_20d_20ambiance_52',['&lt;span class=&quot;tt&quot;&gt;LOT-44&lt;/span&gt; — Noms, tables aléatoires et contenu d&apos;ambiance',['../roadmap.html#lot-44',1,'']]],
  ['algorithme_53',['Le départage est une règle, et elle ne dépend pas de l&apos;algorithme',['../lot-19.html#autotoc_md444',1,'']]],
  ['aligné_20aux_20axes_54',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Rect.html&quot; title=&quot;core::Rect&quot;&gt;Rect&lt;/a&gt; : le rectangle aligné aux axes',['../guide-maths.html#autotoc_md134',1,'']]],
  ['alimenté_55',['Un champ affiché, ou écrit comme non alimenté',['../lot-38.html#autotoc_md559',1,'']]],
  ['alimentés_56',['Les écrans dessinés mais pas encore alimentés',['../guide-conception-qds.html#autotoc_md53',1,'']]],
  ['allègement_20est_20le_20geste_20à_20plus_20fort_20levier_20du_20programme_57',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md951',1,'']]],
  ['aller_20retour_20est_20pur_20et_20c_20est_20ce_20qui_20le_20rend_20vérifiable_58',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md432',1,'']]],
  ['altitude_59',['L&apos;altitude',['../AreaOfEffect_8h.html#autotoc_md1142',1,'']]],
  ['altitude_20est_20un_20attribut_20jamais_20une_20géométrie_60',['altitude est un attribut jamais une géométrie',['../lot-19.html#autotoc_md445',1,'L&apos;altitude est un attribut, jamais une géométrie'],['../namespacecore.html#autotoc_md1149',1,'L&apos;altitude est un attribut, jamais une géométrie']]],
  ['ambiance_61',['&lt;span class=&quot;tt&quot;&gt;LOT-44&lt;/span&gt; — Noms, tables aléatoires et contenu d&apos;ambiance',['../roadmap.html#lot-44',1,'']]],
  ['anariel_20étape_20r_62',['4. La référence canonique : Anariel (étape R)',['../lot-91-poc.html#autotoc_md731',1,'']]],
  ['ancienne_20charte_63',['T5.2 — L&apos;ancienne charte',['../lot-87.html#autotoc_md701',1,'']]],
  ['ancienne_20et_20ce_20n_20est_20pas_20un_20oubli_64',['L&apos;accentué reste tracé à l&apos;ancienne, et ce n&apos;est pas un oubli',['../lot-76.html#autotoc_md628',1,'']]],
  ['and_20pop_65',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md80',1,'']]],
  ['angle_200_2062_20en_20pixel_20art_66',['Risque : l&apos;angle 0,62 en pixel art',['../lot-92.html#autotoc_md744',1,'']]],
  ['animation_20_3a_20des_20clips_20en_20données_67',['L&apos;animation : des clips en données',['../guide-rendu.html#autotoc_md164',1,'']]],
  ['animations_68',['Le jeu d&apos;animations',['../lot-91.html#autotoc_md719',1,'']]],
  ['annuler_20refaire_20_3a_20pourquoi_20des_20instantanés_20complets_69',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md92',1,'']]],
  ['anticiper_20tant_20que_20rien_20n_20est_20construit_70',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap.html#autotoc_md956',1,'']]],
  ['appelant_71',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md619',1,'']]],
  ['applicatif_72',['1. Socle applicatif',['../spec-interface-ihm.html#autotoc_md258',1,'']]],
  ['applications_20deux_20technologies_73',['IHM Qt — deux applications, deux technologies',['../guide-ihm-qt.html',1,'guide']]],
  ['applique_20quand_74',['Ce qui s&apos;applique quand',['../classhmi_1_1OptionsModel.html#autotoc_md1242',1,'']]],
  ['apporte_20chiffré_75',['Ce que chaque document apporte, chiffré',['../roadmap.html#autotoc_md919',1,'']]],
  ['apprentissage_20automatique_20ex_20ia_76',['Solveur d&apos;apprentissage automatique (&lt;span class=&quot;tt&quot;&gt;EX-IA-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md251',1,'']]],
  ['appris_77',['4. Ce que l&apos;extraction a appris',['../roadmap.html#autotoc_md923',1,'']]],
  ['approchée_78',['Égalité approchée',['../guide-maths.html#autotoc_md133',1,'']]],
  ['approche_20d_20implémentation_20décidée_79',['4. Approche d&apos;implémentation (décidée)',['../spec-editeur.html#autotoc_md226',1,'']]],
  ['après_20la_20sortie_20du_20pixel_20art_80',['Pourquoi le facteur reste entier après la sortie du pixel art',['../guide-design-ihm.html#autotoc_md67',1,'']]],
  ['après_20livraison_81',['Habillage de l&apos;arène (14 septembre 2026, après livraison)',['../lot-50.html#autotoc_md594',1,'']]],
  ['après_20lot_82',['Le plan d&apos;intégration : la Capitale, lot après lot',['../roadmap.html#roadmap-capitale',1,'']]],
  ['arène_83',['Par instantané, comme l&apos;arène',['../WorldSceneComposer_8h.html#autotoc_md1221',1,'']]],
  ['arène_2014_20septembre_202026_20après_20livraison_84',['Habillage de l&apos;arène (14 septembre 2026, après livraison)',['../lot-50.html#autotoc_md594',1,'']]],
  ['arène_20est_20et_20ce_20qu_20elle_20n_20est_20pas_85',['Ce que l&apos;arène est, et ce qu&apos;elle n&apos;est pas',['../Arena_8h.html#autotoc_md1144',1,'']]],
  ['arête_20n_20est_20contrôlée_20qu_20une_20fois_86',['Le triangle, et pourquoi chaque arête n&apos;est contrôlée qu&apos;une fois',['../lot-32.html#autotoc_md511',1,'']]],
  ['arborescence_20cible_87',['7. Arborescence cible',['../roadmap.html#autotoc_md941',1,'']]],
  ['architecture_88',['4. Architecture',['../roadmap-editeur.html#roadmap-editeur-architecture',1,'']]],
  ['architecture_20décisions_20dimensionnantes_89',['Architecture (décisions dimensionnantes)',['../spec-architecture.html',1,'specifications']]],
  ['architecture_20dépendances_20entre_20modules_90',['5. Architecture (dépendances entre modules)',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['architecture_20de_20l_20information_91',['6. Architecture de l&apos;information',['../spec-interface-ihm.html#autotoc_md263',1,'']]],
  ['architecture_20de_20l_20information_92',['Système de design et architecture de l&apos;information',['../guide-design-ihm.html',1,'guide']]],
  ['architecture_20de_20l_20information_20_3a_20ce_20qui_20informe_20reste_20ce_20qui_20commande_20est_20unique_93',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md62',1,'']]],
  ['architecture_20en_20deux_20couches_94',['Architecture en deux couches',['../guide.html#autotoc_md173',1,'']]],
  ['architecture_20maintenabilité_95',['2. Architecture &amp;amp; maintenabilité',['../spec-exigences.html#autotoc_md245',1,'']]],
  ['arenacamera_96',['Cadrer une scène : &lt;span class=&quot;tt&quot;&gt;fitZoom&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;worldCamera&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;arenaCamera&lt;/span&gt;',['../guide-rendu.html#autotoc_md154',1,'']]],
  ['arenarea_20et_20du_20colisée_97',['CE-R01 — Reprise intégrale de Martpart, Arenarea et du Colisée',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-r01-reprise-trois-sites.html',1,'']]],
  ['arenarea_20galender_20et_20l’arène_20du_20destin_98',['CE-02 — Arenarea, Galender et l’Arène du Destin',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-02-arenarea-galender.html',1,'']]],
  ['arenarea_20se_20parcourent_20_3a_20le_20graphe_20des_20quartiers_99',['LOT-96 — Martpart et Arenarea se parcourent : le graphe des quartiers',['../lot-96.html',1,'lots']]],
  ['arme_20n_20est_20pas_20dans_20sa_20rangée_100',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md528',1,'']]],
  ['arrêtée_101',['Ce qui l&apos;a arrêtée',['../lot-38.html#autotoc_md562',1,'']]],
  ['arrête_20que_20sur_20une_20réplique_102',['arrête que sur une réplique',['../classcore_1_1DialogueRunner.html#autotoc_md1185',1,'Le joueur ne s&apos;arrête que sur une réplique'],['../lot-15.html#autotoc_md422',1,'Le runner : pur, et il ne s&apos;arrête que sur une réplique']]],
  ['arrêtent_20la_20génération_103',['Deux contrôles qui arrêtent la génération',['../lot-33.html#autotoc_md519',1,'']]],
  ['arrêter_104',['Traverser n&apos;est pas s&apos;arrêter',['../lot-19.html#autotoc_md447',1,'']]],
  ['arrondis_20qui_20ne_20se_20voient_20pas_105',['Deux arrondis qui ne se voient pas',['../lot-12.html#autotoc_md396',1,'']]],
  ['arrondit_20à_20la_20case_20inférieure_106',['Le budget s&apos;arrondit à la case inférieure',['../lot-19.html#autotoc_md448',1,'']]],
  ['art_107',['art',['../lot-66.html',1,'LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art'],['../guide-design-ihm.html#autotoc_md67',1,'Pourquoi le facteur reste entier après la sortie du pixel art'],['../lot-92.html#autotoc_md744',1,'Risque : l&apos;angle 0,62 en pixel art']]],
  ['artiste_20passé_20le_2012_20septembre_202026_108',['T1.5 — Le test de l&apos;artiste, passé le 12 septembre 2026',['../lot-87.html#autotoc_md670',1,'']]],
  ['artistique_20reprise_20des_20maquettes_20supprimées_109',['La direction artistique, reprise des maquettes supprimées',['../lot-86.html#autotoc_md648',1,'']]],
  ['assemblée_110',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Level.html&quot; title=&quot;core::Level&quot;&gt;core::Level&lt;/a&gt; : la carte assemblée',['../guide-niveaux.html#autotoc_md142',1,'']]],
  ['assembler_20la_20frame_20complète_111',['Assembler la frame complète',['../guide-rendu.html#autotoc_md170',1,'']]],
  ['assertions_112',['Journalisation et assertions',['../guide-journalisation.html',1,'guide']]],
  ['assertions_20_3a_20jadg_5fassert_20jadg_5fassert_20un_20outil_20différent_113',['Assertions : &lt;a class=&quot;el&quot; href=&quot;Assert_8h.html#a2811f3d423b22f1a90179b4ed095f054&quot; title=&quot;JADG_ASSERT&quot;&gt;JADG_ASSERT&lt;/a&gt;, un outil différent',['../guide-journalisation.html#autotoc_md129',1,'']]],
  ['assertions_20journalisation_114',['10. Assertions &amp;amp; journalisation',['../spec-conventions.html#autotoc_md219',1,'']]],
  ['asset_20sert_20à_20déroger_115',['La clé se déduit ; le champ &lt;span class=&quot;tt&quot;&gt;asset&lt;/span&gt; sert à déroger',['../lot-39.html#autotoc_md571',1,'']]],
  ['assets_116',['Assets',['../spec-contenu.html#autotoc_md195',1,'5. Assets'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html#autotoc_md896',1,'Assets']]],
  ['assets_117',['assets',['../lot-39.html',1,'LOT-39 — Plomberie des clés d&apos;assets'],['../lot-87.html#autotoc_md681',1,'T2.4 — Le cahier des assets']]],
  ['assets_20—_20produire_20selon_20les_20régions_20jouées_118',['LOT-CREATION-ASSETS — Produire selon les régions jouées',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html',1,'']]],
  ['assets_20de_20la_20charte_20v2_119',['LOT-87 — Cahier des assets de la charte v2',['../lot-87-cahier-assets.html',1,'lot-87']]],
  ['assets_20et_20spécifications_120',['LOT-88 — Retrait de l&apos;héritage : code, assets et spécifications',['../lot-88.html',1,'lots']]],
  ['assets_20scripts_20et_20restes_20de_20code_121',['3. Assets, scripts et restes de code',['../lot-88.html#autotoc_md710',1,'']]],
  ['assistée_122',['LOT-EDITOR-11 — Génération assistée',['../roadmap-editeur.html#lot-editor-11',1,'']]],
  ['assumé_123',['assumé',['../lot-37.html#autotoc_md556',1,'Effet de bord assumé'],['../lot-38.html#autotoc_md565',1,'Le personnage affiché : une donnée, et un échafaudage assumé']]],
  ['assumé_20pas_20subi_124',['Le renversement est assumé, pas subi',['../lot-66.html#autotoc_md605',1,'']]],
  ['assumée_125',['Conséquence assumée',['../lot-01.html#autotoc_md315',1,'']]],
  ['assumée_20sur_20la_20liste_20de_20suppressions_126',['Une déviation assumée sur la liste de suppressions',['../lot-66.html#autotoc_md603',1,'']]],
  ['atelier_127',['atelier',['../lot-91.html#autotoc_md720',1,'L&apos;atelier'],['../lot-93.html#autotoc_md751',1,'L&apos;atelier'],['../roadmap.html#autotoc_md984',1,'Les habitants — les figurines de l&apos;atelier']]],
  ['atelier_20des_20monstres_20_3a_20les_20figurines_20du_20bestiaire_20depuis_20le_20texte_20seul_128',['LOT-93 — Atelier des monstres : les figurines du bestiaire, depuis le texte seul',['../lot-93.html',1,'lots']]],
  ['atelier_20des_20pnj_20_3a_20les_20figurines_20du_20character_20compendium_129',['LOT-91 — Atelier des PNJ : les figurines du Character Compendium',['../lot-91.html',1,'lots']]],
  ['atelier_20des_20textures_20_3a_20le_20style_20de_20la_20scène_20par_20maquette_20une_20planche_20par_20lieu_130',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['atlas_20des_20couleurs_20plates_131',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : l&apos;atlas des couleurs plates',['../guide-rendu.html#autotoc_md161',1,'']]],
  ['atlas_20des_20régions_20et_20graphe_20de_20cartes_132',['LOT-37 — Atlas des régions et graphe de cartes',['../lot-37.html',1,'lots']]],
  ['atlas_20du_20monde_133',['7. Atlas du monde',['../spec-contenu.html#autotoc_md197',1,'']]],
  ['atlas_20procédural_20fichiers_20et_20replis_134',['Les textures : atlas procédural, fichiers et replis',['../guide-rendu.html#autotoc_md160',1,'']]],
  ['attaque_20et_20dégâts_135',['4. Attaque et dégâts',['../spec-combat.html#autotoc_md188',1,'']]],
  ['attaques_20dégâts_20et_20états_136',['LOT-21 — Attaques, dégâts et états',['../lot-21.html',1,'lots']]],
  ['attaques_20du_20manuel_137',['Les attaques du Manuel',['../Arena_8h.html#autotoc_md1145',1,'']]],
  ['atteignent_138',['Les réglages, et ce qu&apos;ils atteignent',['../guide-ihm-qt.html#autotoc_md116',1,'']]],
  ['attente_20—_20deux_20décisions_139',['Conservé contre l&apos;attente — deux décisions',['../lot-01.html#autotoc_md314',1,'']]],
  ['attention_20_3a_20le_20texte_20des_20maquettes_20était_20périmé_140',['Attention : le texte des maquettes était périmé',['../lot-86.html#autotoc_md649',1,'']]],
  ['attesté_20pas_20saisi_141',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md505',1,'']]],
  ['attribut_20jamais_20une_20géométrie_142',['attribut jamais une géométrie',['../lot-19.html#autotoc_md445',1,'L&apos;altitude est un attribut, jamais une géométrie'],['../namespacecore.html#autotoc_md1149',1,'L&apos;altitude est un attribut, jamais une géométrie']]],
  ['au_20colisée_143',['Combattre au Colisée',['../manuel-jouer.html#autotoc_md1124',1,'']]],
  ['au_20delà_20du_20moteur_144',['Objectifs produit (au-delà du moteur)',['../spec-vision.html#autotoc_md306',1,'']]],
  ['au_20gpu_20pas_20un_20changement_20de_20cible_145',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md151',1,'']]],
  ['au_20jour_146',['au jour',['../lot-33.html#autotoc_md521',1,'Cinq défauts du lexique que les 94 noms ont mis au jour'],['../lot-43.html#autotoc_md580',1,'Trois défauts du corpus que ce lot a mis au jour']]],
  ['au_20lancement_147',['Configurer le niveau minimal au lancement',['../guide-journalisation.html#autotoc_md127',1,'']]],
  ['au_20moteur_148',['Le volume : de l&apos;écran des options au moteur',['../guide-audio.html#autotoc_md34',1,'']]],
  ['au_20moteur_20—_20relecture_20du_2014_20septembre_202026_149',['4bis. Ce que les deux livres imposent au moteur — relecture du 14 septembre 2026',['../roadmap.html#autotoc_md925',1,'']]],
  ['au_20texte_20de_20la_20feuille_20de_20route_150',['Écarts par rapport au texte de la feuille de route',['../lot-88.html#autotoc_md712',1,'']]],
  ['au_20vertical_20slice_151',['Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;',['../roadmap.html#autotoc_md937',1,'']]],
  ['aucun_20texte_152',['Le graphe ne porte aucun texte',['../lot-15.html#autotoc_md420',1,'']]],
  ['aucune_20statistique_20n_20est_20stockée_20ici_153',['Aucune statistique n&apos;est stockée ici',['../structcore_1_1Inventory.html#autotoc_md1187',1,'']]],
  ['aucune_20valeur_20de_20règle_20dans_20le_20c_20»_20se_20vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_154',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md405',1,'']]],
  ['audio_155',['Audio',['../spec-rendu-technique.html#autotoc_md291',1,'5. Audio'],['../guide-audio.html',1,'Audio'],['../roadmap.html#autotoc_md993',1,'Audio']]],
  ['audio_203_156',['Audio (3)',['../cahiertest.html#autotoc_md19',1,'']]],
  ['audio_20effets_20et_20version_200_200_201_157',['LOT-28 — Audio, effets et version &lt;span class=&quot;tt&quot;&gt;0.0.1&lt;/span&gt;',['../roadmap.html#lot-28',1,'']]],
  ['audit_158',['Texte d&apos;origine (feuille de route, second audit)',['../lot-88.html#autotoc_md716',1,'']]],
  ['audit_2014_20septembre_202026_20_3a_20ce_20qui_20avait_20dérivé_20en_20dix_20jours_159',['9.6 Second audit, 14 septembre 2026 : ce qui avait dérivé en dix jours',['../roadmap.html#autotoc_md954',1,'']]],
  ['audit_20a_20révélé_20sur_20l_20état_20du_20dépôt_160',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap.html#autotoc_md948',1,'']]],
  ['audit_20a_20trouvé_161',['2. Ce que l&apos;audit a trouvé',['../roadmap-editeur.html#roadmap-editeur-audit',1,'']]],
  ['aujourd_20hui_162',['Ce que l&apos;écran est donc aujourd&apos;hui',['../lot-38.html#autotoc_md563',1,'']]],
  ['aurait_20pas_20vu_163',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md395',1,'']]],
  ['aussi_164',['aussi',['../guide-audio.html#autotoc_md36',1,'Voir aussi'],['../guide-boucle.html#autotoc_md46',1,'Voir aussi'],['../guide-conception-qds.html#autotoc_md60',1,'Voir aussi'],['../guide-design-ihm.html#autotoc_md68',1,'Voir aussi'],['../guide-ecrans.html#autotoc_md75',1,'Voir aussi'],['../guide-ecs.html#autotoc_md84',1,'Voir aussi'],['../guide-editeur.html#autotoc_md98',1,'Voir aussi'],['../guide-entrees.html#autotoc_md108',1,'Voir aussi'],['../guide-ihm-qt.html#autotoc_md118',1,'Voir aussi'],['../guide-journalisation.html#autotoc_md130',1,'Voir aussi'],['../guide-maths.html#autotoc_md137',1,'Voir aussi'],['../guide-niveaux.html#autotoc_md149',1,'Voir aussi'],['../guide-rendu.html#autotoc_md171',1,'Voir aussi']]],
  ['autant_165',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md520',1,'']]],
  ['auteur_166',['auteur',['../lot-editor-12.html#autotoc_md1108',1,'Ce que la migration a trouvé, à trancher par l&apos;auteur'],['../PlaceAppearance_8h.html#autotoc_md1218',1,'La règle, décidée le 17 septembre 2026 (&lt;em&gt;décision de l&apos;auteur&lt;/em&gt;)']]],
  ['auteur_2018_20septembre_202026_167',['Décisions de l&apos;auteur (18 septembre 2026)',['../lot-88.html#autotoc_md706',1,'']]],
  ['auteur_20_3a_20monde_20région_20ville_168',['LOT-94 — Les images du corpus quittent le dépôt ; l&apos;écran « Carte » revient sur les cartes de l&apos;auteur : monde, région, ville',['../lot-94.html',1,'lots']]],
  ['auto_20teste_169',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md506',1,'']]],
  ['auto_20teste_20faute_20de_20données_20à_20valider_170',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md513',1,'']]],
  ['automatique_20ex_20ia_171',['Solveur d&apos;apprentissage automatique (&lt;span class=&quot;tt&quot;&gt;EX-IA-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md251',1,'']]],
  ['automatisé_172',['11. Outillage qualité (automatisé)',['../spec-conventions.html#autotoc_md220',1,'']]],
  ['autonome_20jamais_20un_20singleton_20joueur_173',['&lt;span class=&quot;tt&quot;&gt;CharacterSheet&lt;/span&gt; est un objet autonome, jamais un singleton joueur',['../lot-13.html#autotoc_md406',1,'']]],
  ['autour_20lot_20editor_2009_174',['Plusieurs cartes à la fois, et le monde autour (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-09&lt;/span&gt;)',['../guide-usage-editeur.html#autotoc_md1038',1,'']]],
  ['autre_175',['autre',['../lot-editor-10.html#autotoc_md1100',1,'Côté jeu — trois options, rien d&apos;autre'],['../lot-36.html#autotoc_md540',1,'Sa gouttière bouge d&apos;une page à l&apos;autre']]],
  ['autre_20chose_20que_20des_20intentions_176',['Ce qui rend ces exigences autre chose que des intentions',['../spec-interface-ihm.html#autotoc_md270',1,'']]],
  ['autre_20raison_177',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md602',1,'']]],
  ['autrement_178',['Ce que le corpus dit, et que la feuille de route disait autrement',['../lot-36.html#autotoc_md542',1,'']]],
  ['autres_179',['5. Récupérer les cartes des autres',['../manuel-partager-niveau.html#autotoc_md1132',1,'']]],
  ['aux_20axes_180',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Rect.html&quot; title=&quot;core::Rect&quot;&gt;Rect&lt;/a&gt; : le rectangle aligné aux axes',['../guide-maths.html#autotoc_md134',1,'']]],
  ['aux_20images_20produites_181',['T2.5 — Le manifeste étendu aux images produites',['../lot-87.html#autotoc_md682',1,'']]],
  ['aux_20trois_20niveaux_182',['Les commandes, les mêmes aux trois niveaux',['../lot-94.html#autotoc_md765',1,'']]],
  ['avait_20dérivé_20en_20dix_20jours_183',['9.6 Second audit, 14 septembre 2026 : ce qui avait dérivé en dix jours',['../roadmap.html#autotoc_md954',1,'']]],
  ['avancement_184',['Avancement',['../index.html#autotoc_md2',1,'']]],
  ['avancement_185',['État d&apos;avancement',['../roadmap.html#roadmap-avancement',1,'']]],
  ['avant_20d_20écrire_186',['T1.1 — Le diagnostic, avant d&apos;écrire',['../lot-87.html#autotoc_md668',1,'']]],
  ['avant_20d_20écrire_20jamais_20l_20inverse_187',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md94',1,'']]],
  ['avant_20données_188',['2. Contrats avant données',['../spec-contenu.html#autotoc_md192',1,'']]],
  ['avec_20eux_189',['Les ornements restent tracés, et &lt;span class=&quot;tt&quot;&gt;EX-IHM-075&lt;/span&gt; avec eux',['../spec-interface-ihm.html#autotoc_md269',1,'']]],
  ['avec_20l_20interface_190',['Les surfaces de dessin : un élément composé avec l&apos;interface',['../guide-rendu.html#autotoc_md152',1,'']]],
  ['avec_20le_20jeu_191',['7. Points de contact avec le jeu',['../roadmap-editeur.html#roadmap-editeur-contacts',1,'']]],
  ['avec_20les_20pièces_20du_20lieu_192',['avec les pièces du lieu',['../lot-editor-03.html',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu'],['../roadmap-editeur.html#autotoc_md1015',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu']]],
  ['avec_20les_20pièces_20du_20lieu_20lot_20editor_2003_193',['11. Peindre avec les pièces du lieu (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-03&lt;/span&gt;)',['../spec-editeur.html#autotoc_md233',1,'']]],
  ['avec_20son_20lieu_194',['1. Créer la carte, avec son lieu',['../guide-usage-editeur.html#autotoc_md1028',1,'']]],
  ['aventuriers_20_3a_20rangs_20et_20contrats_195',['&lt;span class=&quot;tt&quot;&gt;LOT-45&lt;/span&gt; — Guilde des Aventuriers : rangs et contrats',['../roadmap.html#lot-45',1,'']]],
  ['axes_196',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Rect.html&quot; title=&quot;core::Rect&quot;&gt;Rect&lt;/a&gt; : le rectangle aligné aux axes',['../guide-maths.html#autotoc_md134',1,'']]]
];
