var searchData=
[
  ['pénombral_0',['&lt;span class=&quot;tt&quot;&gt;LOT-90&lt;/span&gt; — Le plan pénombral',['../roadmap.html#lot-90',1,'']]],
  ['pénombre_1',['Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html',1,'Pénombre'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md831',1,'Première série proposée — Pénombre']]],
  ['périmètre_2',['Périmètre',['../lot-01.html#autotoc_md311',1,'Périmètre'],['../lot-02.html#autotoc_md322',1,'Périmètre'],['../lot-03.html#autotoc_md328',1,'Périmètre'],['../lot-04.html#autotoc_md334',1,'Périmètre'],['../lot-05.html#autotoc_md341',1,'Périmètre'],['../lot-06.html#autotoc_md348',1,'Périmètre'],['../lot-07.html#autotoc_md355',1,'Périmètre'],['../lot-08.html#autotoc_md360',1,'Périmètre'],['../lot-09.html#autotoc_md372',1,'Périmètre'],['../lot-77.html#autotoc_md633',1,'Périmètre'],['../lot-78.html#autotoc_md637',1,'Périmètre'],['../roadmap.html#autotoc_md961',1,'Périmètre'],['../roadmap.html#autotoc_md967',1,'Périmètre'],['../roadmap.html#autotoc_md972',1,'Périmètre'],['../roadmap.html#autotoc_md977',1,'Périmètre'],['../roadmap.html#autotoc_md982',1,'Périmètre'],['../roadmap.html#autotoc_md992',1,'Périmètre'],['../roadmap.html#autotoc_md1002',1,'Périmètre']]],
  ['périmètre_3',['Vision &amp;amp; périmètre',['../spec-vision.html',1,'specifications']]],
  ['périmètre_20vertical_20slice_4',['Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)',['../spec-vision.html#autotoc_md307',1,'']]],
  ['périmé_5',['Attention : le texte des maquettes était périmé',['../lot-86.html#autotoc_md649',1,'']]],
  ['périphériques_6',['1. Périphériques',['../spec-controles.html#autotoc_md198',1,'']]],
  ['pack_20de_20maquettes_7',['T5.1 — Le pack de maquettes',['../lot-87.html#autotoc_md700',1,'']]],
  ['page_20à_20l_20autre_8',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md540',1,'']]],
  ['page_20hors_20code_20pour_20le_20jeu_20en_20code_20pour_20l_20éditeur_9',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md210',1,'']]],
  ['pages_10',['Pages',['../manuel.html#autotoc_md1127',1,'']]],
  ['paie_11',['C&apos;est le lot où le §4 se paie',['../lot-34.html#autotoc_md527',1,'']]],
  ['palette_20est_20relevée_20pas_20choisie_12',['La palette est relevée, pas choisie',['../lot-66.html#autotoc_md599',1,'']]],
  ['palette_20et_20les_20outils_20_3a_20des_20panneaux_20qt_20séparés_20du_20canevas_13',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md89',1,'']]],
  ['palette_20relevée_14',['La palette relevée',['../lot-87.html#autotoc_md677',1,'']]],
  ['panneaux_20groupés_20et_20qui_20suivent_20l_20outil_15',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md64',1,'']]],
  ['panneaux_20qt_20séparés_20du_20canevas_16',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md89',1,'']]],
  ['panthéon_20et_20expressions_20matérielles_17',['Panthéon et expressions matérielles',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md788',1,'']]],
  ['panthéon_20et_20organisations_18',['&lt;span class=&quot;tt&quot;&gt;LOT-80&lt;/span&gt; — Factions, panthéon et organisations',['../roadmap.html#lot-80',1,'']]],
  ['par_20case_19',['La règle, case par case',['../CollisionDerivation_8h.html#autotoc_md1177',1,'']]],
  ['par_20catégorie_20',['Les macros de journalisation, par catégorie',['../guide-journalisation.html#autotoc_md123',1,'']]],
  ['par_20construction_21',['par construction',['../lot-22.html#autotoc_md479',1,'La symétrie, par construction'],['../LineOfSight_8h.html#autotoc_md1169',1,'La symétrie, par construction']]],
  ['par_20critère_22',['Trois règles de désignation, une par critère',['../lot-10.html#autotoc_md379',1,'']]],
  ['par_20instantané_23',['Lecture seule, et par instantané',['../ArenaSceneComposer_8h.html#autotoc_md1213',1,'']]],
  ['par_20instantané_20comme_20l_20arène_24',['Par instantané, comme l&apos;arène',['../WorldSceneComposer_8h.html#autotoc_md1221',1,'']]],
  ['par_20l_20écran_20et_20non_20par_20l_20appelant_25',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md619',1,'']]],
  ['par_20l_20appelant_26',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md619',1,'']]],
  ['par_20l_20auteur_27',['Ce que la migration a trouvé, à trancher par l&apos;auteur',['../lot-editor-12.html#autotoc_md1108',1,'']]],
  ['par_20la_20donnée_28',['Deux natures de déclencheur, distinguées par la donnée',['../lot-18.html#autotoc_md436',1,'']]],
  ['par_20le_20pied_20lot_2007_29',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md167',1,'']]],
  ['par_20lieu_30',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['par_20lot_31',['&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt; à &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt; — une classe par lot',['../roadmap.html#lot-51',1,'']]],
  ['par_20lot_20sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_32',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md91',1,'']]],
  ['par_20maquette_20une_20planche_20par_20lieu_33',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['par_20qstr_34',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1246',1,'']]],
  ['par_20rapport_20au_20texte_20de_20la_20feuille_20de_20route_35',['Écarts par rapport au texte de la feuille de route',['../lot-88.html#autotoc_md712',1,'']]],
  ['par_20son_20cadre_20pas_20à_20l_20estime_36',['L&apos;encart se lit par son cadre, pas à l&apos;estime',['../lot-37.html#autotoc_md551',1,'']]],
  ['par_20son_20pied_37',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md1194',1,'']]],
  ['par_20tour_38',['LOT-20 — Initiative et tour par tour',['../lot-20.html',1,'lots']]],
  ['par_20une_39',['Quatre corruptions d&apos;OCR déclarées, une par une',['../lot-36.html#autotoc_md539',1,'']]],
  ['par_20une_20règle_20écrite_40',['L&apos;initiative : jetée une fois, départagée par une règle écrite',['../lot-20.html#autotoc_md457',1,'']]],
  ['par_20vision_20contre_20une_20liste_20fermée_41',['7. La revue par vision, contre une liste fermée',['../lot-91-poc.html#autotoc_md734',1,'']]],
  ['par_20y_42',['LOT-07 — Rendu top-down et tri par Y',['../lot-07.html',1,'lots']]],
  ['parchemin_20pixel_43',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md664',1,'']]],
  ['parcourent_20_3a_20le_20graphe_20des_20quartiers_44',['LOT-96 — Martpart et Arenarea se parcourent : le graphe des quartiers',['../lot-96.html',1,'lots']]],
  ['parcourir_20le_20monde_45',['Parcourir le monde',['../manuel-jouer.html#autotoc_md1123',1,'']]],
  ['parcours_20en_20largeur_46',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1171',1,'']]],
  ['parcourt_20_3a_20exploration_20dans_20le_20jeu_20et_20première_20carte_47',['LOT-09 — Le Colisée se parcourt : exploration dans le jeu et première carte',['../lot-09.html',1,'lots']]],
  ['part_48',['part',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1227',1,'Pourquoi un item à part'],['../ExplorationSession_8h.html#autotoc_md1190',1,'Pourquoi une session à part']]],
  ['partagent_20jamais_20une_20case_49',['Deux créatures ne partagent jamais une case',['../lot-19.html#autotoc_md446',1,'']]],
  ['partager_20une_20carte_20sans_20ligne_20de_20commande_50',['Créer et partager une carte (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['partie_20»_20_3a_20un_20échafaudage_20et_20il_20est_20écrit_51',['« Nouvelle partie » : un échafaudage, et il est écrit',['../lot-68.html#autotoc_md620',1,'']]],
  ['partie_20dans_20la_20capitale_20_3a_20sauvegarde_20riche_52',['LOT-17 — Reprendre sa partie dans la Capitale : sauvegarde riche',['../roadmap.html#lot-17',1,'']]],
  ['partout_53',['Le vocabulaire : « niveau » devient « carte », partout',['../lot-67.html#autotoc_md613',1,'']]],
  ['pas_54',['pas',['../classcore_1_1BattleGrid.html#autotoc_md1152',1,'Ce qu&apos;elle ne fait pas'],['../classhmi_1_1CharacterSheetModel.html#autotoc_md1232',1,'Ce qu&apos;elle ne refait pas'],['../namespacecore.html#autotoc_md1174',1,'Ce qu&apos;elle ne vérifie pas'],['../classhmi_1_1ArenaModel.html#autotoc_md1225',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1WorldModel.html#autotoc_md1249',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1GamepadNavigator.html#autotoc_md1237',1,'Ce qu&apos;il fait, et ce qu&apos;il ne fait pas'],['../classhmi_1_1ScreenRouter.html#autotoc_md1247',1,'Ce qu&apos;il n&apos;est pas'],['../structcore_1_1ExplorationSnapshot.html#autotoc_md1159',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../EnemyAi_8h.html#autotoc_md1162',1,'Ce que ce fichier décide, et que le Guide ne dit pas'],['../lot-15.html#autotoc_md419',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-18.html#autotoc_md431',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-19.html#autotoc_md442',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-20.html#autotoc_md455',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-21.html#autotoc_md468',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-22.html#autotoc_md477',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-23.html#autotoc_md487',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-50.html#autotoc_md586',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-87.html#autotoc_md665',1,'Ce que Claude ne produit pas'],['../lot-50.html#autotoc_md591',1,'Ce que l&apos;écran compose, et ce qu&apos;il ne compose pas'],['../Arena_8h.html#autotoc_md1144',1,'Ce que l&apos;arène est, et ce qu&apos;elle n&apos;est pas'],['../lot-18.html#autotoc_md433',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas'],['../lot-14.html#autotoc_md414',1,'Ce que le lot n&apos;invente pas'],['../lot-10.html#autotoc_md381',1,'Ce que le lot ne fait pas'],['../lot-12.html#autotoc_md400',1,'Ce que le lot ne fait pas'],['../lot-13.html#autotoc_md409',1,'Ce que le lot ne fait pas'],['../lot-14.html#autotoc_md416',1,'Ce que le lot ne fait pas'],['../lot-30.html#autotoc_md507',1,'Ce que le lot ne fait pas'],['../lot-32.html#autotoc_md514',1,'Ce que le lot ne fait pas'],['../lot-33.html#autotoc_md523',1,'Ce que le lot ne fait pas'],['../lot-34.html#autotoc_md533',1,'Ce que le lot ne fait pas'],['../lot-36.html#autotoc_md546',1,'Ce que le lot ne fait pas'],['../lot-38.html#autotoc_md567',1,'Ce que le lot ne fait pas'],['../lot-39.html#autotoc_md575',1,'Ce que le lot ne fait pas'],['../lot-43.html#autotoc_md583',1,'Ce que le lot ne fait pas'],['../lot-66.html#autotoc_md606',1,'Ce que le lot ne fait pas'],['../lot-67.html#autotoc_md614',1,'Ce que le lot ne fait pas'],['../lot-68.html#autotoc_md622',1,'Ce que le lot ne fait pas'],['../lot-76.html#autotoc_md630',1,'Ce que le lot ne fait pas'],['../lot-editor-10.html#autotoc_md1098',1,'Ce que le lot ne fait pas'],['../ArenaSceneComposer_8h.html#autotoc_md1212',1,'Ce qui n&apos;y est pas'],['../lot-12.html#autotoc_md396',1,'Deux arrondis qui ne se voient pas'],['../guide-ecs.html#autotoc_md81',1,'Exemple pas à pas'],['../guide-conception-qds.html#autotoc_md57',1,'Les ornements se tracent, ils ne se collent pas'],['../CombatPreview_8h.html#autotoc_md1153',1,'Une prévisualisation qui ne ment pas']]],
  ['pas_20«_20une_20seule_20hmilib_20»_55',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md321',1,'']]],
  ['pas_20à_20l_20estime_56',['L&apos;encart se lit par son cadre, pas à l&apos;estime',['../lot-37.html#autotoc_md551',1,'']]],
  ['pas_20à_20pas_57',['Exemple pas à pas',['../guide-ecs.html#autotoc_md81',1,'']]],
  ['pas_20écrit_20de_20classdefinition_20_3a_20elle_20existait_20déjà_58',['Le lot n&apos;a pas écrit de &lt;span class=&quot;tt&quot;&gt;ClassDefinition&lt;/span&gt; : elle existait déjà',['../lot-13.html#autotoc_md404',1,'']]],
  ['pas_20ce_20qui_20bloque_59',['Couches : ce qu&apos;on voit n&apos;est pas ce qui bloque',['../guide-niveaux.html#autotoc_md143',1,'']]],
  ['pas_20choisie_60',['La palette est relevée, pas choisie',['../lot-66.html#autotoc_md599',1,'']]],
  ['pas_20confondre_61',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md139',1,'']]],
  ['pas_20dans_20sa_20rangée_62',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md528',1,'']]],
  ['pas_20de_20l_20algorithme_63',['Le départage est une règle, et elle ne dépend pas de l&apos;algorithme',['../lot-19.html#autotoc_md444',1,'']]],
  ['pas_20de_20la_20prose_64',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md482',1,'']]],
  ['pas_20de_20simulation_20et_20les_20entrées_65',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md44',1,'']]],
  ['pas_20de_20temps_20fixe_66',['pas de temps fixe',['../guide-boucle.html',1,'Boucle de jeu et pas de temps fixe'],['../guide-boucle.html#autotoc_md39',1,'Le principe du pas de temps fixe']]],
  ['pas_20dire_67',['Ce que le schéma ne peut pas dire',['../lot-36.html#autotoc_md543',1,'']]],
  ['pas_20dire_20et_20qui_20n_20est_20pas_20perdu_20pour_20autant_68',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md520',1,'']]],
  ['pas_20directement_20dans_20l_20item_20qt_20quick_69',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md1214',1,'']]],
  ['pas_20dix_70',['Treize régions, pas dix',['../lot-37.html#autotoc_md550',1,'']]],
  ['pas_20encore_71',['Ce qu&apos;il ne fait pas encore',['../classhmi_1_1GameViewportItem.html#autotoc_md1240',1,'']]],
  ['pas_20encore_20alimentés_72',['Les écrans dessinés mais pas encore alimentés',['../guide-conception-qds.html#autotoc_md53',1,'']]],
  ['pas_20encore_20dans_20l_20éditeur_73',['Ce qui ne se fait pas encore dans l&apos;éditeur',['../guide-usage-editeur.html#autotoc_md1039',1,'']]],
  ['pas_20et_20pourquoi_74',['Ce que le lot ne fait pas, et pourquoi',['../lot-37.html#autotoc_md555',1,'']]],
  ['pas_20faire_20seule_75',['Ce que la conception ne peut pas faire seule',['../spec-interface-ihm.html#autotoc_md271',1,'']]],
  ['pas_20la_20fiche_20il_20la_20désigne_76',['Le composant ECS ne porte pas la fiche, il la désigne',['../lot-13.html#autotoc_md407',1,'']]],
  ['pas_20la_20génération_77',['Le test lit le livre, pas la génération',['../lot-33.html#autotoc_md522',1,'']]],
  ['pas_20la_20matière_78',['Ce que le corpus donne encore : la mesure, pas la matière',['../lot-76.html#autotoc_md626',1,'']]],
  ['pas_20liste_20de_20production_79',['pas liste de production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md799',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md817',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md824',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md830',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md842',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md848',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md854',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md860',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md866',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md872',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md878',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md885',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md891',1,'PNJ — localisateurs, pas liste de production']]],
  ['pas_20livré_80',['Ce que le lot a livré, et ce qu&apos;il n&apos;a pas livré',['../lot-09.html#autotoc_md369',1,'']]],
  ['pas_20par_20qstr_81',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1246',1,'']]],
  ['pas_20perdu_20pour_20autant_82',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md520',1,'']]],
  ['pas_20plus_20tard_83',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md333',1,'']]],
  ['pas_20produire_84',['Ce que le cahier ne fait pas produire',['../lot-87-cahier-assets.html#lot-87-cahier-exclusions',1,'']]],
  ['pas_20réécrire_85',['Ce qui existe déjà, et qu&apos;il ne faut pas réécrire',['../lot-06.html#autotoc_md347',1,'']]],
  ['pas_20rater_86',['Le point à ne pas rater',['../lot-04.html#autotoc_md335',1,'']]],
  ['pas_20s_20arrêter_87',['Traverser n&apos;est pas s&apos;arrêter',['../lot-19.html#autotoc_md447',1,'']]],
  ['pas_20saisi_88',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md505',1,'']]],
  ['pas_20se_20cacher_89',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md1239',1,'']]],
  ['pas_20seulement_20l_20état_90',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md102',1,'']]],
  ['pas_20subi_91',['Le renversement est assumé, pas subi',['../lot-66.html#autotoc_md605',1,'']]],
  ['pas_20sur_20des_20expressions_20régulières_92',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md518',1,'']]],
  ['pas_20sur_20l_20intention_93',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md405',1,'']]],
  ['pas_20tenu_94',['Ce que la feuille de route supposait, et qui n&apos;a pas tenu',['../lot-19.html#autotoc_md443',1,'']]],
  ['pas_20un_20booléen_95',['Un ennemi vaincu est un drapeau de monde, pas un booléen',['../lot-18.html#autotoc_md434',1,'']]],
  ['pas_20un_20changement_20de_20cible_96',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md151',1,'']]],
  ['pas_20un_20hasard_97',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md1172',1,'']]],
  ['pas_20un_20indice_98',['pas un indice',['../lot-20.html#autotoc_md458',1,'Le tour : une place, pas un indice'],['../classcore_1_1TurnOrder.html#autotoc_md1176',1,'Une place, pas un indice']]],
  ['pas_20un_20journal_20c_20est_20une_20exigence_99',['La restitution n&apos;est pas un journal, c&apos;est une exigence',['../lot-12.html#autotoc_md398',1,'']]],
  ['pas_20un_20oubli_100',['L&apos;accentué reste tracé à l&apos;ancienne, et ce n&apos;est pas un oubli',['../lot-76.html#autotoc_md628',1,'']]],
  ['pas_20un_20parcours_20en_20largeur_101',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1171',1,'']]],
  ['pas_20un_20produit_102',['L&apos;éditeur : un outil, pas un produit',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['pas_20un_20total_20de_2020_103',['Un 20 naturel n&apos;est pas un total de 20',['../lot-12.html#autotoc_md397',1,'']]],
  ['pas_20une_20refonte_104',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md1001',1,'']]],
  ['pas_20une_20soustraction_105',['pas une soustraction',['../Damage_8h.html#autotoc_md1160',1,'Pourquoi un pipeline, et pas une soustraction'],['../lot-21.html#autotoc_md471',1,'Un pipeline, pas une soustraction']]],
  ['pas_20versionné_106',['1. Le corpus n&apos;est pas versionné',['../roadmap.html#autotoc_md915',1,'']]],
  ['pas_20vu_107',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md395',1,'']]],
  ['passé_20le_2012_20septembre_202026_108',['T1.5 — Le test de l&apos;artiste, passé le 12 septembre 2026',['../lot-87.html#autotoc_md670',1,'']]],
  ['passe_20la_20frontière_109',['Où passe la frontière',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1231',1,'']]],
  ['passent_20pas_20par_20qstr_110',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1246',1,'']]],
  ['patch_111',['Cadres 9-patch',['../lot-87-cahier-assets.html#lot-87-cahier-frame',1,'']]],
  ['pause_112',['Pause',['../guide-ecrans.html#autotoc_md72',1,'Pause'],['../manuel-jouer.html#autotoc_md1125',1,'Pause']]],
  ['pause_20dialogue_20marchand_20journal_20_3a_20restylés_113',['T3.9 — Pause, dialogue, marchand, journal : restylés',['../lot-87.html#autotoc_md695',1,'']]],
  ['peindre_20avec_20les_20pièces_20du_20lieu_114',['Peindre avec les pièces du lieu',['../lot-editor-03.html',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu'],['../roadmap-editeur.html#autotoc_md1015',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu']]],
  ['peindre_20avec_20les_20pièces_20du_20lieu_20lot_20editor_2003_115',['11. Peindre avec les pièces du lieu (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-03&lt;/span&gt;)',['../spec-editeur.html#autotoc_md233',1,'']]],
  ['peindre_20c_20est_20convertir_20un_20pixel_20en_20case_116',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md88',1,'']]],
  ['peindre_20par_20lot_20sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_117',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md91',1,'']]],
  ['peintre_118',['peintre',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1229',1,'Ce que fait le peintre'],['../lot-editor-04.html',1,'LOT-EDITOR-04 — Les outils du peintre'],['../roadmap-editeur.html#autotoc_md1016',1,'LOT-EDITOR-04 — Les outils du peintre']]],
  ['peintre_20lot_20editor_2004_119',['12. Les outils du peintre (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-04&lt;/span&gt;)',['../spec-editeur.html#autotoc_md234',1,'']]],
  ['peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_120',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md91',1,'']]],
  ['perdent_20leur_20porteur_121',['Exigences qui perdent leur porteur',['../lot-88.html#autotoc_md713',1,'']]],
  ['perdu_20de_20vue_122',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md604',1,'']]],
  ['perdu_20pour_20autant_123',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md520',1,'']]],
  ['performance_124',['1. Performance',['../spec-exigences.html#autotoc_md244',1,'']]],
  ['performance_20à_20respecter_125',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md125',1,'']]],
  ['personnage_126',['personnage',['../spec-rpg.html#autotoc_md298',1,'5. Options de personnage'],['../lot-13.html',1,'LOT-13 — Fiche de personnage']]],
  ['personnage_20_3a_20dons_20multiclassage_20compétences_20langues_127',['LOT-43 — Options de personnage : dons, multiclassage, compétences, langues',['../lot-43.html',1,'lots']]],
  ['personnage_20_3a_20maquette_20et_20interface_128',['LOT-38 — Fiche de personnage : maquette et interface',['../lot-38.html',1,'lots']]],
  ['personnage_20affiché_20_3a_20une_20donnée_20et_20un_20échafaudage_20assumé_129',['Le personnage affiché : une donnée, et un échafaudage assumé',['../lot-38.html#autotoc_md565',1,'']]],
  ['personnage_20de_20démonstration_130',['Le personnage de démonstration',['../lot-18.html#autotoc_md439',1,'']]],
  ['personnage_20et_20progression_131',['Personnage et progression',['../spec-rpg.html',1,'specifications']]],
  ['personnage_20maquette_2003_132',['T3.4 — La fiche de personnage (maquette 03)',['../lot-87.html#autotoc_md690',1,'']]],
  ['personnages_133',['LOT-29 — Groupe de quatre personnages',['../roadmap.html#lot-29',1,'']]],
  ['personne_20n_20y_20meurt_20et_20c_20est_20la_20fiction_20qui_20l_20explique_134',['Personne n&apos;y meurt, et c&apos;est la fiction qui l&apos;explique',['../lot-50.html#autotoc_md589',1,'']]],
  ['perte_20de_20travail_135',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md95',1,'']]],
  ['peuplement_20_3a_20rencontres_20et_20créatures_136',['&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt; — Peuplement : rencontres et créatures',['../roadmap.html#lot-41',1,'']]],
  ['peuplement_20civil_20_3a_20pnj_20marchands_20et_20quêtes_137',['&lt;span class=&quot;tt&quot;&gt;LOT-82&lt;/span&gt; — Peuplement civil : PNJ, marchands et quêtes',['../roadmap.html#lot-82',1,'']]],
  ['peut_20défaire_138',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html&quot; title=&quot;core::LevelDraft&quot;&gt;core::LevelDraft&lt;/a&gt; : une carte qu&apos;on peut défaire',['../guide-editeur.html#autotoc_md86',1,'']]],
  ['peut_20on_20se_20tenir_20ici_20»_139',['peut on se tenir ici »',['../lot-19.html#autotoc_md450',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1150',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['peut_20pas_20dire_140',['Ce que le schéma ne peut pas dire',['../lot-36.html#autotoc_md543',1,'']]],
  ['peut_20pas_20dire_20et_20qui_20n_20est_20pas_20perdu_20pour_20autant_141',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md520',1,'']]],
  ['peut_20pas_20faire_20seule_142',['Ce que la conception ne peut pas faire seule',['../spec-interface-ihm.html#autotoc_md271',1,'']]],
  ['phase_200_143',['Critères d&apos;acceptation de la phase 0',['../lot-87.html#autotoc_md704',1,'']]],
  ['phase_201_144',['Où en est la phase 1',['../lot-87.html#autotoc_md671',1,'']]],
  ['phase_201_20—_20le_20module_20de_20conception_145',['Phase 1 — le module de conception',['../lot-87.html#autotoc_md667',1,'']]],
  ['phase_202_20—_20charte_20v2_20et_20matière_20première_146',['Phase 2 — charte v2 et matière première',['../lot-87.html#autotoc_md672',1,'']]],
  ['phase_202_20—_20vérifié_20le_2013_20septembre_202026_147',['Où en est la phase 2 — vérifié le 13 septembre 2026',['../lot-87.html#autotoc_md685',1,'']]],
  ['phase_203_148',['Où en est la phase 3',['../lot-87.html#autotoc_md696',1,'']]],
  ['phase_203_20—_20les_20écrans_149',['Phase 3 — les écrans',['../lot-87.html#autotoc_md686',1,'']]],
  ['phase_204_20—_20le_20cadre_20du_20hud_150',['Phase 4 — le cadre du HUD',['../lot-87.html#autotoc_md697',1,'']]],
  ['phase_205_20—_20retirer_20ce_20qui_20ne_20sert_20plus_151',['Phase 5 — retirer ce qui ne sert plus',['../lot-87.html#autotoc_md699',1,'']]],
  ['phases_152',['phases',['../lot-96.html#autotoc_md774',1,'Les phases'],['../lot-09.html#autotoc_md368',1,'Les six phases'],['../lot-87.html#autotoc_md666',1,'Programme, en six phases']]],
  ['phrase_153',['En une phrase',['../guide-conception-qds.html#autotoc_md47',1,'']]],
  ['pièce_20format_20v4_20lot_20editor_2012_20ex_20lvl_20019_154',['Une case = un type et une pièce (format v4, &lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-LVL-019&lt;/span&gt;)',['../structcore_1_1TileLayer.html#autotoc_md1181',1,'']]],
  ['pièces_20du_20lieu_155',['pièces du lieu',['../lot-editor-03.html',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu'],['../roadmap-editeur.html#autotoc_md1015',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu']]],
  ['pièces_20du_20lieu_20lot_20editor_2003_156',['11. Peindre avec les pièces du lieu (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-03&lt;/span&gt;)',['../spec-editeur.html#autotoc_md233',1,'']]],
  ['piège_20classique_157',['Le piège classique',['../lot-06.html#autotoc_md349',1,'']]],
  ['piège_20du_20framerate_20variable_158',['Le piège du framerate variable',['../guide-boucle.html#autotoc_md38',1,'']]],
  ['piège_20du_20lot_20_3a_20un_20coffre_20ouvert_20deux_20fois_159',['Le piège du lot : un coffre ouvert deux fois',['../lot-10.html#autotoc_md377',1,'']]],
  ['piège_20du_20tirage_160',['Le piège du tirage',['../roadmap.html#autotoc_md978',1,'']]],
  ['piège_20et_20la_20façon_20dont_20il_20est_20écarté_161',['Le piège, et la façon dont il est écarté',['../lot-14.html#autotoc_md412',1,'']]],
  ['picturaux_20ex_20dec_162',['Décors et plans picturaux (&lt;span class=&quot;tt&quot;&gt;EX-DEC-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md252',1,'']]],
  ['pied_163',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md1194',1,'']]],
  ['pied_20lot_2007_164',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md167',1,'']]],
  ['pile_20d_20écrans_165',['Le routeur et la pile d&apos;écrans',['../guide-ecrans.html#autotoc_md70',1,'']]],
  ['pilotage_166',['Le pilotage',['../ArenaAnimationDriver_8h.html#autotoc_md1208',1,'']]],
  ['pilote_167',['1. Les cinq PNJ du pilote',['../lot-91-poc.html#autotoc_md728',1,'']]],
  ['pipeline_20de_20dessin_20de_20sprites_20_3a_20hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_168',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['pipeline_20et_20pas_20une_20soustraction_169',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md1160',1,'']]],
  ['pipeline_20pas_20une_20soustraction_170',['Un pipeline, pas une soustraction',['../lot-21.html#autotoc_md471',1,'']]],
  ['piste_20du_20repaire_171',['CE-01 — Martpart, Myr et la piste du repaire',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html',1,'']]],
  ['piste_20ouverte_20puis_20refermée_172',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md560',1,'']]],
  ['pistes_20écartées_173',['8. Risques et pistes écartées',['../roadmap-editeur.html#roadmap-editeur-risques',1,'']]],
  ['pixel_174',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md664',1,'']]],
  ['pixel_20art_175',['pixel art',['../lot-66.html',1,'LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art'],['../guide-design-ihm.html#autotoc_md67',1,'Pourquoi le facteur reste entier après la sortie du pixel art'],['../lot-92.html#autotoc_md744',1,'Risque : l&apos;angle 0,62 en pixel art']]],
  ['pixel_20en_20case_176',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md88',1,'']]],
  ['pixels_20_3a_20hmi_3a_3acamera2d_20hmi_3a_3acamera2d_177',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md153',1,'']]],
  ['place_178',['Ce que l&apos;agonie trouvera en place',['../lot-21.html#autotoc_md472',1,'']]],
  ['place_20pas_20un_20indice_179',['place pas un indice',['../lot-20.html#autotoc_md458',1,'Le tour : une place, pas un indice'],['../classcore_1_1TurnOrder.html#autotoc_md1176',1,'Une place, pas un indice']]],
  ['placement_20d_20entités_180',['LOT-11 — Éditeur multi-couches et placement d&apos;entités',['../lot-11.html',1,'']]],
  ['placer_20l_20entrée_181',['4. Placer l&apos;entrée',['../guide-usage-editeur.html#autotoc_md1031',1,'']]],
  ['plan_182',['Les cartes — quatre, tracées depuis le plan',['../roadmap.html#autotoc_md983',1,'']]],
  ['plan_20d_20intégration_20_3a_20la_20capitale_20lot_20après_20lot_183',['Le plan d&apos;intégration : la Capitale, lot après lot',['../roadmap.html#roadmap-capitale',1,'']]],
  ['plan_20du_20guide_184',['Plan du guide',['../guide.html#autotoc_md174',1,'']]],
  ['plan_20pénombral_185',['&lt;span class=&quot;tt&quot;&gt;LOT-90&lt;/span&gt; — Le plan pénombral',['../roadmap.html#lot-90',1,'']]],
  ['planche_186',['Renommer, remplacer, changer de planche',['../guide-usage-editeur.html#autotoc_md1037',1,'']]],
  ['planche_20chacun_187',['Les textures — trois jeux, une planche chacun',['../roadmap.html#autotoc_md985',1,'']]],
  ['planche_20gravée_20_3a_20une_20piste_20ouverte_20puis_20refermée_188',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md560',1,'']]],
  ['planche_20par_20lieu_189',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['planche_20retenue_190',['9. La découpe d&apos;une planche retenue',['../lot-91-poc.html#autotoc_md736',1,'']]],
  ['planches_20à_20la_20main_191',['LOT-91 — Preuve de concept : cinq planches à la main',['../lot-91-poc.html',1,'lot-91']]],
  ['planches_20et_20ce_20qu_20on_20relève_20dessus_192',['La maquette : cinq planches, et ce qu&apos;on relève dessus',['../lot-38.html#autotoc_md558',1,'']]],
  ['plans_20picturaux_20ex_20dec_193',['Décors et plans picturaux (&lt;span class=&quot;tt&quot;&gt;EX-DEC-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md252',1,'']]],
  ['plaques_20et_20bandeaux_194',['Plaques et bandeaux',['../lot-87-cahier-assets.html#lot-87-cahier-plate',1,'']]],
  ['plates_195',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : l&apos;atlas des couleurs plates',['../guide-rendu.html#autotoc_md161',1,'']]],
  ['platform_205_196',['Platform (5)',['../cahiertest.html#autotoc_md25',1,'']]],
  ['plausibilité_197',['6. Contrôle de plausibilité',['../spec-contenu.html#autotoc_md196',1,'']]],
  ['player_20s_20guide_20dessine_20ses_20titres_20deux_20fois_198',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md541',1,'']]],
  ['plomberie_20des_20clés_20d_20assets_199',['LOT-39 — Plomberie des clés d&apos;assets',['../lot-39.html',1,'lots']]],
  ['plus_200',['plus',['../guide-audio.html#autotoc_md32',1,'La règle d&apos;or, une fois de plus'],['../lot-87.html#autotoc_md699',1,'Phase 5 — retirer ce qui ne sert plus']]],
  ['plus_20facile_20d_20implémenter_20de_20travers_201',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md581',1,'']]],
  ['plus_20fort_20levier_20du_20programme_202',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md951',1,'']]],
  ['plus_20grande_20que_20la_20fenêtre_203',['Cadrer une carte plus grande que la fenêtre',['../guide-editeur.html#autotoc_md96',1,'']]],
  ['plus_20large_20qu_20estimé_204',['9.5 La collision de numéros est bloquante, et bien plus large qu&apos;estimé',['../roadmap.html#autotoc_md953',1,'']]],
  ['plus_20que_20le_20rpg_205',['2. Le modèle de carte ne porte plus que le RPG',['../lot-88.html#autotoc_md709',1,'']]],
  ['plus_20tard_206',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md333',1,'']]],
  ['plus_20une_20cible_207',['Un coffre vidé n&apos;est plus une cible',['../lot-10.html#autotoc_md378',1,'']]],
  ['plusieurs_20cartes_20à_20la_20fois_20et_20le_20monde_20autour_20lot_20editor_2009_208',['Plusieurs cartes à la fois, et le monde autour (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-09&lt;/span&gt;)',['../guide-usage-editeur.html#autotoc_md1038',1,'']]],
  ['plutôt_20qu_20une_20image_20manquante_209',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md1182',1,'']]],
  ['plutôt_20que_20contournées_210',['Trois irrégularités de la source, nommées plutôt que contournées',['../lot-37.html#autotoc_md554',1,'']]],
  ['plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_211',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md156',1,'']]],
  ['plutôt_20que_20fonctions_20libres_212',['Classes plutôt que fonctions libres',['../spec-conventions.html#autotoc_md211',1,'']]],
  ['plutôt_20que_20la_20table_20brute_213',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1233',1,'']]],
  ['plutôt_20que_20réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_214',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md101',1,'']]],
  ['pnj_215',['PNJ',['../lot-91-poc.html#lot-91-methode',1,'4bis. La méthode standard, pour un PNJ'],['../md_Lot_2LOT-CREATION-ASSETS_2epic.html#autotoc_md782',1,'Contrat de qualité PNJ'],['../lot-91.html#autotoc_md721',1,'La méthode, pour un PNJ'],['../lot-91.html#autotoc_md724',1,'Les PNJ']]],
  ['pnj_20—_20localisateurs_20pas_20liste_20de_20production_216',['PNJ — localisateurs pas liste de production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md799',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md817',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md824',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md830',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md842',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md848',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md854',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md860',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md866',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md872',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md878',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md885',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md891',1,'PNJ — localisateurs, pas liste de production']]],
  ['pnj_20_3a_20les_20figurines_20du_20character_20compendium_217',['LOT-91 — Atelier des PNJ : les figurines du Character Compendium',['../lot-91.html',1,'lots']]],
  ['pnj_20du_20pilote_218',['1. Les cinq PNJ du pilote',['../lot-91-poc.html#autotoc_md728',1,'']]],
  ['pnj_20du_20poc_219',['T00 — Socle et reprise des cinq PNJ du PoC',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html',1,'']]],
  ['pnj_20et_20dialogues_220',['LOT-15 — PNJ et dialogues',['../lot-15.html',1,'lots']]],
  ['pnj_20marchands_20et_20quêtes_221',['&lt;span class=&quot;tt&quot;&gt;LOT-82&lt;/span&gt; — Peuplement civil : PNJ, marchands et quêtes',['../roadmap.html#lot-82',1,'']]],
  ['poc_222',['T00 — Socle et reprise des cinq PNJ du PoC',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html',1,'']]],
  ['point_223',['Déterministe, et c&apos;est le point',['../namespacecore.html#autotoc_md1183',1,'']]],
  ['point_20à_20ne_20pas_20rater_224',['Le point à ne pas rater',['../lot-04.html#autotoc_md335',1,'']]],
  ['point_20délicat_225',['Le point délicat',['../roadmap.html#autotoc_md1003',1,'']]],
  ['point_20ou_20une_20direction_20dans_20le_20monde_226',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md131',1,'']]],
  ['points_20de_20contact_20avec_20le_20jeu_227',['7. Points de contact avec le jeu',['../roadmap-editeur.html#roadmap-editeur-contacts',1,'']]],
  ['points_20de_20vigilance_228',['Points de vigilance',['../lot-02.html#autotoc_md323',1,'']]],
  ['points_20ouverts_229',['Points ouverts',['../lot-96.html#autotoc_md776',1,'']]],
  ['points_20que_20la_20grille_20laissait_20ouverts_230',['Les trois points que la grille laissait ouverts',['../lot-20.html#autotoc_md456',1,'']]],
  ['pop_231',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md80',1,'']]],
  ['portée_232',['Les mémoires à portée',['../lot-20.html#autotoc_md462',1,'']]],
  ['portée_20ligne_20de_20vue_20et_20zones_20d_20effet_233',['LOT-22 — Portée, ligne de vue et zones d&apos;effet',['../lot-22.html',1,'lots']]],
  ['portée_20par_20l_20écran_20et_20non_20par_20l_20appelant_234',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md619',1,'']]],
  ['portabilité_20reproductibilité_235',['4. Portabilité &amp;amp; reproductibilité',['../spec-exigences.html#autotoc_md247',1,'']]],
  ['portails_20ville_236',['portails ville',['../lot-editor-09.html',1,'LOT-EDITOR-09 — Le monde : onglets, portails, ville'],['../roadmap-editeur.html#autotoc_md1023',1,'LOT-EDITOR-09 — Le monde : onglets, portails, ville']]],
  ['portails_20ville_20lot_20editor_2009_237',['19. Le monde : onglets, portails, ville (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-09&lt;/span&gt;)',['../spec-editeur.html#autotoc_md241',1,'']]],
  ['porte_20aucun_20texte_238',['Le graphe ne porte aucun texte',['../lot-15.html#autotoc_md420',1,'']]],
  ['porte_20et_20ce_20qu_20il_20ne_20porte_20pas_239',['porte et ce qu il ne porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md1159',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../lot-18.html#autotoc_md433',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas']]],
  ['porte_20le_20lot_240',['La décision qui porte le lot',['../lot-03.html#autotoc_md329',1,'']]],
  ['porte_20pas_241',['porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md1159',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../lot-18.html#autotoc_md433',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas']]],
  ['porte_20pas_20la_20fiche_20il_20la_20désigne_242',['Le composant ECS ne porte pas la fiche, il la désigne',['../lot-13.html#autotoc_md407',1,'']]],
  ['porte_20plus_20que_20le_20rpg_243',['2. Le modèle de carte ne porte plus que le RPG',['../lot-88.html#autotoc_md709',1,'']]],
  ['portent_20le_20soldat_244',['Les sentinelles portent le soldat',['../lot-93.html#autotoc_md755',1,'']]],
  ['porter_245',['1. Porter',['../spec-inventaire.html#autotoc_md273',1,'']]],
  ['porteur_246',['Exigences qui perdent leur porteur',['../lot-88.html#autotoc_md713',1,'']]],
  ['pose_20écrit_247',['Ce que la pose écrit',['../Stamps_8h.html#autotoc_md1204',1,'']]],
  ['pose_20sous_20la_20valeur_20jamais_20dessus_248',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md545',1,'']]],
  ['poser_20le_20sol_249',['2. Poser le sol',['../guide-usage-editeur.html#autotoc_md1029',1,'']]],
  ['poser_20les_20entités_250',['5. Poser les entités',['../guide-usage-editeur.html#autotoc_md1032',1,'']]],
  ['poste_251',['0. Le poste',['../lot-91-poc.html#autotoc_md727',1,'']]],
  ['pour_20«_20peut_20on_20se_20tenir_20ici_20»_252',['pour « peut on se tenir ici »',['../lot-19.html#autotoc_md450',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1150',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['pour_20«_20se_20tenir_20ici_20»_253',['Une seule règle pour « se tenir ici »',['../namespacecore.html#autotoc_md1173',1,'']]],
  ['pour_20autant_254',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md520',1,'']]],
  ['pour_20douze_20refondues_20pour_20trois_255',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md612',1,'']]],
  ['pour_20durer_256',['5. Cinq règles pour durer',['../roadmap-editeur.html#roadmap-editeur-perennite',1,'']]],
  ['pour_20l_20éditeur_257',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md210',1,'']]],
  ['pour_20le_20jeu_20en_20code_20pour_20l_20éditeur_258',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md210',1,'']]],
  ['pour_20les_20dessiner_259',['Ouvrir les écrans pour les dessiner',['../guide-ihm-qt.html#autotoc_md113',1,'']]],
  ['pour_20tout_20le_20code_20de_20simulation_260',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md45',1,'']]],
  ['pour_20trois_261',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md612',1,'']]],
  ['pour_20un_20pnj_262',['pour un PNJ',['../lot-91-poc.html#lot-91-methode',1,'4bis. La méthode standard, pour un PNJ'],['../lot-91.html#autotoc_md721',1,'La méthode, pour un PNJ']]],
  ['pour_20une_20autre_20raison_263',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md602',1,'']]],
  ['pour_20une_20créature_264',['La méthode, pour une créature',['../lot-93.html#autotoc_md752',1,'']]],
  ['pourquoi_265',['pourquoi',['../lot-09.html#autotoc_md371',1,'Écarté, et pourquoi'],['../lot-37.html#autotoc_md555',1,'Ce que le lot ne fait pas, et pourquoi'],['../lot-18.html#autotoc_md438',1,'Ce que le mode combat gèle, et pourquoi'],['../spec-interface-ihm.html#autotoc_md267',1,'Ce qui a changé, et pourquoi'],['../lot-87.html#autotoc_md676',1,'Ce qui est écarté, et pourquoi'],['../lot-86.html#autotoc_md650',1,'Les deux directions écartées, et pourquoi']]],
  ['pourquoi_20«_20batcher_20»_20plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_266',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md156',1,'']]],
  ['pourquoi_20c_20est_20celle_20du_20jeu_267',['La règle, et pourquoi c&apos;est celle du jeu',['../ExplorationReach_8h.html#autotoc_md1189',1,'']]],
  ['pourquoi_20ce_20lot_20est_20un_20lot_20d_20ajout_20pas_20une_20refonte_268',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md1001',1,'']]],
  ['pourquoi_20ceux_20là_20ne_20passent_20pas_20par_20qstr_269',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1246',1,'']]],
  ['pourquoi_20chaque_20arête_20n_20est_20contrôlée_20qu_20une_20fois_270',['Le triangle, et pourquoi chaque arête n&apos;est contrôlée qu&apos;une fois',['../lot-32.html#autotoc_md511',1,'']]],
  ['pourquoi_20des_20instantanés_20complets_271',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md92',1,'']]],
  ['pourquoi_20des_20propriétés_20nommées_20plutôt_20que_20la_20table_20brute_272',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1233',1,'']]],
  ['pourquoi_20deux_20binaires_273',['Pourquoi deux binaires',['../guide-ihm-qt.html#autotoc_md109',1,'']]],
  ['pourquoi_20elle_20n_20est_20pas_20un_20parcours_20en_20largeur_274',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1171',1,'']]],
  ['pourquoi_20il_20est_20déterministe_275',['Le marqueur, et pourquoi il est déterministe',['../lot-39.html#autotoc_md573',1,'']]],
  ['pourquoi_20il_20fallait_20l_20écrire_276',['Pourquoi il fallait l&apos;écrire',['../classhmi_1_1GamepadNavigator.html#autotoc_md1236',1,'']]],
  ['pourquoi_20il_20n_20est_20pas_20«_20une_20seule_20hmilib_20»_277',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md321',1,'']]],
  ['pourquoi_20il_20s_20auto_20teste_278',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md506',1,'']]],
  ['pourquoi_20il_20valait_20mieux_279',['Le renversement du milieu du lot, et pourquoi il valait mieux',['../lot-76.html#autotoc_md625',1,'']]],
  ['pourquoi_20journaliser_20dans_20un_20jeu_20vidéo_280',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md119',1,'']]],
  ['pourquoi_20l_20égalité_20stricte_20est_20dangereuse_281',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md136',1,'']]],
  ['pourquoi_20le_20facteur_20reste_20entier_20après_20la_20sortie_20du_20pixel_20art_282',['Pourquoi le facteur reste entier après la sortie du pixel art',['../guide-design-ihm.html#autotoc_md67',1,'']]],
  ['pourquoi_20les_20maquettes_20remplacent_20la_20charte_20parchemin_20pixel_283',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md664',1,'']]],
  ['pourquoi_20maintenant_20et_20pas_20plus_20tard_284',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md333',1,'']]],
  ['pourquoi_20pas_20directement_20dans_20l_20item_20qt_20quick_285',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md1214',1,'']]],
  ['pourquoi_20purger_20en_20premier_286',['Pourquoi purger en premier',['../lot-01.html#autotoc_md310',1,'']]],
  ['pourquoi_20un_20item_20à_20part_287',['Pourquoi un item à part',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1227',1,'']]],
  ['pourquoi_20un_20marqueur_20plutôt_20qu_20une_20image_20manquante_288',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md1182',1,'']]],
  ['pourquoi_20un_20pipeline_20et_20pas_20une_20soustraction_289',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md1160',1,'']]],
  ['pourquoi_20un_20tiret_20cadratin_20et_20non_20de_20fausses_20données_290',['Pourquoi un tiret cadratin et non de fausses données',['../classhmi_1_1PendingData.html#autotoc_md1244',1,'']]],
  ['pourquoi_20une_20énumération_20et_20non_20un_20nom_20de_20fichier_291',['Pourquoi une énumération et non un nom de fichier',['../classhmi_1_1ScreenRouter.html#autotoc_md1248',1,'']]],
  ['pourquoi_20une_20liste_292',['Pourquoi une liste',['../classcore_1_1ActionEconomy.html#autotoc_md1137',1,'']]],
  ['pourquoi_20une_20session_20à_20part_293',['Pourquoi une session à part',['../ExplorationSession_8h.html#autotoc_md1190',1,'']]],
  ['pourquoi_20une_20table_20de_20chaînes_20et_20non_20une_20structure_20de_20champs_294',['Pourquoi une table de chaînes, et non une structure de champs',['../structhmi_1_1CharacterSheetContext.html#autotoc_md1222',1,'']]],
  ['pourquoi_20une_20zone_20et_20non_20la_20carte_20entière_295',['Pourquoi une zone, et non la carte entière',['../CombatZone_8h.html#autotoc_md1188',1,'']]],
  ['pouvez_20importer_296',['Les modules que vous pouvez importer',['../guide-conception-qds.html#autotoc_md56',1,'']]],
  ['pouvoirs_20et_20menaces_20documentés_297',['pouvoirs et menaces documentés',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md791',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md797',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md804',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md810',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md816',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md822',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md829',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md835',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md841',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md847',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md853',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md859',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md865',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md871',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md877',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md883',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md890',1,'Lieux, cultures, pouvoirs et menaces documentés']]],
  ['pouvoirs_20factions_20et_20organisations_298',['Pouvoirs, factions et organisations',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md787',1,'']]],
  ['préalable_20tranchée_299',['La décision préalable, tranchée',['../lot-11.html#autotoc_md384',1,'']]],
  ['préconditions_20manquent_300',['9.4 Le socle technique tient, mais trois préconditions manquent',['../roadmap.html#autotoc_md952',1,'']]],
  ['préfabriqués_301',['préfabriqués',['../lot-editor-08.html',1,'LOT-EDITOR-08 — Tampons et préfabriqués'],['../roadmap-editeur.html#autotoc_md1022',1,'LOT-EDITOR-08 — Tampons et préfabriqués'],['../guide-usage-editeur.html#autotoc_md1036',1,'Répéter ce qu&apos;on a composé : tampons et préfabriqués']]],
  ['préfabriqués_20lot_20editor_2008_302',['18. Tampons et préfabriqués (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-08&lt;/span&gt;)',['../spec-editeur.html#autotoc_md240',1,'']]],
  ['préparation_303',['préparation',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md795',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md802',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md808',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md814',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md820',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md827',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md833',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md839',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md845',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md851',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md857',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md863',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md869',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md875',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md881',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md888',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md894',1,'Limites de la préparation']]],
  ['préparation_20production_20et_20acceptation_304',['Préparation production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html#autotoc_md903',1,'Préparation, production et acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-02-arenarea-galender.html#autotoc_md905',1,'Préparation, production et acceptation']]],
  ['préparation_20régionale_305',['Références communes et préparation régionale',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html',1,'']]],
  ['prérequis_306',['Prérequis',['../manuel-telecharger.html#autotoc_md1134',1,'']]],
  ['prévenir_20et_20comment_307',['Les deux défauts à prévenir, et comment',['../lot-23.html#autotoc_md490',1,'']]],
  ['prévisualisation_20qui_20ne_20ment_20pas_308',['Une prévisualisation qui ne ment pas',['../CombatPreview_8h.html#autotoc_md1153',1,'']]],
  ['prévue_309',['Intégration technique prévue',['../md_Lot_2LOT-CREATION-ASSETS_2tache-01-carte-test-textures.html#autotoc_md901',1,'']]],
  ['pratique_20pour_20tout_20le_20code_20de_20simulation_310',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md45',1,'']]],
  ['pratiques_311',['7. Bonnes pratiques',['../spec-conventions.html#autotoc_md216',1,'']]],
  ['première_312',['Phase 2 — charte v2 et matière première',['../lot-87.html#autotoc_md672',1,'']]],
  ['première_20carte_313',['LOT-09 — Le Colisée se parcourt : exploration dans le jeu et première carte',['../lot-09.html',1,'lots']]],
  ['première_20série_20proposée_20—_20central_20empire_314',['Première série proposée — Central Empire',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md793',1,'']]],
  ['première_20série_20proposée_20—_20darkall_315',['Première série proposée — Darkall',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md800',1,'']]],
  ['première_20série_20proposée_20—_20imperial_20ben’net_316',['Première série proposée — Imperial Ben’net',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md806',1,'']]],
  ['première_20série_20proposée_20—_20kingdom_20of_20kolbjörn_317',['Première série proposée — Kingdom of Kolbjörn',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md812',1,'']]],
  ['première_20série_20proposée_20—_20magocracy_20of_20mage_20tower_318',['Première série proposée — Magocracy of Mage Tower',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md818',1,'']]],
  ['première_20série_20proposée_20—_20mystical_20wasteland_319',['Première série proposée — Mystical / Wasteland',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md825',1,'']]],
  ['première_20série_20proposée_20—_20pénombre_320',['Première série proposée — Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md831',1,'']]],
  ['première_20série_20proposée_20—_20republic_20of_20freelands_321',['Première série proposée — Republic of Freelands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md837',1,'']]],
  ['première_20série_20proposée_20—_20seashores_322',['Première série proposée — Seashores',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md843',1,'']]],
  ['première_20série_20proposée_20—_20sindile_20forest_323',['Première série proposée — Sindile Forest',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md849',1,'']]],
  ['première_20série_20proposée_20—_20storm_20islands_324',['Première série proposée — Storm Islands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md855',1,'']]],
  ['première_20série_20proposée_20—_20stravian_20domains_325',['Première série proposée — Stravian Domains',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md861',1,'']]],
  ['première_20série_20proposée_20—_20taii’maku_326',['Première série proposée — Taii’Maku',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md867',1,'']]],
  ['première_20série_20proposée_20—_20theocracy_20of_20kepesh_327',['Première série proposée — Theocracy of Kepesh',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md873',1,'']]],
  ['première_20série_20proposée_20—_20tsvetan_328',['Première série proposée — Tsvetan',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md879',1,'']]],
  ['première_20série_20proposée_20—_20undertanares_329',['Première série proposée — Undertanares',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md886',1,'']]],
  ['première_20série_20proposée_20—_20yama_330',['Première série proposée — Yama',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md892',1,'']]],
  ['premier_331',['Pourquoi purger en premier',['../lot-01.html#autotoc_md310',1,'']]],
  ['premier_20lieu_20où_20le_20combat_20est_20tenu_332',['Le premier lieu où le combat est tenu',['../lot-50.html#autotoc_md587',1,'']]],
  ['prend_333',['Ce que le découpage prend',['../Stamps_8h.html#autotoc_md1203',1,'']]],
  ['prennent_20la_20couleur_20des_20jetons_334',['Les contrôles Qt prennent la couleur des jetons',['../guide-conception-qds.html#autotoc_md54',1,'']]],
  ['presentation_2017_335',['Presentation (17)',['../cahiertest.html#autotoc_md26',1,'']]],
  ['preuve_336',['&lt;span class=&quot;tt&quot;&gt;LOT-47&lt;/span&gt; — Socle de classe, et le guerrier comme preuve',['../roadmap.html#lot-47',1,'']]],
  ['preuve_20de_20concept_20_3a_20cinq_20planches_20à_20la_20main_337',['LOT-91 — Preuve de concept : cinq planches à la main',['../lot-91-poc.html',1,'lot-91']]],
  ['principal_338',['Le menu principal',['../manuel-jouer.html#autotoc_md1122',1,'']]],
  ['principal_20maquette_2006_339',['T3.1 — Le menu principal (maquette 06)',['../lot-87.html#autotoc_md687',1,'']]],
  ['principe_20_3a_20ne_20jamais_20coder_20«_20en_20dur_20»_20une_20touche_20dans_20le_20gameplay_340',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md99',1,'']]],
  ['principe_20du_20pas_20de_20temps_20fixe_341',['Le principe du pas de temps fixe',['../guide-boucle.html#autotoc_md39',1,'']]],
  ['prises_20en_20route_342',['prises en route',['../lot-11.html#autotoc_md390',1,'Décisions prises en route'],['../lot-21.html#autotoc_md473',1,'Décisions prises en route'],['../lot-22.html#autotoc_md483',1,'Décisions prises en route'],['../lot-23.html#autotoc_md492',1,'Décisions prises en route'],['../lot-24.html#autotoc_md499',1,'Décisions prises en route']]],
  ['prises_20et_20questions_20restantes_343',['8. Décisions prises et questions restantes',['../roadmap.html#autotoc_md943',1,'']]],
  ['problème_344',['problème',['../manuel-partager-niveau.html#autotoc_md1133',1,'En cas de problème'],['../lot-02.html#autotoc_md320',1,'Le problème'],['../lot-03.html#autotoc_md327',1,'Le problème'],['../lot-05.html#autotoc_md340',1,'Le problème'],['../roadmap.html#autotoc_md966',1,'Le problème']]],
  ['problème_20_3a_20éditer_20une_20carte_20sans_20re_20coder_20le_20moteur_345',['Le problème : éditer une carte sans (re)coder le moteur',['../guide-editeur.html#autotoc_md85',1,'']]],
  ['problème_20que_20cette_20classe_20résout_346',['Le problème que cette classe résout',['../classhmi_1_1PendingData.html#autotoc_md1243',1,'']]],
  ['problème_20que_20l_20ecs_20résout_347',['Le problème que l&apos;ECS résout',['../guide-ecs.html#autotoc_md76',1,'']]],
  ['procédural_20fichiers_20et_20replis_348',['Les textures : atlas procédural, fichiers et replis',['../guide-rendu.html#autotoc_md160',1,'']]],
  ['production_349',['production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md799',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md817',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md824',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md830',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md842',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md848',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md854',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md860',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md866',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md872',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md878',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md885',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md891',1,'PNJ — localisateurs, pas liste de production']]],
  ['production_20du_2018_20septembre_202026_350',['La production du 18 septembre 2026',['../lot-93.html#autotoc_md754',1,'']]],
  ['production_20et_20acceptation_351',['Production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html#autotoc_md898',1,'']]],
  ['production_20et_20acceptation_352',['production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html#autotoc_md903',1,'Préparation, production et acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-02-arenarea-galender.html#autotoc_md905',1,'Préparation, production et acceptation']]],
  ['produire_353',['Ce que le cahier ne fait pas produire',['../lot-87-cahier-assets.html#lot-87-cahier-exclusions',1,'']]],
  ['produire_20dans_20quel_20ordre_354',['Produire, dans quel ordre',['../lot-87-cahier-assets.html#autotoc_md659',1,'']]],
  ['produire_20selon_20les_20régions_20jouées_355',['LOT-CREATION-ASSETS — Produire selon les régions jouées',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html',1,'']]],
  ['produit_356',['L&apos;éditeur : un outil, pas un produit',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['produit_20au_20delà_20du_20moteur_357',['Objectifs produit (au-delà du moteur)',['../spec-vision.html#autotoc_md306',1,'']]],
  ['produit_20pas_358',['Ce que Claude ne produit pas',['../lot-87.html#autotoc_md665',1,'']]],
  ['produit_20tout_20de_20même_20une_20entité_359',['Un type inconnu produit tout de même une entité',['../lot-10.html#autotoc_md380',1,'']]],
  ['produites_360',['produites',['../roadmap.html#autotoc_md950',1,'9.2 Six mécaniques étaient consommées sans être produites'],['../lot-87.html#autotoc_md682',1,'T2.5 — Le manifeste étendu aux images produites'],['../lot-87.html#autotoc_md683',1,'T2.6 — La réception des images produites']]],
  ['produites_2018_20septembre_202026_361',['La réception des images produites (18 septembre 2026)',['../lot-87.html#lot-87-reception',1,'']]],
  ['profondeur_362',['La profondeur',['../ArenaSceneComposer_8h.html#autotoc_md1210',1,'']]],
  ['profondeur_20_3a_20trier_20par_20le_20pied_20lot_2007_363',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md167',1,'']]],
  ['programme_364',['Programme',['../lots.html#autotoc_md912',1,'']]],
  ['programme_365',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md951',1,'']]],
  ['programme_20de_20lots_20proposé_20—_20la_20filière_20contenu_366',['5. Programme de lots proposé — la filière contenu',['../roadmap.html#autotoc_md927',1,'']]],
  ['programme_20en_20six_20phases_367',['Programme, en six phases',['../lot-87.html#autotoc_md666',1,'']]],
  ['progression_368',['4. Progression',['../spec-rpg.html#autotoc_md297',1,'']]],
  ['progression_369',['progression',['../roadmap.html#lot-74',1,'&lt;span class=&quot;tt&quot;&gt;LOT-74&lt;/span&gt; — Expérience et progression'],['../spec-rpg.html',1,'Personnage et progression']]],
  ['progression_20de_20classe_370',['&lt;span class=&quot;tt&quot;&gt;LOT-84&lt;/span&gt; — Les 31 tables de progression de classe',['../roadmap.html#lot-84',1,'']]],
  ['progression_20et_20tâches_371',['Progression et tâches',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html#autotoc_md780',1,'']]],
  ['progressivement_372',['Importer tout, honorer progressivement',['../roadmap.html#autotoc_md928',1,'']]],
  ['projet_373',['1. Récupérer le projet',['../manuel-partager-niveau.html#autotoc_md1128',1,'']]],
  ['projet_20vous_20montre_20et_20ce_20qu_20il_20vous_20cache_374',['Ce que le projet vous montre, et ce qu&apos;il vous cache',['../guide-conception-qds.html#autotoc_md48',1,'']]],
  ['promet_375',['4. Ce qu&apos;une donnée promet',['../spec-contenu.html#autotoc_md194',1,'']]],
  ['prompts_376',['Les prompts',['../lot-87-cahier-assets.html#autotoc_md657',1,'']]],
  ['proposé_20—_20la_20filière_20contenu_377',['5. Programme de lots proposé — la filière contenu',['../roadmap.html#autotoc_md927',1,'']]],
  ['proposée_20—_20central_20empire_378',['Première série proposée — Central Empire',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md793',1,'']]],
  ['proposée_20—_20darkall_379',['Première série proposée — Darkall',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md800',1,'']]],
  ['proposée_20—_20imperial_20ben’net_380',['Première série proposée — Imperial Ben’net',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md806',1,'']]],
  ['proposée_20—_20kingdom_20of_20kolbjörn_381',['Première série proposée — Kingdom of Kolbjörn',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md812',1,'']]],
  ['proposée_20—_20magocracy_20of_20mage_20tower_382',['Première série proposée — Magocracy of Mage Tower',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md818',1,'']]],
  ['proposée_20—_20mystical_20wasteland_383',['Première série proposée — Mystical / Wasteland',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md825',1,'']]],
  ['proposée_20—_20pénombre_384',['Première série proposée — Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md831',1,'']]],
  ['proposée_20—_20republic_20of_20freelands_385',['Première série proposée — Republic of Freelands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md837',1,'']]],
  ['proposée_20—_20seashores_386',['Première série proposée — Seashores',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md843',1,'']]],
  ['proposée_20—_20sindile_20forest_387',['Première série proposée — Sindile Forest',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md849',1,'']]],
  ['proposée_20—_20storm_20islands_388',['Première série proposée — Storm Islands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md855',1,'']]],
  ['proposée_20—_20stravian_20domains_389',['Première série proposée — Stravian Domains',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md861',1,'']]],
  ['proposée_20—_20taii’maku_390',['Première série proposée — Taii’Maku',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md867',1,'']]],
  ['proposée_20—_20theocracy_20of_20kepesh_391',['Première série proposée — Theocracy of Kepesh',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md873',1,'']]],
  ['proposée_20—_20tsvetan_392',['Première série proposée — Tsvetan',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md879',1,'']]],
  ['proposée_20—_20undertanares_393',['Première série proposée — Undertanares',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md886',1,'']]],
  ['proposée_20—_20yama_394',['Première série proposée — Yama',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md892',1,'']]],
  ['propre_20catégorie_395',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md124',1,'']]],
  ['propriétés_20de_20zone_396',['Les propriétés de zone',['../classcore_1_1BattleGrid.html#autotoc_md1151',1,'']]],
  ['propriétés_20de_20zone_20_3a_20un_20crochet_20et_20une_20seule_20lecture_397',['Les propriétés de zone : un crochet, et une seule lecture',['../lot-19.html#autotoc_md449',1,'']]],
  ['propriétés_20libres_398',['Entités et propriétés libres',['../guide-niveaux.html#autotoc_md144',1,'']]],
  ['propriétés_20nommées_20plutôt_20que_20la_20table_20brute_399',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1233',1,'']]],
  ['propriétés_20pas_20de_20la_20prose_400',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md482',1,'']]],
  ['prose_401',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md482',1,'']]],
  ['provenance_402',['1. Provenance',['../spec-contenu.html#autotoc_md191',1,'']]],
  ['provisionnement_20_3a_20qt_20multimedia_403',['Provisionnement : Qt Multimedia',['../guide-audio.html#autotoc_md35',1,'']]],
  ['provisoire_404',['Les blocs de Tanares (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;, relevé provisoire)',['../lot-93.html#autotoc_md760',1,'']]],
  ['provisoire_20et_20dit_20comme_20tel_405',['Le coup d&apos;essai, provisoire et dit comme tel',['../lot-50.html#autotoc_md590',1,'']]],
  ['provisoires_406',['LOT-36 — Espèces, historiques et classes provisoires',['../lot-36.html',1,'lots']]],
  ['provisoires_20et_20le_20déclarent_407',['Les quatre classes sont provisoires, et le déclarent',['../lot-36.html#autotoc_md544',1,'']]],
  ['provisoires_20et_20le_20disent_408',['Les dons sont livrés provisoires, et le disent',['../lot-43.html#autotoc_md582',1,'']]],
  ['publier_409',['7. Enregistrer, contrôler, publier',['../guide-usage-editeur.html#autotoc_md1034',1,'']]],
  ['publier_20votre_20carte_410',['4. Publier votre carte',['../manuel-partager-niveau.html#autotoc_md1131',1,'']]],
  ['puis_20diffuser_411',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Logger.html&quot; title=&quot;core::Logger&quot;&gt;core::Logger&lt;/a&gt; : filtrer puis diffuser',['../guide-journalisation.html#autotoc_md121',1,'']]],
  ['puis_20refermée_412',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md560',1,'']]],
  ['puis_20soumettre_413',['Composer, puis soumettre',['../guide-rendu.html#autotoc_md165',1,'']]],
  ['pur_20et_20c_20est_20ce_20qui_20le_20rend_20vérifiable_414',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md432',1,'']]],
  ['pur_20et_20il_20ne_20s_20arrête_20que_20sur_20une_20réplique_415',['Le runner : pur, et il ne s&apos;arrête que sur une réplique',['../lot-15.html#autotoc_md422',1,'']]],
  ['pure_20et_20c_20est_20tout_20son_20intérêt_416',['Pure, et c&apos;est tout son intérêt',['../classcore_1_1DialogueRunner.html#autotoc_md1184',1,'']]],
  ['purge_20et_20remise_20à_20nu_417',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['purger_20en_20premier_418',['Pourquoi purger en premier',['../lot-01.html#autotoc_md310',1,'']]]
];
