var searchData=
[
  ['pénombral_0',['&lt;span class=&quot;tt&quot;&gt;LOT-90&lt;/span&gt; — Le plan pénombral',['../roadmap.html#lot-90',1,'']]],
  ['pénombre_1',['Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html',1,'Pénombre'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md827',1,'Première série proposée — Pénombre']]],
  ['périmètre_2',['Périmètre',['../lot-01.html#autotoc_md307',1,'Périmètre'],['../lot-02.html#autotoc_md318',1,'Périmètre'],['../lot-03.html#autotoc_md324',1,'Périmètre'],['../lot-04.html#autotoc_md330',1,'Périmètre'],['../lot-05.html#autotoc_md337',1,'Périmètre'],['../lot-06.html#autotoc_md344',1,'Périmètre'],['../lot-07.html#autotoc_md351',1,'Périmètre'],['../lot-08.html#autotoc_md356',1,'Périmètre'],['../lot-09.html#autotoc_md368',1,'Périmètre'],['../lot-77.html#autotoc_md629',1,'Périmètre'],['../lot-78.html#autotoc_md633',1,'Périmètre'],['../roadmap.html#autotoc_md957',1,'Périmètre'],['../roadmap.html#autotoc_md963',1,'Périmètre'],['../roadmap.html#autotoc_md968',1,'Périmètre'],['../roadmap.html#autotoc_md973',1,'Périmètre'],['../roadmap.html#autotoc_md978',1,'Périmètre'],['../roadmap.html#autotoc_md988',1,'Périmètre'],['../roadmap.html#autotoc_md998',1,'Périmètre']]],
  ['périmètre_3',['Vision &amp;amp; périmètre',['../spec-vision.html',1,'specifications']]],
  ['périmètre_20et_20provenance_4',['Périmètre et provenance',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html#autotoc_md1227',1,'']]],
  ['périmètre_20vertical_20slice_5',['Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)',['../spec-vision.html#autotoc_md303',1,'']]],
  ['périmé_6',['Attention : le texte des maquettes était périmé',['../lot-86.html#autotoc_md645',1,'']]],
  ['périphériques_7',['1. Périphériques',['../spec-controles.html#autotoc_md197',1,'']]],
  ['pack_20de_20maquettes_8',['T5.1 — Le pack de maquettes',['../lot-87.html#autotoc_md696',1,'']]],
  ['page_20à_20l_20autre_9',['Sa gouttière bouge d&apos;une page à l&apos;autre',['../lot-36.html#autotoc_md536',1,'']]],
  ['page_20hors_20code_20pour_20le_20jeu_20en_20code_20pour_20l_20éditeur_10',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['pages_11',['Pages',['../manuel.html#autotoc_md1098',1,'']]],
  ['paie_12',['C&apos;est le lot où le §4 se paie',['../lot-34.html#autotoc_md523',1,'']]],
  ['palette_20est_20relevée_20pas_20choisie_13',['La palette est relevée, pas choisie',['../lot-66.html#autotoc_md595',1,'']]],
  ['palette_20et_20les_20outils_20_3a_20des_20panneaux_20qt_20séparés_20du_20canevas_14',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md88',1,'']]],
  ['palette_20relevée_15',['La palette relevée',['../lot-87.html#autotoc_md673',1,'']]],
  ['panneaux_20groupés_20et_20qui_20suivent_20l_20outil_16',['Des panneaux groupés, et qui suivent l&apos;outil',['../guide-design-ihm.html#autotoc_md63',1,'']]],
  ['panneaux_20qt_20séparés_20du_20canevas_17',['La palette et les outils : des panneaux Qt séparés du canevas',['../guide-editeur.html#autotoc_md88',1,'']]],
  ['panthéon_20et_20expressions_20matérielles_18',['Panthéon et expressions matérielles',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md784',1,'']]],
  ['panthéon_20et_20organisations_19',['&lt;span class=&quot;tt&quot;&gt;LOT-80&lt;/span&gt; — Factions, panthéon et organisations',['../roadmap.html#lot-80',1,'']]],
  ['par_20case_20',['La règle, case par case',['../CollisionDerivation_8h.html#autotoc_md1148',1,'']]],
  ['par_20catégorie_21',['Les macros de journalisation, par catégorie',['../guide-journalisation.html#autotoc_md122',1,'']]],
  ['par_20construction_22',['par construction',['../lot-22.html#autotoc_md475',1,'La symétrie, par construction'],['../LineOfSight_8h.html#autotoc_md1140',1,'La symétrie, par construction']]],
  ['par_20critère_23',['Trois règles de désignation, une par critère',['../lot-10.html#autotoc_md375',1,'']]],
  ['par_20instantané_24',['Lecture seule, et par instantané',['../ArenaSceneComposer_8h.html#autotoc_md1181',1,'']]],
  ['par_20instantané_20comme_20l_20arène_25',['Par instantané, comme l&apos;arène',['../WorldSceneComposer_8h.html#autotoc_md1189',1,'']]],
  ['par_20l_20écran_20et_20non_20par_20l_20appelant_26',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md615',1,'']]],
  ['par_20l_20appelant_27',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md615',1,'']]],
  ['par_20l_20auteur_28',['Ce que la migration a trouvé, à trancher par l&apos;auteur',['../lot-editor-12.html#autotoc_md1079',1,'']]],
  ['par_20la_20donnée_29',['Deux natures de déclencheur, distinguées par la donnée',['../lot-18.html#autotoc_md432',1,'']]],
  ['par_20le_20pied_20lot_2007_30',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md166',1,'']]],
  ['par_20lieu_31',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['par_20lot_32',['&lt;span class=&quot;tt&quot;&gt;LOT-51&lt;/span&gt; à &lt;span class=&quot;tt&quot;&gt;LOT-65&lt;/span&gt; — une classe par lot',['../roadmap.html#lot-51',1,'']]],
  ['par_20lot_20sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_33',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md90',1,'']]],
  ['par_20maquette_20une_20planche_20par_20lieu_34',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['par_20qstr_35',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1214',1,'']]],
  ['par_20rapport_20au_20texte_20de_20la_20feuille_20de_20route_36',['Écarts par rapport au texte de la feuille de route',['../lot-88.html#autotoc_md708',1,'']]],
  ['par_20son_20cadre_20pas_20à_20l_20estime_37',['L&apos;encart se lit par son cadre, pas à l&apos;estime',['../lot-37.html#autotoc_md547',1,'']]],
  ['par_20son_20pied_38',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md1165',1,'']]],
  ['par_20tour_39',['LOT-20 — Initiative et tour par tour',['../lot-20.html',1,'lots']]],
  ['par_20une_40',['Quatre corruptions d&apos;OCR déclarées, une par une',['../lot-36.html#autotoc_md535',1,'']]],
  ['par_20une_20règle_20écrite_41',['L&apos;initiative : jetée une fois, départagée par une règle écrite',['../lot-20.html#autotoc_md453',1,'']]],
  ['par_20vision_20contre_20une_20liste_20fermée_42',['7. La revue par vision, contre une liste fermée',['../lot-91-poc.html#autotoc_md730',1,'']]],
  ['par_20y_43',['LOT-07 — Rendu top-down et tri par Y',['../lot-07.html',1,'lots']]],
  ['parchemin_20pixel_44',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md660',1,'']]],
  ['parcourent_20_3a_20le_20graphe_20des_20quartiers_45',['LOT-96 — Martpart et Arenarea se parcourent : le graphe des quartiers',['../lot-96.html',1,'lots']]],
  ['parcourir_20le_20monde_46',['Parcourir le monde',['../manuel-jouer.html#autotoc_md1094',1,'']]],
  ['parcours_20en_20largeur_47',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1142',1,'']]],
  ['parcourt_20_3a_20exploration_20dans_20le_20jeu_20et_20première_20carte_48',['LOT-09 — Le Colisée se parcourt : exploration dans le jeu et première carte',['../lot-09.html',1,'lots']]],
  ['part_49',['part',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1195',1,'Pourquoi un item à part'],['../ExplorationSession_8h.html#autotoc_md1161',1,'Pourquoi une session à part']]],
  ['partagent_20jamais_20une_20case_50',['Deux créatures ne partagent jamais une case',['../lot-19.html#autotoc_md442',1,'']]],
  ['partager_20une_20carte_20sans_20ligne_20de_20commande_51',['Créer et partager une carte (sans ligne de commande)',['../manuel-partager-niveau.html',1,'manuel']]],
  ['partie_20»_20_3a_20un_20échafaudage_20et_20il_20est_20écrit_52',['« Nouvelle partie » : un échafaudage, et il est écrit',['../lot-68.html#autotoc_md616',1,'']]],
  ['partie_20dans_20la_20capitale_20_3a_20sauvegarde_20riche_53',['LOT-17 — Reprendre sa partie dans la Capitale : sauvegarde riche',['../roadmap.html#lot-17',1,'']]],
  ['partout_54',['Le vocabulaire : « niveau » devient « carte », partout',['../lot-67.html#autotoc_md609',1,'']]],
  ['pas_55',['pas',['../classcore_1_1BattleGrid.html#autotoc_md1123',1,'Ce qu&apos;elle ne fait pas'],['../classhmi_1_1CharacterSheetModel.html#autotoc_md1200',1,'Ce qu&apos;elle ne refait pas'],['../namespacecore.html#autotoc_md1145',1,'Ce qu&apos;elle ne vérifie pas'],['../classhmi_1_1ArenaModel.html#autotoc_md1193',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1WorldModel.html#autotoc_md1217',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1GamepadNavigator.html#autotoc_md1205',1,'Ce qu&apos;il fait, et ce qu&apos;il ne fait pas'],['../classhmi_1_1ScreenRouter.html#autotoc_md1215',1,'Ce qu&apos;il n&apos;est pas'],['../structcore_1_1ExplorationSnapshot.html#autotoc_md1130',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../EnemyAi_8h.html#autotoc_md1133',1,'Ce que ce fichier décide, et que le Guide ne dit pas'],['../lot-15.html#autotoc_md415',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-18.html#autotoc_md427',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-19.html#autotoc_md438',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-20.html#autotoc_md451',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-21.html#autotoc_md464',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-22.html#autotoc_md473',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-23.html#autotoc_md483',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-50.html#autotoc_md582',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-87.html#autotoc_md661',1,'Ce que Claude ne produit pas'],['../lot-50.html#autotoc_md587',1,'Ce que l&apos;écran compose, et ce qu&apos;il ne compose pas'],['../Arena_8h.html#autotoc_md1115',1,'Ce que l&apos;arène est, et ce qu&apos;elle n&apos;est pas'],['../lot-18.html#autotoc_md429',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas'],['../lot-14.html#autotoc_md410',1,'Ce que le lot n&apos;invente pas'],['../lot-10.html#autotoc_md377',1,'Ce que le lot ne fait pas'],['../lot-12.html#autotoc_md396',1,'Ce que le lot ne fait pas'],['../lot-13.html#autotoc_md405',1,'Ce que le lot ne fait pas'],['../lot-14.html#autotoc_md412',1,'Ce que le lot ne fait pas'],['../lot-30.html#autotoc_md503',1,'Ce que le lot ne fait pas'],['../lot-32.html#autotoc_md510',1,'Ce que le lot ne fait pas'],['../lot-33.html#autotoc_md519',1,'Ce que le lot ne fait pas'],['../lot-34.html#autotoc_md529',1,'Ce que le lot ne fait pas'],['../lot-36.html#autotoc_md542',1,'Ce que le lot ne fait pas'],['../lot-38.html#autotoc_md563',1,'Ce que le lot ne fait pas'],['../lot-39.html#autotoc_md571',1,'Ce que le lot ne fait pas'],['../lot-43.html#autotoc_md579',1,'Ce que le lot ne fait pas'],['../lot-66.html#autotoc_md602',1,'Ce que le lot ne fait pas'],['../lot-67.html#autotoc_md610',1,'Ce que le lot ne fait pas'],['../lot-68.html#autotoc_md618',1,'Ce que le lot ne fait pas'],['../lot-76.html#autotoc_md626',1,'Ce que le lot ne fait pas'],['../ArenaSceneComposer_8h.html#autotoc_md1180',1,'Ce qui n&apos;y est pas'],['../lot-12.html#autotoc_md392',1,'Deux arrondis qui ne se voient pas'],['../guide-ecs.html#autotoc_md80',1,'Exemple pas à pas'],['../guide-conception-qds.html#autotoc_md56',1,'Les ornements se tracent, ils ne se collent pas'],['../CombatPreview_8h.html#autotoc_md1124',1,'Une prévisualisation qui ne ment pas']]],
  ['pas_20«_20une_20seule_20hmilib_20»_56',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md317',1,'']]],
  ['pas_20à_20l_20estime_57',['L&apos;encart se lit par son cadre, pas à l&apos;estime',['../lot-37.html#autotoc_md547',1,'']]],
  ['pas_20à_20pas_58',['Exemple pas à pas',['../guide-ecs.html#autotoc_md80',1,'']]],
  ['pas_20écrit_20de_20classdefinition_20_3a_20elle_20existait_20déjà_59',['Le lot n&apos;a pas écrit de &lt;span class=&quot;tt&quot;&gt;ClassDefinition&lt;/span&gt; : elle existait déjà',['../lot-13.html#autotoc_md400',1,'']]],
  ['pas_20ce_20qui_20bloque_60',['Couches : ce qu&apos;on voit n&apos;est pas ce qui bloque',['../guide-niveaux.html#autotoc_md142',1,'']]],
  ['pas_20choisie_61',['La palette est relevée, pas choisie',['../lot-66.html#autotoc_md595',1,'']]],
  ['pas_20confondre_62',['Deux systèmes de coordonnées à ne pas confondre',['../guide-niveaux.html#autotoc_md138',1,'']]],
  ['pas_20dans_20sa_20rangée_63',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md524',1,'']]],
  ['pas_20de_20l_20algorithme_64',['Le départage est une règle, et elle ne dépend pas de l&apos;algorithme',['../lot-19.html#autotoc_md440',1,'']]],
  ['pas_20de_20la_20prose_65',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md478',1,'']]],
  ['pas_20de_20simulation_20et_20les_20entrées_66',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md43',1,'']]],
  ['pas_20de_20temps_20fixe_67',['pas de temps fixe',['../guide-boucle.html',1,'Boucle de jeu et pas de temps fixe'],['../guide-boucle.html#autotoc_md38',1,'Le principe du pas de temps fixe']]],
  ['pas_20dire_68',['Ce que le schéma ne peut pas dire',['../lot-36.html#autotoc_md539',1,'']]],
  ['pas_20dire_20et_20qui_20n_20est_20pas_20perdu_20pour_20autant_69',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md516',1,'']]],
  ['pas_20directement_20dans_20l_20item_20qt_20quick_70',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md1182',1,'']]],
  ['pas_20dix_71',['Treize régions, pas dix',['../lot-37.html#autotoc_md546',1,'']]],
  ['pas_20encore_72',['Ce qu&apos;il ne fait pas encore',['../classhmi_1_1GameViewportItem.html#autotoc_md1208',1,'']]],
  ['pas_20encore_20alimentés_73',['Les écrans dessinés mais pas encore alimentés',['../guide-conception-qds.html#autotoc_md52',1,'']]],
  ['pas_20encore_20dans_20l_20éditeur_74',['Ce qui ne se fait pas encore dans l&apos;éditeur',['../guide-usage-editeur.html#autotoc_md1030',1,'']]],
  ['pas_20et_20pourquoi_75',['Ce que le lot ne fait pas, et pourquoi',['../lot-37.html#autotoc_md551',1,'']]],
  ['pas_20faire_20seule_76',['Ce que la conception ne peut pas faire seule',['../spec-interface-ihm.html#autotoc_md267',1,'']]],
  ['pas_20la_20fiche_20il_20la_20désigne_77',['Le composant ECS ne porte pas la fiche, il la désigne',['../lot-13.html#autotoc_md403',1,'']]],
  ['pas_20la_20génération_78',['Le test lit le livre, pas la génération',['../lot-33.html#autotoc_md518',1,'']]],
  ['pas_20la_20matière_79',['Ce que le corpus donne encore : la mesure, pas la matière',['../lot-76.html#autotoc_md622',1,'']]],
  ['pas_20liste_20de_20production_80',['pas liste de production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md795',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md813',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md820',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md826',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md838',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md844',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md850',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md856',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md862',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md868',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md874',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md881',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md887',1,'PNJ — localisateurs, pas liste de production']]],
  ['pas_20livré_81',['Ce que le lot a livré, et ce qu&apos;il n&apos;a pas livré',['../lot-09.html#autotoc_md365',1,'']]],
  ['pas_20par_20qstr_82',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1214',1,'']]],
  ['pas_20perdu_20pour_20autant_83',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md516',1,'']]],
  ['pas_20plus_20tard_84',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md329',1,'']]],
  ['pas_20produire_85',['Ce que le cahier ne fait pas produire',['../lot-87-cahier-assets.html#lot-87-cahier-exclusions',1,'']]],
  ['pas_20réécrire_86',['Ce qui existe déjà, et qu&apos;il ne faut pas réécrire',['../lot-06.html#autotoc_md343',1,'']]],
  ['pas_20rater_87',['Le point à ne pas rater',['../lot-04.html#autotoc_md331',1,'']]],
  ['pas_20s_20arrêter_88',['Traverser n&apos;est pas s&apos;arrêter',['../lot-19.html#autotoc_md443',1,'']]],
  ['pas_20saisi_89',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md501',1,'']]],
  ['pas_20se_20cacher_90',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md1207',1,'']]],
  ['pas_20seulement_20l_20état_91',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md101',1,'']]],
  ['pas_20subi_92',['Le renversement est assumé, pas subi',['../lot-66.html#autotoc_md601',1,'']]],
  ['pas_20sur_20des_20expressions_20régulières_93',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md514',1,'']]],
  ['pas_20sur_20l_20intention_94',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md401',1,'']]],
  ['pas_20tenu_95',['Ce que la feuille de route supposait, et qui n&apos;a pas tenu',['../lot-19.html#autotoc_md439',1,'']]],
  ['pas_20un_20booléen_96',['Un ennemi vaincu est un drapeau de monde, pas un booléen',['../lot-18.html#autotoc_md430',1,'']]],
  ['pas_20un_20changement_20de_20cible_97',['QRhi : une couche d&apos;accès au GPU, pas un changement de cible',['../guide-rendu.html#autotoc_md150',1,'']]],
  ['pas_20un_20hasard_98',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md1143',1,'']]],
  ['pas_20un_20indice_99',['pas un indice',['../lot-20.html#autotoc_md454',1,'Le tour : une place, pas un indice'],['../classcore_1_1TurnOrder.html#autotoc_md1147',1,'Une place, pas un indice']]],
  ['pas_20un_20journal_20c_20est_20une_20exigence_100',['La restitution n&apos;est pas un journal, c&apos;est une exigence',['../lot-12.html#autotoc_md394',1,'']]],
  ['pas_20un_20oubli_101',['L&apos;accentué reste tracé à l&apos;ancienne, et ce n&apos;est pas un oubli',['../lot-76.html#autotoc_md624',1,'']]],
  ['pas_20un_20parcours_20en_20largeur_102',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1142',1,'']]],
  ['pas_20un_20produit_103',['L&apos;éditeur : un outil, pas un produit',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['pas_20un_20total_20de_2020_104',['Un 20 naturel n&apos;est pas un total de 20',['../lot-12.html#autotoc_md393',1,'']]],
  ['pas_20une_20refonte_105',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md997',1,'']]],
  ['pas_20une_20soustraction_106',['pas une soustraction',['../Damage_8h.html#autotoc_md1131',1,'Pourquoi un pipeline, et pas une soustraction'],['../lot-21.html#autotoc_md467',1,'Un pipeline, pas une soustraction']]],
  ['pas_20versionné_107',['1. Le corpus n&apos;est pas versionné',['../roadmap.html#autotoc_md911',1,'']]],
  ['pas_20vu_108',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md391',1,'']]],
  ['passé_20le_2012_20septembre_202026_109',['T1.5 — Le test de l&apos;artiste, passé le 12 septembre 2026',['../lot-87.html#autotoc_md666',1,'']]],
  ['passe_20la_20frontière_110',['Où passe la frontière',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1199',1,'']]],
  ['passent_20pas_20par_20qstr_111',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1214',1,'']]],
  ['patch_112',['Cadres 9-patch',['../lot-87-cahier-assets.html#lot-87-cahier-frame',1,'']]],
  ['pause_113',['Pause',['../guide-ecrans.html#autotoc_md71',1,'Pause'],['../manuel-jouer.html#autotoc_md1096',1,'Pause']]],
  ['pause_20dialogue_20marchand_20journal_20_3a_20restylés_114',['T3.9 — Pause, dialogue, marchand, journal : restylés',['../lot-87.html#autotoc_md691',1,'']]],
  ['peindre_20avec_20les_20pièces_20du_20lieu_115',['Peindre avec les pièces du lieu',['../lot-editor-03.html',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu'],['../roadmap-editeur.html#autotoc_md1011',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu']]],
  ['peindre_20avec_20les_20pièces_20du_20lieu_20lot_20editor_2003_116',['11. Peindre avec les pièces du lieu (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-03&lt;/span&gt;)',['../spec-editeur.html#autotoc_md232',1,'']]],
  ['peindre_20c_20est_20convertir_20un_20pixel_20en_20case_117',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md87',1,'']]],
  ['peindre_20par_20lot_20sans_20dupliquer_20la_20logique_20de_20peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_118',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md90',1,'']]],
  ['peintre_119',['peintre',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1197',1,'Ce que fait le peintre'],['../lot-editor-04.html',1,'LOT-EDITOR-04 — Les outils du peintre'],['../roadmap-editeur.html#autotoc_md1012',1,'LOT-EDITOR-04 — Les outils du peintre']]],
  ['peintre_20lot_20editor_2004_120',['12. Les outils du peintre (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-04&lt;/span&gt;)',['../spec-editeur.html#autotoc_md233',1,'']]],
  ['peinture_20_3a_20core_3a_3aleveldraft_3a_3apaintregion_20leveldraft_3a_3apaintregion_121',['Peindre par lot sans dupliquer la logique de peinture : &lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html#a7fb667e044067f5e9bf16f747d3f5f8e&quot; title=&quot;core::LevelDraft::paintRegion&quot;&gt;LevelDraft::paintRegion&lt;/a&gt;',['../guide-editeur.html#autotoc_md90',1,'']]],
  ['perdent_20leur_20porteur_122',['Exigences qui perdent leur porteur',['../lot-88.html#autotoc_md709',1,'']]],
  ['perdu_20de_20vue_123',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md600',1,'']]],
  ['perdu_20pour_20autant_124',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md516',1,'']]],
  ['performance_125',['1. Performance',['../spec-exigences.html#autotoc_md240',1,'']]],
  ['performance_20à_20respecter_126',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md124',1,'']]],
  ['personnage_127',['personnage',['../spec-rpg.html#autotoc_md294',1,'5. Options de personnage'],['../lot-13.html',1,'LOT-13 — Fiche de personnage']]],
  ['personnage_20_3a_20dons_20multiclassage_20compétences_20langues_128',['LOT-43 — Options de personnage : dons, multiclassage, compétences, langues',['../lot-43.html',1,'lots']]],
  ['personnage_20_3a_20maquette_20et_20interface_129',['LOT-38 — Fiche de personnage : maquette et interface',['../lot-38.html',1,'lots']]],
  ['personnage_20affiché_20_3a_20une_20donnée_20et_20un_20échafaudage_20assumé_130',['Le personnage affiché : une donnée, et un échafaudage assumé',['../lot-38.html#autotoc_md561',1,'']]],
  ['personnage_20de_20démonstration_131',['Le personnage de démonstration',['../lot-18.html#autotoc_md435',1,'']]],
  ['personnage_20et_20progression_132',['Personnage et progression',['../spec-rpg.html',1,'specifications']]],
  ['personnage_20maquette_2003_133',['T3.4 — La fiche de personnage (maquette 03)',['../lot-87.html#autotoc_md686',1,'']]],
  ['personnages_134',['LOT-29 — Groupe de quatre personnages',['../roadmap.html#lot-29',1,'']]],
  ['personne_20n_20y_20meurt_20et_20c_20est_20la_20fiction_20qui_20l_20explique_135',['Personne n&apos;y meurt, et c&apos;est la fiction qui l&apos;explique',['../lot-50.html#autotoc_md585',1,'']]],
  ['perte_20de_20travail_136',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md94',1,'']]],
  ['peuplement_20_3a_20rencontres_20et_20créatures_137',['&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt; — Peuplement : rencontres et créatures',['../roadmap.html#lot-41',1,'']]],
  ['peuplement_20civil_20_3a_20pnj_20marchands_20et_20quêtes_138',['&lt;span class=&quot;tt&quot;&gt;LOT-82&lt;/span&gt; — Peuplement civil : PNJ, marchands et quêtes',['../roadmap.html#lot-82',1,'']]],
  ['peut_20défaire_139',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelDraft.html&quot; title=&quot;core::LevelDraft&quot;&gt;core::LevelDraft&lt;/a&gt; : une carte qu&apos;on peut défaire',['../guide-editeur.html#autotoc_md85',1,'']]],
  ['peut_20on_20se_20tenir_20ici_20»_140',['peut on se tenir ici »',['../lot-19.html#autotoc_md446',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1121',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['peut_20pas_20dire_141',['Ce que le schéma ne peut pas dire',['../lot-36.html#autotoc_md539',1,'']]],
  ['peut_20pas_20dire_20et_20qui_20n_20est_20pas_20perdu_20pour_20autant_142',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md516',1,'']]],
  ['peut_20pas_20faire_20seule_143',['Ce que la conception ne peut pas faire seule',['../spec-interface-ihm.html#autotoc_md267',1,'']]],
  ['phase_200_144',['Critères d&apos;acceptation de la phase 0',['../lot-87.html#autotoc_md700',1,'']]],
  ['phase_201_145',['Où en est la phase 1',['../lot-87.html#autotoc_md667',1,'']]],
  ['phase_201_20—_20le_20module_20de_20conception_146',['Phase 1 — le module de conception',['../lot-87.html#autotoc_md663',1,'']]],
  ['phase_202_20—_20charte_20v2_20et_20matière_20première_147',['Phase 2 — charte v2 et matière première',['../lot-87.html#autotoc_md668',1,'']]],
  ['phase_202_20—_20vérifié_20le_2013_20septembre_202026_148',['Où en est la phase 2 — vérifié le 13 septembre 2026',['../lot-87.html#autotoc_md681',1,'']]],
  ['phase_203_149',['Où en est la phase 3',['../lot-87.html#autotoc_md692',1,'']]],
  ['phase_203_20—_20les_20écrans_150',['Phase 3 — les écrans',['../lot-87.html#autotoc_md682',1,'']]],
  ['phase_204_20—_20le_20cadre_20du_20hud_151',['Phase 4 — le cadre du HUD',['../lot-87.html#autotoc_md693',1,'']]],
  ['phase_205_20—_20retirer_20ce_20qui_20ne_20sert_20plus_152',['Phase 5 — retirer ce qui ne sert plus',['../lot-87.html#autotoc_md695',1,'']]],
  ['phases_153',['phases',['../lot-96.html#autotoc_md770',1,'Les phases'],['../lot-09.html#autotoc_md364',1,'Les six phases'],['../lot-87.html#autotoc_md662',1,'Programme, en six phases']]],
  ['phrase_154',['En une phrase',['../guide-conception-qds.html#autotoc_md46',1,'']]],
  ['pièce_20format_20v4_20lot_20editor_2012_20ex_20lvl_20019_155',['Une case = un type et une pièce (format v4, &lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-LVL-019&lt;/span&gt;)',['../structcore_1_1TileLayer.html#autotoc_md1152',1,'']]],
  ['pièces_20du_20lieu_156',['pièces du lieu',['../lot-editor-03.html',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu'],['../roadmap-editeur.html#autotoc_md1011',1,'LOT-EDITOR-03 — Peindre avec les pièces du lieu']]],
  ['pièces_20du_20lieu_20lot_20editor_2003_157',['11. Peindre avec les pièces du lieu (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-03&lt;/span&gt;)',['../spec-editeur.html#autotoc_md232',1,'']]],
  ['piège_20classique_158',['Le piège classique',['../lot-06.html#autotoc_md345',1,'']]],
  ['piège_20du_20framerate_20variable_159',['Le piège du framerate variable',['../guide-boucle.html#autotoc_md37',1,'']]],
  ['piège_20du_20lot_20_3a_20un_20coffre_20ouvert_20deux_20fois_160',['Le piège du lot : un coffre ouvert deux fois',['../lot-10.html#autotoc_md373',1,'']]],
  ['piège_20du_20tirage_161',['Le piège du tirage',['../roadmap.html#autotoc_md974',1,'']]],
  ['piège_20et_20la_20façon_20dont_20il_20est_20écarté_162',['Le piège, et la façon dont il est écarté',['../lot-14.html#autotoc_md408',1,'']]],
  ['picturaux_20ex_20dec_163',['Décors et plans picturaux (&lt;span class=&quot;tt&quot;&gt;EX-DEC-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md248',1,'']]],
  ['pied_164',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md1165',1,'']]],
  ['pied_20lot_2007_165',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md166',1,'']]],
  ['pile_20d_20écrans_166',['Le routeur et la pile d&apos;écrans',['../guide-ecrans.html#autotoc_md69',1,'']]],
  ['pilotage_167',['Le pilotage',['../ArenaAnimationDriver_8h.html#autotoc_md1176',1,'']]],
  ['pilote_168',['pilote',['../lot-91-poc.html#autotoc_md724',1,'1. Les cinq PNJ du pilote'],['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2CREDITS.html',1,'Provenance des candidats du pilote']]],
  ['pilote_20pnj_169',['Fabrique d’assets — pilote PNJ',['../dir_52c08823cef41a3df195c0648e30f2b3.html#autotoc_md1218',1,'']]],
  ['pipeline_20de_20dessin_20de_20sprites_20_3a_20hmi_3a_3aspritebatch_20hmi_3a_3aspritebatch_170',['Le pipeline de dessin de sprites : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1SpriteBatch.html&quot; title=&quot;hmi::SpriteBatch&quot;&gt;hmi::SpriteBatch&lt;/a&gt;',['../guide-rendu.html#autotoc_md154',1,'']]],
  ['pipeline_20et_20pas_20une_20soustraction_171',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md1131',1,'']]],
  ['pipeline_20pas_20une_20soustraction_172',['Un pipeline, pas une soustraction',['../lot-21.html#autotoc_md467',1,'']]],
  ['piste_20du_20repaire_173',['CE-01 — Martpart, Myr et la piste du repaire',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html',1,'']]],
  ['piste_20ouverte_20puis_20refermée_174',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md556',1,'']]],
  ['pistes_20écartées_175',['8. Risques et pistes écartées',['../roadmap-editeur.html#roadmap-editeur-risques',1,'']]],
  ['pixel_176',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md660',1,'']]],
  ['pixel_20art_177',['pixel art',['../lot-66.html',1,'LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art'],['../guide-design-ihm.html#autotoc_md66',1,'Pourquoi le facteur reste entier après la sortie du pixel art'],['../lot-92.html#autotoc_md740',1,'Risque : l&apos;angle 0,62 en pixel art']]],
  ['pixel_20en_20case_178',['Peindre, c&apos;est convertir un pixel en case',['../guide-editeur.html#autotoc_md87',1,'']]],
  ['pixels_20_3a_20hmi_3a_3acamera2d_20hmi_3a_3acamera2d_179',['Unités monde et pixels : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Camera2D.html&quot; title=&quot;hmi::Camera2D&quot;&gt;hmi::Camera2D&lt;/a&gt;',['../guide-rendu.html#autotoc_md152',1,'']]],
  ['place_180',['Ce que l&apos;agonie trouvera en place',['../lot-21.html#autotoc_md468',1,'']]],
  ['place_20pas_20un_20indice_181',['place pas un indice',['../lot-20.html#autotoc_md454',1,'Le tour : une place, pas un indice'],['../classcore_1_1TurnOrder.html#autotoc_md1147',1,'Une place, pas un indice']]],
  ['placement_20d_20entités_182',['LOT-11 — Éditeur multi-couches et placement d&apos;entités',['../lot-11.html',1,'']]],
  ['placer_20l_20entrée_183',['4. Placer l&apos;entrée',['../guide-usage-editeur.html#autotoc_md1024',1,'']]],
  ['plan_184',['Les cartes — quatre, tracées depuis le plan',['../roadmap.html#autotoc_md979',1,'']]],
  ['plan_20d_20intégration_20_3a_20la_20capitale_20lot_20après_20lot_185',['Le plan d&apos;intégration : la Capitale, lot après lot',['../roadmap.html#roadmap-capitale',1,'']]],
  ['plan_20du_20guide_186',['Plan du guide',['../guide.html#autotoc_md173',1,'']]],
  ['plan_20pénombral_187',['&lt;span class=&quot;tt&quot;&gt;LOT-90&lt;/span&gt; — Le plan pénombral',['../roadmap.html#lot-90',1,'']]],
  ['planche_188',['Renommer, remplacer, changer de planche',['../guide-usage-editeur.html#autotoc_md1029',1,'']]],
  ['planche_20chacun_189',['Les textures — trois jeux, une planche chacun',['../roadmap.html#autotoc_md981',1,'']]],
  ['planche_20gravée_20_3a_20une_20piste_20ouverte_20puis_20refermée_190',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md556',1,'']]],
  ['planche_20par_20lieu_191',['LOT-92 — Atelier des textures : le style de la scène par maquette, une planche par lieu',['../lot-92.html',1,'']]],
  ['planche_20retenue_192',['9. La découpe d&apos;une planche retenue',['../lot-91-poc.html#autotoc_md732',1,'']]],
  ['planches_20à_20la_20main_193',['LOT-91 — Preuve de concept : cinq planches à la main',['../lot-91-poc.html',1,'lot-91']]],
  ['planches_20et_20ce_20qu_20on_20relève_20dessus_194',['La maquette : cinq planches, et ce qu&apos;on relève dessus',['../lot-38.html#autotoc_md554',1,'']]],
  ['plans_20picturaux_20ex_20dec_195',['Décors et plans picturaux (&lt;span class=&quot;tt&quot;&gt;EX-DEC-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md248',1,'']]],
  ['plaques_20et_20bandeaux_196',['Plaques et bandeaux',['../lot-87-cahier-assets.html#lot-87-cahier-plate',1,'']]],
  ['plates_197',['&lt;a class=&quot;el&quot; href=&quot;classhmi_1_1TextureAtlas.html&quot; title=&quot;hmi::TextureAtlas&quot;&gt;hmi::TextureAtlas&lt;/a&gt; : l&apos;atlas des couleurs plates',['../guide-rendu.html#autotoc_md160',1,'']]],
  ['platform_205_198',['Platform (5)',['../cahiertest.html#autotoc_md24',1,'']]],
  ['plausibilité_199',['6. Contrôle de plausibilité',['../spec-contenu.html#autotoc_md195',1,'']]],
  ['player_20s_20guide_20dessine_20ses_20titres_20deux_20fois_200',['Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois',['../lot-36.html#autotoc_md537',1,'']]],
  ['plomberie_20des_20clés_20d_20assets_201',['LOT-39 — Plomberie des clés d&apos;assets',['../lot-39.html',1,'lots']]],
  ['plus_202',['plus',['../guide-audio.html#autotoc_md31',1,'La règle d&apos;or, une fois de plus'],['../lot-87.html#autotoc_md695',1,'Phase 5 — retirer ce qui ne sert plus']]],
  ['plus_20facile_20d_20implémenter_20de_20travers_203',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md577',1,'']]],
  ['plus_20fort_20levier_20du_20programme_204',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md947',1,'']]],
  ['plus_20grande_20que_20la_20fenêtre_205',['Cadrer une carte plus grande que la fenêtre',['../guide-editeur.html#autotoc_md95',1,'']]],
  ['plus_20large_20qu_20estimé_206',['9.5 La collision de numéros est bloquante, et bien plus large qu&apos;estimé',['../roadmap.html#autotoc_md949',1,'']]],
  ['plus_20que_20le_20rpg_207',['2. Le modèle de carte ne porte plus que le RPG',['../lot-88.html#autotoc_md705',1,'']]],
  ['plus_20tard_208',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md329',1,'']]],
  ['plus_20une_20cible_209',['Un coffre vidé n&apos;est plus une cible',['../lot-10.html#autotoc_md374',1,'']]],
  ['plutôt_20qu_20une_20image_20manquante_210',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md1153',1,'']]],
  ['plutôt_20que_20contournées_211',['Trois irrégularités de la source, nommées plutôt que contournées',['../lot-37.html#autotoc_md550',1,'']]],
  ['plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_212',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['plutôt_20que_20fonctions_20libres_213',['Classes plutôt que fonctions libres',['../spec-conventions.html#autotoc_md210',1,'']]],
  ['plutôt_20que_20la_20table_20brute_214',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1201',1,'']]],
  ['plutôt_20que_20réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_215',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md100',1,'']]],
  ['pnj_216',['PNJ',['../lot-91-poc.html#lot-91-methode',1,'4bis. La méthode standard, pour un PNJ'],['../md_Lot_2LOT-CREATION-ASSETS_2epic.html#autotoc_md778',1,'Contrat de qualité PNJ'],['../dir_52c08823cef41a3df195c0648e30f2b3.html#autotoc_md1218',1,'Fabrique d’assets — pilote PNJ'],['../lot-91.html#autotoc_md717',1,'La méthode, pour un PNJ'],['../lot-91.html#autotoc_md720',1,'Les PNJ']]],
  ['pnj_20—_2019_20septembre_202026_217',['Premier essai PNJ — 19 septembre 2026',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html',1,'']]],
  ['pnj_20—_20localisateurs_20pas_20liste_20de_20production_218',['PNJ — localisateurs pas liste de production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md795',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md813',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md820',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md826',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md838',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md844',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md850',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md856',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md862',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md868',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md874',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md881',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md887',1,'PNJ — localisateurs, pas liste de production']]],
  ['pnj_20_3a_20les_20figurines_20du_20character_20compendium_219',['LOT-91 — Atelier des PNJ : les figurines du Character Compendium',['../lot-91.html',1,'lots']]],
  ['pnj_20du_20pilote_220',['1. Les cinq PNJ du pilote',['../lot-91-poc.html#autotoc_md724',1,'']]],
  ['pnj_20du_20poc_221',['T00 — Socle et reprise des cinq PNJ du PoC',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html',1,'']]],
  ['pnj_20et_20dialogues_222',['LOT-15 — PNJ et dialogues',['../lot-15.html',1,'lots']]],
  ['pnj_20marchands_20et_20quêtes_223',['&lt;span class=&quot;tt&quot;&gt;LOT-82&lt;/span&gt; — Peuplement civil : PNJ, marchands et quêtes',['../roadmap.html#lot-82',1,'']]],
  ['poc_224',['PoC',['../dir_52c08823cef41a3df195c0648e30f2b3.html#autotoc_md1221',1,'Acceptation finale du PoC'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html',1,'T00 — Socle et reprise des cinq PNJ du PoC']]],
  ['poc_20fabrique_20d’assets_20—_20état_20de_20production_225',['PoC Fabrique d’assets — état de production',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2rapport-poc.html',1,'']]],
  ['point_226',['Déterministe, et c&apos;est le point',['../namespacecore.html#autotoc_md1154',1,'']]],
  ['point_20à_20ne_20pas_20rater_227',['Le point à ne pas rater',['../lot-04.html#autotoc_md331',1,'']]],
  ['point_20délicat_228',['Le point délicat',['../roadmap.html#autotoc_md999',1,'']]],
  ['point_20ou_20une_20direction_20dans_20le_20monde_229',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md130',1,'']]],
  ['points_20de_20contact_20avec_20le_20jeu_230',['7. Points de contact avec le jeu',['../roadmap-editeur.html#roadmap-editeur-contacts',1,'']]],
  ['points_20de_20vigilance_231',['Points de vigilance',['../lot-02.html#autotoc_md319',1,'']]],
  ['points_20ouverts_232',['Points ouverts',['../lot-96.html#autotoc_md772',1,'']]],
  ['points_20que_20la_20grille_20laissait_20ouverts_233',['Les trois points que la grille laissait ouverts',['../lot-20.html#autotoc_md452',1,'']]],
  ['pop_234',['Ajout et suppression : &lt;em&gt;swap-and-pop&lt;/em&gt;',['../guide-ecs.html#autotoc_md79',1,'']]],
  ['portée_235',['Les mémoires à portée',['../lot-20.html#autotoc_md458',1,'']]],
  ['portée_20ligne_20de_20vue_20et_20zones_20d_20effet_236',['LOT-22 — Portée, ligne de vue et zones d&apos;effet',['../lot-22.html',1,'lots']]],
  ['portée_20par_20l_20écran_20et_20non_20par_20l_20appelant_237',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md615',1,'']]],
  ['portabilité_20reproductibilité_238',['4. Portabilité &amp;amp; reproductibilité',['../spec-exigences.html#autotoc_md243',1,'']]],
  ['portails_20ville_239',['LOT-EDITOR-09 — Le monde : onglets, portails, ville',['../roadmap-editeur.html#lot-editor-09',1,'']]],
  ['porte_20aucun_20texte_240',['Le graphe ne porte aucun texte',['../lot-15.html#autotoc_md416',1,'']]],
  ['porte_20et_20ce_20qu_20il_20ne_20porte_20pas_241',['porte et ce qu il ne porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md1130',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../lot-18.html#autotoc_md429',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas']]],
  ['porte_20le_20lot_242',['La décision qui porte le lot',['../lot-03.html#autotoc_md325',1,'']]],
  ['porte_20pas_243',['porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md1130',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../lot-18.html#autotoc_md429',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas']]],
  ['porte_20pas_20la_20fiche_20il_20la_20désigne_244',['Le composant ECS ne porte pas la fiche, il la désigne',['../lot-13.html#autotoc_md403',1,'']]],
  ['porte_20plus_20que_20le_20rpg_245',['2. Le modèle de carte ne porte plus que le RPG',['../lot-88.html#autotoc_md705',1,'']]],
  ['portent_20le_20soldat_246',['Les sentinelles portent le soldat',['../lot-93.html#autotoc_md751',1,'']]],
  ['porter_247',['1. Porter',['../spec-inventaire.html#autotoc_md269',1,'']]],
  ['porteur_248',['Exigences qui perdent leur porteur',['../lot-88.html#autotoc_md709',1,'']]],
  ['pose_20sous_20la_20valeur_20jamais_20dessus_249',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md541',1,'']]],
  ['poser_20le_20sol_250',['2. Poser le sol',['../guide-usage-editeur.html#autotoc_md1022',1,'']]],
  ['poser_20les_20entités_251',['5. Poser les entités',['../guide-usage-editeur.html#autotoc_md1025',1,'']]],
  ['poste_252',['0. Le poste',['../lot-91-poc.html#autotoc_md723',1,'']]],
  ['pour_20«_20peut_20on_20se_20tenir_20ici_20»_253',['pour « peut on se tenir ici »',['../lot-19.html#autotoc_md446',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1121',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['pour_20«_20se_20tenir_20ici_20»_254',['Une seule règle pour « se tenir ici »',['../namespacecore.html#autotoc_md1144',1,'']]],
  ['pour_20autant_255',['Ce que le schéma ne peut pas dire, et qui n&apos;est pas perdu pour autant',['../lot-33.html#autotoc_md516',1,'']]],
  ['pour_20douze_20refondues_20pour_20trois_256',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md608',1,'']]],
  ['pour_20durer_257',['5. Cinq règles pour durer',['../roadmap-editeur.html#roadmap-editeur-perennite',1,'']]],
  ['pour_20l_20éditeur_258',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['pour_20le_20jeu_20en_20code_20pour_20l_20éditeur_259',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['pour_20les_20dessiner_260',['Ouvrir les écrans pour les dessiner',['../guide-ihm-qt.html#autotoc_md112',1,'']]],
  ['pour_20tout_20le_20code_20de_20simulation_261',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md44',1,'']]],
  ['pour_20trois_262',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md608',1,'']]],
  ['pour_20un_20pnj_263',['pour un PNJ',['../lot-91-poc.html#lot-91-methode',1,'4bis. La méthode standard, pour un PNJ'],['../lot-91.html#autotoc_md717',1,'La méthode, pour un PNJ']]],
  ['pour_20une_20autre_20raison_264',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md598',1,'']]],
  ['pour_20une_20créature_265',['La méthode, pour une créature',['../lot-93.html#autotoc_md748',1,'']]],
  ['pourquoi_266',['pourquoi',['../lot-09.html#autotoc_md367',1,'Écarté, et pourquoi'],['../lot-37.html#autotoc_md551',1,'Ce que le lot ne fait pas, et pourquoi'],['../lot-18.html#autotoc_md434',1,'Ce que le mode combat gèle, et pourquoi'],['../spec-interface-ihm.html#autotoc_md263',1,'Ce qui a changé, et pourquoi'],['../lot-87.html#autotoc_md672',1,'Ce qui est écarté, et pourquoi'],['../lot-86.html#autotoc_md646',1,'Les deux directions écartées, et pourquoi']]],
  ['pourquoi_20«_20batcher_20»_20plutôt_20que_20dessiner_20un_20sprite_20à_20la_20fois_267',['Pourquoi « batcher » plutôt que dessiner un sprite à la fois',['../guide-rendu.html#autotoc_md155',1,'']]],
  ['pourquoi_20c_20est_20celle_20du_20jeu_268',['La règle, et pourquoi c&apos;est celle du jeu',['../ExplorationReach_8h.html#autotoc_md1160',1,'']]],
  ['pourquoi_20ce_20lot_20est_20un_20lot_20d_20ajout_20pas_20une_20refonte_269',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md997',1,'']]],
  ['pourquoi_20ceux_20là_20ne_20passent_20pas_20par_20qstr_270',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md1214',1,'']]],
  ['pourquoi_20chaque_20arête_20n_20est_20contrôlée_20qu_20une_20fois_271',['Le triangle, et pourquoi chaque arête n&apos;est contrôlée qu&apos;une fois',['../lot-32.html#autotoc_md507',1,'']]],
  ['pourquoi_20des_20instantanés_20complets_272',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md91',1,'']]],
  ['pourquoi_20des_20propriétés_20nommées_20plutôt_20que_20la_20table_20brute_273',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1201',1,'']]],
  ['pourquoi_20deux_20binaires_274',['Pourquoi deux binaires',['../guide-ihm-qt.html#autotoc_md108',1,'']]],
  ['pourquoi_20elle_20n_20est_20pas_20un_20parcours_20en_20largeur_275',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1142',1,'']]],
  ['pourquoi_20il_20est_20déterministe_276',['Le marqueur, et pourquoi il est déterministe',['../lot-39.html#autotoc_md569',1,'']]],
  ['pourquoi_20il_20fallait_20l_20écrire_277',['Pourquoi il fallait l&apos;écrire',['../classhmi_1_1GamepadNavigator.html#autotoc_md1204',1,'']]],
  ['pourquoi_20il_20n_20est_20pas_20«_20une_20seule_20hmilib_20»_278',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md317',1,'']]],
  ['pourquoi_20il_20s_20auto_20teste_279',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md502',1,'']]],
  ['pourquoi_20il_20valait_20mieux_280',['Le renversement du milieu du lot, et pourquoi il valait mieux',['../lot-76.html#autotoc_md621',1,'']]],
  ['pourquoi_20journaliser_20dans_20un_20jeu_20vidéo_281',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md118',1,'']]],
  ['pourquoi_20l_20égalité_20stricte_20est_20dangereuse_282',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md135',1,'']]],
  ['pourquoi_20le_20facteur_20reste_20entier_20après_20la_20sortie_20du_20pixel_20art_283',['Pourquoi le facteur reste entier après la sortie du pixel art',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['pourquoi_20les_20maquettes_20remplacent_20la_20charte_20parchemin_20pixel_284',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md660',1,'']]],
  ['pourquoi_20maintenant_20et_20pas_20plus_20tard_285',['Pourquoi maintenant, et pas plus tard',['../lot-04.html#autotoc_md329',1,'']]],
  ['pourquoi_20pas_20directement_20dans_20l_20item_20qt_20quick_286',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md1182',1,'']]],
  ['pourquoi_20purger_20en_20premier_287',['Pourquoi purger en premier',['../lot-01.html#autotoc_md306',1,'']]],
  ['pourquoi_20un_20item_20à_20part_288',['Pourquoi un item à part',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1195',1,'']]],
  ['pourquoi_20un_20marqueur_20plutôt_20qu_20une_20image_20manquante_289',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md1153',1,'']]],
  ['pourquoi_20un_20pipeline_20et_20pas_20une_20soustraction_290',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md1131',1,'']]],
  ['pourquoi_20un_20tiret_20cadratin_20et_20non_20de_20fausses_20données_291',['Pourquoi un tiret cadratin et non de fausses données',['../classhmi_1_1PendingData.html#autotoc_md1212',1,'']]],
  ['pourquoi_20une_20énumération_20et_20non_20un_20nom_20de_20fichier_292',['Pourquoi une énumération et non un nom de fichier',['../classhmi_1_1ScreenRouter.html#autotoc_md1216',1,'']]],
  ['pourquoi_20une_20liste_293',['Pourquoi une liste',['../classcore_1_1ActionEconomy.html#autotoc_md1108',1,'']]],
  ['pourquoi_20une_20session_20à_20part_294',['Pourquoi une session à part',['../ExplorationSession_8h.html#autotoc_md1161',1,'']]],
  ['pourquoi_20une_20table_20de_20chaînes_20et_20non_20une_20structure_20de_20champs_295',['Pourquoi une table de chaînes, et non une structure de champs',['../structhmi_1_1CharacterSheetContext.html#autotoc_md1190',1,'']]],
  ['pourquoi_20une_20zone_20et_20non_20la_20carte_20entière_296',['Pourquoi une zone, et non la carte entière',['../CombatZone_8h.html#autotoc_md1159',1,'']]],
  ['pouvez_20importer_297',['Les modules que vous pouvez importer',['../guide-conception-qds.html#autotoc_md55',1,'']]],
  ['pouvoirs_20et_20menaces_20documentés_298',['pouvoirs et menaces documentés',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md787',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md793',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md800',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md806',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md812',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md818',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md825',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md831',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md837',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md843',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md849',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md855',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md861',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md867',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md873',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md879',1,'Lieux, cultures, pouvoirs et menaces documentés'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md886',1,'Lieux, cultures, pouvoirs et menaces documentés']]],
  ['pouvoirs_20factions_20et_20organisations_299',['Pouvoirs, factions et organisations',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md783',1,'']]],
  ['préalable_20tranchée_300',['La décision préalable, tranchée',['../lot-11.html#autotoc_md380',1,'']]],
  ['préconditions_20manquent_301',['9.4 Le socle technique tient, mais trois préconditions manquent',['../roadmap.html#autotoc_md948',1,'']]],
  ['préfabriqués_302',['LOT-EDITOR-08 — Tampons et préfabriqués',['../roadmap-editeur.html#lot-editor-08',1,'']]],
  ['préparation_303',['préparation',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md791',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md798',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md804',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md810',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md816',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md823',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md829',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md835',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md841',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md847',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md853',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md859',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md865',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md871',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md877',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md884',1,'Limites de la préparation'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md890',1,'Limites de la préparation']]],
  ['préparation_20production_20et_20acceptation_304',['Préparation production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html#autotoc_md899',1,'Préparation, production et acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-02-arenarea-galender.html#autotoc_md901',1,'Préparation, production et acceptation']]],
  ['préparation_20régionale_305',['Références communes et préparation régionale',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html',1,'']]],
  ['prérequis_306',['Prérequis',['../manuel-telecharger.html#autotoc_md1105',1,'']]],
  ['prévenir_20et_20comment_307',['Les deux défauts à prévenir, et comment',['../lot-23.html#autotoc_md486',1,'']]],
  ['prévisualisation_20qui_20ne_20ment_20pas_308',['Une prévisualisation qui ne ment pas',['../CombatPreview_8h.html#autotoc_md1124',1,'']]],
  ['prévue_309',['Intégration technique prévue',['../md_Lot_2LOT-CREATION-ASSETS_2tache-01-carte-test-textures.html#autotoc_md897',1,'']]],
  ['pratique_20pour_20tout_20le_20code_20de_20simulation_310',['Conséquence pratique pour tout le code de simulation',['../guide-boucle.html#autotoc_md44',1,'']]],
  ['pratiques_311',['7. Bonnes pratiques',['../spec-conventions.html#autotoc_md215',1,'']]],
  ['première_312',['Phase 2 — charte v2 et matière première',['../lot-87.html#autotoc_md668',1,'']]],
  ['première_20carte_313',['LOT-09 — Le Colisée se parcourt : exploration dans le jeu et première carte',['../lot-09.html',1,'lots']]],
  ['première_20série_20proposée_20—_20central_20empire_314',['Première série proposée — Central Empire',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md789',1,'']]],
  ['première_20série_20proposée_20—_20darkall_315',['Première série proposée — Darkall',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md796',1,'']]],
  ['première_20série_20proposée_20—_20imperial_20ben’net_316',['Première série proposée — Imperial Ben’net',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md802',1,'']]],
  ['première_20série_20proposée_20—_20kingdom_20of_20kolbjörn_317',['Première série proposée — Kingdom of Kolbjörn',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md808',1,'']]],
  ['première_20série_20proposée_20—_20magocracy_20of_20mage_20tower_318',['Première série proposée — Magocracy of Mage Tower',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md814',1,'']]],
  ['première_20série_20proposée_20—_20mystical_20wasteland_319',['Première série proposée — Mystical / Wasteland',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md821',1,'']]],
  ['première_20série_20proposée_20—_20pénombre_320',['Première série proposée — Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md827',1,'']]],
  ['première_20série_20proposée_20—_20republic_20of_20freelands_321',['Première série proposée — Republic of Freelands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md833',1,'']]],
  ['première_20série_20proposée_20—_20seashores_322',['Première série proposée — Seashores',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md839',1,'']]],
  ['première_20série_20proposée_20—_20sindile_20forest_323',['Première série proposée — Sindile Forest',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md845',1,'']]],
  ['première_20série_20proposée_20—_20storm_20islands_324',['Première série proposée — Storm Islands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md851',1,'']]],
  ['première_20série_20proposée_20—_20stravian_20domains_325',['Première série proposée — Stravian Domains',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md857',1,'']]],
  ['première_20série_20proposée_20—_20taii’maku_326',['Première série proposée — Taii’Maku',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md863',1,'']]],
  ['première_20série_20proposée_20—_20theocracy_20of_20kepesh_327',['Première série proposée — Theocracy of Kepesh',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md869',1,'']]],
  ['première_20série_20proposée_20—_20tsvetan_328',['Première série proposée — Tsvetan',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md875',1,'']]],
  ['première_20série_20proposée_20—_20undertanares_329',['Première série proposée — Undertanares',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md882',1,'']]],
  ['première_20série_20proposée_20—_20yama_330',['Première série proposée — Yama',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md888',1,'']]],
  ['premier_331',['Pourquoi purger en premier',['../lot-01.html#autotoc_md306',1,'']]],
  ['premier_20essai_20pnj_20—_2019_20septembre_202026_332',['Premier essai PNJ — 19 septembre 2026',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html',1,'']]],
  ['premier_20lieu_20où_20le_20combat_20est_20tenu_333',['Le premier lieu où le combat est tenu',['../lot-50.html#autotoc_md583',1,'']]],
  ['prennent_20la_20couleur_20des_20jetons_334',['Les contrôles Qt prennent la couleur des jetons',['../guide-conception-qds.html#autotoc_md53',1,'']]],
  ['presentation_2017_335',['Presentation (17)',['../cahiertest.html#autotoc_md25',1,'']]],
  ['preuve_336',['&lt;span class=&quot;tt&quot;&gt;LOT-47&lt;/span&gt; — Socle de classe, et le guerrier comme preuve',['../roadmap.html#lot-47',1,'']]],
  ['preuve_20de_20concept_20_3a_20cinq_20planches_20à_20la_20main_337',['LOT-91 — Preuve de concept : cinq planches à la main',['../lot-91-poc.html',1,'lot-91']]],
  ['principal_338',['Le menu principal',['../manuel-jouer.html#autotoc_md1093',1,'']]],
  ['principal_20maquette_2006_339',['T3.1 — Le menu principal (maquette 06)',['../lot-87.html#autotoc_md683',1,'']]],
  ['principe_20_3a_20ne_20jamais_20coder_20«_20en_20dur_20»_20une_20touche_20dans_20le_20gameplay_340',['Le principe : ne jamais coder « en dur » une touche dans le gameplay',['../guide-entrees.html#autotoc_md98',1,'']]],
  ['principe_20du_20pas_20de_20temps_20fixe_341',['Le principe du pas de temps fixe',['../guide-boucle.html#autotoc_md38',1,'']]],
  ['prises_20en_20route_342',['prises en route',['../lot-11.html#autotoc_md386',1,'Décisions prises en route'],['../lot-21.html#autotoc_md469',1,'Décisions prises en route'],['../lot-22.html#autotoc_md479',1,'Décisions prises en route'],['../lot-23.html#autotoc_md488',1,'Décisions prises en route'],['../lot-24.html#autotoc_md495',1,'Décisions prises en route']]],
  ['prises_20et_20questions_20restantes_343',['8. Décisions prises et questions restantes',['../roadmap.html#autotoc_md939',1,'']]],
  ['problème_344',['problème',['../manuel-partager-niveau.html#autotoc_md1104',1,'En cas de problème'],['../lot-02.html#autotoc_md316',1,'Le problème'],['../lot-03.html#autotoc_md323',1,'Le problème'],['../lot-05.html#autotoc_md336',1,'Le problème'],['../roadmap.html#autotoc_md962',1,'Le problème']]],
  ['problème_20_3a_20éditer_20une_20carte_20sans_20re_20coder_20le_20moteur_345',['Le problème : éditer une carte sans (re)coder le moteur',['../guide-editeur.html#autotoc_md84',1,'']]],
  ['problème_20que_20cette_20classe_20résout_346',['Le problème que cette classe résout',['../classhmi_1_1PendingData.html#autotoc_md1211',1,'']]],
  ['problème_20que_20l_20ecs_20résout_347',['Le problème que l&apos;ECS résout',['../guide-ecs.html#autotoc_md75',1,'']]],
  ['procédural_20fichiers_20et_20replis_348',['Les textures : atlas procédural, fichiers et replis',['../guide-rendu.html#autotoc_md159',1,'']]],
  ['production_349',['production',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md795',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md813',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md820',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md826',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md838',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md844',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md850',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md856',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md862',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md868',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md874',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md881',1,'PNJ — localisateurs, pas liste de production'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md887',1,'PNJ — localisateurs, pas liste de production'],['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2rapport-poc.html',1,'PoC Fabrique d’assets — état de production']]],
  ['production_20du_2018_20septembre_202026_350',['La production du 18 septembre 2026',['../lot-93.html#autotoc_md750',1,'']]],
  ['production_20et_20acceptation_351',['Production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html#autotoc_md894',1,'']]],
  ['production_20et_20acceptation_352',['production et acceptation',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html#autotoc_md899',1,'Préparation, production et acceptation'],['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-02-arenarea-galender.html#autotoc_md901',1,'Préparation, production et acceptation']]],
  ['production_20observée_353',['Production observée',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html#autotoc_md1224',1,'']]],
  ['produire_354',['Ce que le cahier ne fait pas produire',['../lot-87-cahier-assets.html#lot-87-cahier-exclusions',1,'']]],
  ['produire_20dans_20quel_20ordre_355',['Produire, dans quel ordre',['../lot-87-cahier-assets.html#autotoc_md655',1,'']]],
  ['produire_20selon_20les_20régions_20jouées_356',['LOT-CREATION-ASSETS — Produire selon les régions jouées',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html',1,'']]],
  ['produit_357',['L&apos;éditeur : un outil, pas un produit',['../guide-design-ihm.html#autotoc_md60',1,'']]],
  ['produit_20au_20delà_20du_20moteur_358',['Objectifs produit (au-delà du moteur)',['../spec-vision.html#autotoc_md302',1,'']]],
  ['produit_20pas_359',['Ce que Claude ne produit pas',['../lot-87.html#autotoc_md661',1,'']]],
  ['produit_20tout_20de_20même_20une_20entité_360',['Un type inconnu produit tout de même une entité',['../lot-10.html#autotoc_md376',1,'']]],
  ['produites_361',['produites',['../roadmap.html#autotoc_md946',1,'9.2 Six mécaniques étaient consommées sans être produites'],['../lot-87.html#autotoc_md678',1,'T2.5 — Le manifeste étendu aux images produites'],['../lot-87.html#autotoc_md679',1,'T2.6 — La réception des images produites']]],
  ['produites_2018_20septembre_202026_362',['La réception des images produites (18 septembre 2026)',['../lot-87.html#lot-87-reception',1,'']]],
  ['profondeur_363',['La profondeur',['../ArenaSceneComposer_8h.html#autotoc_md1178',1,'']]],
  ['profondeur_20_3a_20trier_20par_20le_20pied_20lot_2007_364',['La profondeur : trier par le pied (&lt;span class=&quot;tt&quot;&gt;LOT-07&lt;/span&gt;)',['../guide-rendu.html#autotoc_md166',1,'']]],
  ['programme_365',['Programme',['../lots.html#autotoc_md908',1,'']]],
  ['programme_366',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md947',1,'']]],
  ['programme_20de_20lots_20proposé_20—_20la_20filière_20contenu_367',['5. Programme de lots proposé — la filière contenu',['../roadmap.html#autotoc_md923',1,'']]],
  ['programme_20en_20six_20phases_368',['Programme, en six phases',['../lot-87.html#autotoc_md662',1,'']]],
  ['progression_369',['4. Progression',['../spec-rpg.html#autotoc_md293',1,'']]],
  ['progression_370',['progression',['../roadmap.html#lot-74',1,'&lt;span class=&quot;tt&quot;&gt;LOT-74&lt;/span&gt; — Expérience et progression'],['../spec-rpg.html',1,'Personnage et progression']]],
  ['progression_20de_20classe_371',['&lt;span class=&quot;tt&quot;&gt;LOT-84&lt;/span&gt; — Les 31 tables de progression de classe',['../roadmap.html#lot-84',1,'']]],
  ['progression_20et_20tâches_372',['Progression et tâches',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html#autotoc_md776',1,'']]],
  ['progressivement_373',['Importer tout, honorer progressivement',['../roadmap.html#autotoc_md924',1,'']]],
  ['projet_374',['1. Récupérer le projet',['../manuel-partager-niveau.html#autotoc_md1099',1,'']]],
  ['projet_20vous_20montre_20et_20ce_20qu_20il_20vous_20cache_375',['Ce que le projet vous montre, et ce qu&apos;il vous cache',['../guide-conception-qds.html#autotoc_md47',1,'']]],
  ['promet_376',['4. Ce qu&apos;une donnée promet',['../spec-contenu.html#autotoc_md193',1,'']]],
  ['prompts_377',['Les prompts',['../lot-87-cahier-assets.html#autotoc_md653',1,'']]],
  ['proposé_20—_20la_20filière_20contenu_378',['5. Programme de lots proposé — la filière contenu',['../roadmap.html#autotoc_md923',1,'']]],
  ['proposée_20—_20central_20empire_379',['Première série proposée — Central Empire',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md789',1,'']]],
  ['proposée_20—_20darkall_380',['Première série proposée — Darkall',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md796',1,'']]],
  ['proposée_20—_20imperial_20ben’net_381',['Première série proposée — Imperial Ben’net',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md802',1,'']]],
  ['proposée_20—_20kingdom_20of_20kolbjörn_382',['Première série proposée — Kingdom of Kolbjörn',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md808',1,'']]],
  ['proposée_20—_20magocracy_20of_20mage_20tower_383',['Première série proposée — Magocracy of Mage Tower',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md814',1,'']]],
  ['proposée_20—_20mystical_20wasteland_384',['Première série proposée — Mystical / Wasteland',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md821',1,'']]],
  ['proposée_20—_20pénombre_385',['Première série proposée — Pénombre',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md827',1,'']]],
  ['proposée_20—_20republic_20of_20freelands_386',['Première série proposée — Republic of Freelands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md833',1,'']]],
  ['proposée_20—_20seashores_387',['Première série proposée — Seashores',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md839',1,'']]],
  ['proposée_20—_20sindile_20forest_388',['Première série proposée — Sindile Forest',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md845',1,'']]],
  ['proposée_20—_20storm_20islands_389',['Première série proposée — Storm Islands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md851',1,'']]],
  ['proposée_20—_20stravian_20domains_390',['Première série proposée — Stravian Domains',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md857',1,'']]],
  ['proposée_20—_20taii’maku_391',['Première série proposée — Taii’Maku',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md863',1,'']]],
  ['proposée_20—_20theocracy_20of_20kepesh_392',['Première série proposée — Theocracy of Kepesh',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md869',1,'']]],
  ['proposée_20—_20tsvetan_393',['Première série proposée — Tsvetan',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md875',1,'']]],
  ['proposée_20—_20undertanares_394',['Première série proposée — Undertanares',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md882',1,'']]],
  ['proposée_20—_20yama_395',['Première série proposée — Yama',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md888',1,'']]],
  ['propre_20catégorie_396',['Chaque module a sa propre catégorie',['../guide-journalisation.html#autotoc_md123',1,'']]],
  ['propriétés_20de_20zone_397',['Les propriétés de zone',['../classcore_1_1BattleGrid.html#autotoc_md1122',1,'']]],
  ['propriétés_20de_20zone_20_3a_20un_20crochet_20et_20une_20seule_20lecture_398',['Les propriétés de zone : un crochet, et une seule lecture',['../lot-19.html#autotoc_md445',1,'']]],
  ['propriétés_20libres_399',['Entités et propriétés libres',['../guide-niveaux.html#autotoc_md143',1,'']]],
  ['propriétés_20nommées_20plutôt_20que_20la_20table_20brute_400',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1201',1,'']]],
  ['propriétés_20pas_20de_20la_20prose_401',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md478',1,'']]],
  ['prose_402',['La donnée : des propriétés, pas de la prose',['../lot-22.html#autotoc_md478',1,'']]],
  ['provenance_403',['1. Provenance',['../spec-contenu.html#autotoc_md190',1,'']]],
  ['provenance_404',['Périmètre et provenance',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2bilan-poc.html#autotoc_md1227',1,'']]],
  ['provenance_20des_20candidats_20du_20pilote_405',['Provenance des candidats du pilote',['../md__2home_2runner_2work_2JustAnotherRpgGame_2JustAnotherRpgGame_2Tools_2AssetFactory_2CREDITS.html',1,'']]],
  ['provisionnement_20_3a_20qt_20multimedia_406',['Provisionnement : Qt Multimedia',['../guide-audio.html#autotoc_md34',1,'']]],
  ['provisoire_407',['Les blocs de Tanares (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;, relevé provisoire)',['../lot-93.html#autotoc_md756',1,'']]],
  ['provisoire_20et_20dit_20comme_20tel_408',['Le coup d&apos;essai, provisoire et dit comme tel',['../lot-50.html#autotoc_md586',1,'']]],
  ['provisoires_409',['LOT-36 — Espèces, historiques et classes provisoires',['../lot-36.html',1,'lots']]],
  ['provisoires_20et_20le_20déclarent_410',['Les quatre classes sont provisoires, et le déclarent',['../lot-36.html#autotoc_md540',1,'']]],
  ['provisoires_20et_20le_20disent_411',['Les dons sont livrés provisoires, et le disent',['../lot-43.html#autotoc_md578',1,'']]],
  ['publier_412',['7. Enregistrer, contrôler, publier',['../guide-usage-editeur.html#autotoc_md1027',1,'']]],
  ['publier_20votre_20carte_413',['4. Publier votre carte',['../manuel-partager-niveau.html#autotoc_md1102',1,'']]],
  ['puis_20diffuser_414',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Logger.html&quot; title=&quot;core::Logger&quot;&gt;core::Logger&lt;/a&gt; : filtrer puis diffuser',['../guide-journalisation.html#autotoc_md120',1,'']]],
  ['puis_20refermée_415',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md556',1,'']]],
  ['puis_20soumettre_416',['Composer, puis soumettre',['../guide-rendu.html#autotoc_md164',1,'']]],
  ['pur_20et_20c_20est_20ce_20qui_20le_20rend_20vérifiable_417',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md428',1,'']]],
  ['pur_20et_20il_20ne_20s_20arrête_20que_20sur_20une_20réplique_418',['Le runner : pur, et il ne s&apos;arrête que sur une réplique',['../lot-15.html#autotoc_md418',1,'']]],
  ['pure_20et_20c_20est_20tout_20son_20intérêt_419',['Pure, et c&apos;est tout son intérêt',['../classcore_1_1DialogueRunner.html#autotoc_md1155',1,'']]],
  ['purge_20et_20remise_20à_20nu_420',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['purger_20en_20premier_421',['Pourquoi purger en premier',['../lot-01.html#autotoc_md306',1,'']]]
];
