var searchData=
[
  ['ia_0',['Solveur d&apos;apprentissage automatique (&lt;span class=&quot;tt&quot;&gt;EX-IA-*&lt;/span&gt;)',['../spec-retirees.html#autotoc_md247',1,'']]],
  ['ia_20décide_1',['Comment l&apos;IA décide',['../lot-23.html#autotoc_md485',1,'']]],
  ['ia_20tactique_20ennemie_2',['LOT-23 — IA tactique ennemie',['../lot-23.html',1,'']]],
  ['icônes_3',['Icônes',['../lot-87-cahier-assets.html#lot-87-cahier-icon',1,'']]],
  ['ici_4',['Aucune statistique n&apos;est stockée ici',['../structcore_1_1Inventory.html#autotoc_md1158',1,'']]],
  ['ici_20»_5',['ici »',['../namespacecore.html#autotoc_md1144',1,'Une seule règle pour « se tenir ici »'],['../lot-19.html#autotoc_md446',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1121',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['ici_20la_20traduction_20reste_20dehors_6',['Le formatage est ici, la traduction reste dehors',['../structhmi_1_1CharacterSheetContext.html#autotoc_md1191',1,'']]],
  ['identifiants_20d_20exigences_20ex_20…_7',['12. Identifiants d&apos;exigences (EX-…)',['../spec-conventions.html#autotoc_md220',1,'']]],
  ['identité_20du_20dépôt_8',['Identité du dépôt',['../lot-01.html#autotoc_md312',1,'']]],
  ['identité_20pixel_20art_9',['LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art',['../lot-66.html',1,'lots']]],
  ['identité_20visuelle_20des_20écrans_20du_20jeu_10',['7. Identité visuelle des écrans du jeu',['../spec-interface-ihm.html#autotoc_md260',1,'']]],
  ['identités_20deux_20règles_20d_20échelle_20lot_2066_11',['Deux identités, deux règles d&apos;échelle (LOT-66)',['../guide-design-ihm.html#autotoc_md65',1,'']]],
  ['identités_20visuelles_12',['Identités visuelles',['../spec-vision.html#autotoc_md299',1,'']]],
  ['ihm_13',['Interface utilisateur (IHM)',['../spec-interface-ihm.html',1,'specifications']]],
  ['ihm_20075_20avec_20eux_14',['Les ornements restent tracés, et &lt;span class=&quot;tt&quot;&gt;EX-IHM-075&lt;/span&gt; avec eux',['../spec-interface-ihm.html#autotoc_md265',1,'']]],
  ['ihm_20de_20combat_15',['LOT-24 — IHM de combat',['../lot-24.html',1,'']]],
  ['ihm_20qt_20—_20deux_20applications_20deux_20technologies_16',['IHM Qt — deux applications, deux technologies',['../guide-ihm-qt.html',1,'guide']]],
  ['ihm_20qt_20_3a_20la_20mise_20en_20page_20hors_20code_20pour_20le_20jeu_20en_20code_20pour_20l_20éditeur_17',['IHM Qt : la mise en page hors code pour le jeu, en code pour l&apos;éditeur',['../spec-conventions.html#autotoc_md209',1,'']]],
  ['ihm_20sur_20qt_20quick_18',['LOT-86 — Refonte de l&apos;IHM sur Qt Quick',['../lot-86.html',1,'lots']]],
  ['il_20déclenche_19',['10. Le verdict, et ce qu&apos;il déclenche',['../lot-91-poc.html#autotoc_md733',1,'']]],
  ['il_20est_20écarté_20',['Le piège, et la façon dont il est écarté',['../lot-14.html#autotoc_md408',1,'']]],
  ['il_20est_20écrit_21',['« Nouvelle partie » : un échafaudage, et il est écrit',['../lot-68.html#autotoc_md616',1,'']]],
  ['il_20est_20déterministe_22',['Le marqueur, et pourquoi il est déterministe',['../lot-39.html#autotoc_md569',1,'']]],
  ['il_20est_20le_20plus_20facile_20d_20implémenter_20de_20travers_23',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md577',1,'']]],
  ['il_20fait_20et_20ce_20qu_20il_20ne_20fait_20pas_24',['Ce qu&apos;il fait, et ce qu&apos;il ne fait pas',['../classhmi_1_1GamepadNavigator.html#autotoc_md1205',1,'']]],
  ['il_20fallait_20l_20écrire_25',['Pourquoi il fallait l&apos;écrire',['../classhmi_1_1GamepadNavigator.html#autotoc_md1204',1,'']]],
  ['il_20faut_20anticiper_20tant_20que_20rien_20n_20est_20construit_26',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap.html#autotoc_md952',1,'']]],
  ['il_20la_20désigne_27',['Le composant ECS ne porte pas la fiche, il la désigne',['../lot-13.html#autotoc_md403',1,'']]],
  ['il_20laisse_20à_20trancher_28',['Ce que dit le Manuel, et ce qu&apos;il laisse à trancher',['../LineOfSight_8h.html#autotoc_md1139',1,'']]],
  ['il_20n_20a_20pas_20livré_29',['Ce que le lot a livré, et ce qu&apos;il n&apos;a pas livré',['../lot-09.html#autotoc_md365',1,'']]],
  ['il_20n_20est_20pas_30',['Ce qu&apos;il n&apos;est pas',['../classhmi_1_1ScreenRouter.html#autotoc_md1215',1,'']]],
  ['il_20n_20est_20pas_20«_20une_20seule_20hmilib_20»_31',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md317',1,'']]],
  ['il_20ne_20compose_20pas_32',['Ce que l&apos;écran compose, et ce qu&apos;il ne compose pas',['../lot-50.html#autotoc_md587',1,'']]],
  ['il_20ne_20fait_20pas_33',['Ce qu&apos;il fait, et ce qu&apos;il ne fait pas',['../classhmi_1_1GamepadNavigator.html#autotoc_md1205',1,'']]],
  ['il_20ne_20fait_20pas_20encore_34',['Ce qu&apos;il ne fait pas encore',['../classhmi_1_1GameViewportItem.html#autotoc_md1208',1,'']]],
  ['il_20ne_20faut_20pas_20réécrire_35',['Ce qui existe déjà, et qu&apos;il ne faut pas réécrire',['../lot-06.html#autotoc_md343',1,'']]],
  ['il_20ne_20faut_20pas_20se_20cacher_36',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md1207',1,'']]],
  ['il_20ne_20livre_20pas_37',['il ne livre pas',['../lot-15.html#autotoc_md415',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-18.html#autotoc_md427',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-19.html#autotoc_md438',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-20.html#autotoc_md451',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-21.html#autotoc_md464',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-22.html#autotoc_md473',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-23.html#autotoc_md483',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas'],['../lot-50.html#autotoc_md582',1,'Ce que ce lot livre, et ce qu&apos;il ne livre pas']]],
  ['il_20ne_20porte_20pas_38',['il ne porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md1130',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../lot-18.html#autotoc_md429',1,'Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas']]],
  ['il_20ne_20s_20arrête_20que_20sur_20une_20réplique_39',['Le runner : pur, et il ne s&apos;arrête que sur une réplique',['../lot-15.html#autotoc_md418',1,'']]],
  ['il_20porte_20et_20ce_20qu_20il_20ne_20porte_20pas_40',['Ce qu&apos;il porte, et ce qu&apos;il ne porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md1130',1,'']]],
  ['il_20reste_20à_20brancher_41',['Comment on retrouve ce qu&apos;il reste à brancher',['../classhmi_1_1PendingData.html#autotoc_md1213',1,'']]],
  ['il_20s_20auto_20teste_42',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md502',1,'']]],
  ['il_20valait_20mieux_43',['Le renversement du milieu du lot, et pourquoi il valait mieux',['../lot-76.html#autotoc_md621',1,'']]],
  ['il_20vous_20cache_44',['Ce que le projet vous montre, et ce qu&apos;il vous cache',['../guide-conception-qds.html#autotoc_md47',1,'']]],
  ['ils_20atteignent_45',['Les réglages, et ce qu&apos;ils atteignent',['../guide-ihm-qt.html#autotoc_md115',1,'']]],
  ['ils_20ne_20se_20collent_20pas_46',['Les ornements se tracent, ils ne se collent pas',['../guide-conception-qds.html#autotoc_md56',1,'']]],
  ['image_20manquante_47',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md1153',1,'']]],
  ['images_20du_20corpus_20quittent_20le_20dépôt_20l_20écran_20«_20carte_20»_20revient_20sur_20les_20cartes_20de_20l_20auteur_20_3a_20monde_20région_20ville_48',['LOT-94 — Les images du corpus quittent le dépôt ; l&apos;écran « Carte » revient sur les cartes de l&apos;auteur : monde, région, ville',['../lot-94.html',1,'lots']]],
  ['images_20produites_49',['images produites',['../lot-87.html#autotoc_md678',1,'T2.5 — Le manifeste étendu aux images produites'],['../lot-87.html#autotoc_md679',1,'T2.6 — La réception des images produites']]],
  ['images_20produites_2018_20septembre_202026_50',['La réception des images produites (18 septembre 2026)',['../lot-87.html#lot-87-reception',1,'']]],
  ['immédiat_20_3a_20jouer_20sans_20quitter_20l_20éditeur_51',['Essai immédiat : jouer sans quitter l&apos;éditeur',['../guide-editeur.html#autotoc_md92',1,'']]],
  ['imperial_20ben’net_52',['Imperial Ben’net',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html',1,'Imperial Ben’net'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md802',1,'Première série proposée — Imperial Ben’net']]],
  ['implémentation_20décidée_53',['4. Approche d&apos;implémentation (décidée)',['../spec-editeur.html#autotoc_md225',1,'']]],
  ['implémenter_20de_20travers_54',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md577',1,'']]],
  ['importer_55',['Les modules que vous pouvez importer',['../guide-conception-qds.html#autotoc_md55',1,'']]],
  ['importer_20tout_20honorer_20progressivement_56',['Importer tout, honorer progressivement',['../roadmap.html#autotoc_md924',1,'']]],
  ['imposent_20au_20moteur_20—_20relecture_20du_2014_20septembre_202026_57',['4bis. Ce que les deux livres imposent au moteur — relecture du 14 septembre 2026',['../roadmap.html#autotoc_md921',1,'']]],
  ['include_58',['4. Inclusions (#include)',['../spec-conventions.html#autotoc_md205',1,'']]],
  ['inclusions_20include_59',['4. Inclusions (#include)',['../spec-conventions.html#autotoc_md205',1,'']]],
  ['inconnu_20produit_20tout_20de_20même_20une_20entité_60',['Un type inconnu produit tout de même une entité',['../lot-10.html#autotoc_md376',1,'']]],
  ['indice_61',['indice',['../lot-20.html#autotoc_md454',1,'Le tour : une place, pas un indice'],['../classcore_1_1TurnOrder.html#autotoc_md1147',1,'Une place, pas un indice']]],
  ['inférieure_62',['Le budget s&apos;arrondit à la case inférieure',['../lot-19.html#autotoc_md444',1,'']]],
  ['information_63',['information',['../spec-interface-ihm.html#autotoc_md259',1,'6. Architecture de l&apos;information'],['../guide-design-ihm.html',1,'Système de design et architecture de l&apos;information']]],
  ['information_20_3a_20ce_20qui_20informe_20reste_20ce_20qui_20commande_20est_20unique_64',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['informe_20reste_20ce_20qui_20commande_20est_20unique_65',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['initiative_20_3a_20jetée_20une_20fois_20départagée_20par_20une_20règle_20écrite_66',['L&apos;initiative : jetée une fois, départagée par une règle écrite',['../lot-20.html#autotoc_md453',1,'']]],
  ['initiative_20et_20tour_20par_20tour_67',['LOT-20 — Initiative et tour par tour',['../lot-20.html',1,'lots']]],
  ['input_2025_68',['Input (25)',['../cahiertest.html#autotoc_md21',1,'']]],
  ['insère_20dans_20la_20boucle_69',['Où ça s&apos;insère dans la boucle',['../guide-ecrans.html#autotoc_md73',1,'']]],
  ['inspectées_70',['inspectées',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md788',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md794',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md801',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md807',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md819',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md832',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md880',1,'Références visuelles inspectées']]],
  ['instantané_71',['Lecture seule, et par instantané',['../ArenaSceneComposer_8h.html#autotoc_md1181',1,'']]],
  ['instantané_20comme_20l_20arène_72',['Par instantané, comme l&apos;arène',['../WorldSceneComposer_8h.html#autotoc_md1189',1,'']]],
  ['instantané_20porte_20et_20ce_20qu_20il_20ne_20porte_20pas_73',['Ce que l&apos;instantané porte, et ce qu&apos;il ne porte pas',['../lot-18.html#autotoc_md429',1,'']]],
  ['instantanés_20complets_74',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md91',1,'']]],
  ['intégrale_20de_20martpart_20arenarea_20et_20du_20colisée_75',['CE-R01 — Reprise intégrale de Martpart, Arenarea et du Colisée',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-r01-reprise-trois-sites.html',1,'']]],
  ['intégration_202_76',['Tests d&apos;intégration (2)',['../cahiertest.html#autotoc_md27',1,'']]],
  ['intégration_20_3a_20la_20capitale_20lot_20après_20lot_77',['Le plan d&apos;intégration : la Capitale, lot après lot',['../roadmap.html#roadmap-capitale',1,'']]],
  ['intégration_20des_20maquettes_78',['LOT-87 — Charte v2 et intégration des maquettes',['../lot-87.html',1,'lots']]],
  ['intégration_20technique_20prévue_79',['Intégration technique prévue',['../md_Lot_2LOT-CREATION-ASSETS_2tache-01-carte-test-textures.html#autotoc_md897',1,'']]],
  ['intérêt_80',['Pure, et c&apos;est tout son intérêt',['../classcore_1_1DialogueRunner.html#autotoc_md1155',1,'']]],
  ['intention_81',['intention',['../lot-13.html#autotoc_md401',1,'« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention'],['../roadmap.html#autotoc_md931',1,'Le regroupement d&apos;intention']]],
  ['intention_20_3a_20core_3a_3aexplorationintent_20core_3a_3aexplorationintent_82',['L&apos;intention : &lt;a class=&quot;el&quot; href=&quot;structcore_1_1ExplorationIntent.html&quot; title=&quot;core::ExplorationIntent&quot;&gt;core::ExplorationIntent&lt;/a&gt;',['../guide-entrees.html#autotoc_md99',1,'']]],
  ['intentions_83',['Ce qui rend ces exigences autre chose que des intentions',['../spec-interface-ihm.html#autotoc_md266',1,'']]],
  ['inter_20systèmes_84',['8. Communication inter-systèmes',['../spec-architecture.html#autotoc_md181',1,'']]],
  ['interaction_85',['LOT-10 — Entités de carte et interaction',['../lot-10.html',1,'lots']]],
  ['interface_86',['interface',['../guide-rendu.html#autotoc_md151',1,'Les surfaces de dessin : un élément composé avec l&apos;interface'],['../lot-38.html',1,'LOT-38 — Fiche de personnage : maquette et interface']]],
  ['interface_2029_87',['Interface (29)',['../cahiertest.html#autotoc_md22',1,'']]],
  ['interface_20_3a_20hmi_3a_3alocalization_20hmi_3a_3alocalization_88',['La langue de l&apos;interface : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1Localization.html&quot; title=&quot;hmi::Localization&quot;&gt;hmi::Localization&lt;/a&gt;',['../guide-entrees.html#autotoc_md106',1,'']]],
  ['interface_20extrait_20des_20livres_89',['LOT-76 — Habillage d&apos;interface extrait des livres',['../lot-76.html',1,'lots']]],
  ['interface_20hmi_90',['4. Interface (HMI)',['../spec-rendu-technique.html#autotoc_md286',1,'']]],
  ['interface_20sans_20la_20regarder_91',['Vérifier une interface sans la regarder',['../guide-ihm-qt.html#autotoc_md116',1,'']]],
  ['interface_20utilisateur_20ihm_92',['Interface utilisateur (IHM)',['../spec-interface-ihm.html',1,'specifications']]],
  ['interpolationalpha_93',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1FixedTimestep.html#ab7f7f880eef11df91ab7bc647e19bf56&quot; title=&quot;core::FixedTimestep::interpolationAlpha&quot;&gt;interpolationAlpha&lt;/a&gt;',['../guide-boucle.html#autotoc_md42',1,'']]],
  ['invariants_94',['Deux ornements, deux invariants',['../lot-76.html#autotoc_md623',1,'']]],
  ['inventaire_20du_20corpus_95',['2. Inventaire du corpus',['../roadmap.html#autotoc_md913',1,'']]],
  ['inventaire_20et_20économie_96',['Inventaire et économie',['../spec-inventaire.html',1,'specifications']]],
  ['inventaire_20et_20équipement_97',['LOT-14 — Inventaire et équipement',['../lot-14.html',1,'lots']]],
  ['inventaire_20et_20l_20équipement_20maquette_2004_98',['T3.5 — L&apos;inventaire et l&apos;équipement (maquette 04)',['../lot-87.html#autotoc_md687',1,'']]],
  ['inventaire_20et_20séries_20de_20dix_20maximum_99',['Inventaire et séries de dix maximum',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-r01-reprise-trois-sites.html#autotoc_md903',1,'']]],
  ['invente_20pas_100',['Ce que le lot n&apos;invente pas',['../lot-14.html#autotoc_md410',1,'']]],
  ['inverse_101',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md93',1,'']]],
  ['inverse_20du_20chargement_102',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1LevelWriter.html&quot; title=&quot;core::LevelWriter&quot;&gt;core::LevelWriter&lt;/a&gt; : l&apos;inverse du chargement',['../guide-editeur.html#autotoc_md86',1,'']]],
  ['ironhand_103',['CE-R02 — Refaire le soldat Ironhand',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-r02-refonte-ironhand.html',1,'']]],
  ['irrégularités_20de_20la_20source_20nommées_20plutôt_20que_20contournées_104',['Trois irrégularités de la source, nommées plutôt que contournées',['../lot-37.html#autotoc_md550',1,'']]],
  ['islands_105',['Islands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md851',1,'Première série proposée — Storm Islands'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html',1,'Storm Islands']]],
  ['item_20à_20part_106',['Pourquoi un item à part',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1195',1,'']]],
  ['item_20qt_20quick_107',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md1182',1,'']]]
];
