var searchData=
[
  ['façon_20dont_20il_20est_20écarté_0',['Le piège, et la façon dont il est écarté',['../lot-14.html#autotoc_md409',1,'']]],
  ['facile_20d_20implémenter_20de_20travers_1',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md578',1,'']]],
  ['facteur_20d_20agrandissement_2',['Le facteur d&apos;agrandissement',['../guide-conception-qds.html#autotoc_md50',1,'']]],
  ['facteur_20d_20agrandissement_20reste_20entier_20pour_20une_20autre_20raison_3',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md599',1,'']]],
  ['facteur_20reste_20entier_20après_20la_20sortie_20du_20pixel_20art_4',['Pourquoi le facteur reste entier après la sortie du pixel art',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['factions_20et_20organisations_5',['Pouvoirs, factions et organisations',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md784',1,'']]],
  ['factions_20panthéon_20et_20organisations_6',['&lt;span class=&quot;tt&quot;&gt;LOT-80&lt;/span&gt; — Factions, panthéon et organisations',['../roadmap.html#lot-80',1,'']]],
  ['faire_20seule_7',['Ce que la conception ne peut pas faire seule',['../spec-interface-ihm.html#autotoc_md268',1,'']]],
  ['faire_20une_20carte_20dans_20l_20éditeur_8',['Faire une carte dans l&apos;éditeur',['../guide-usage-editeur.html',1,'lot-editor-06']]],
  ['fait_9',['fait',['../lot-88.html#autotoc_md704',1,'Ce qui a été fait'],['../lot-87.html#autotoc_md666',1,'T1.2 à T1.4 — Ce qui a été fait']]],
  ['fait_20deux_20choses_20de_20nature_20différente_10',['Le lint fait deux choses de nature différente',['../lot-39.html#autotoc_md571',1,'']]],
  ['fait_20et_20ce_20qu_20il_20ne_20fait_20pas_11',['Ce qu&apos;il fait, et ce qu&apos;il ne fait pas',['../classhmi_1_1GamepadNavigator.html#autotoc_md1217',1,'']]],
  ['fait_20le_20peintre_12',['Ce que fait le peintre',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1209',1,'']]],
  ['fait_20pas_13',['fait pas',['../classcore_1_1BattleGrid.html#autotoc_md1132',1,'Ce qu&apos;elle ne fait pas'],['../classhmi_1_1GamepadNavigator.html#autotoc_md1217',1,'Ce qu&apos;il fait, et ce qu&apos;il ne fait pas'],['../lot-10.html#autotoc_md378',1,'Ce que le lot ne fait pas'],['../lot-12.html#autotoc_md397',1,'Ce que le lot ne fait pas'],['../lot-13.html#autotoc_md406',1,'Ce que le lot ne fait pas'],['../lot-14.html#autotoc_md413',1,'Ce que le lot ne fait pas'],['../lot-30.html#autotoc_md504',1,'Ce que le lot ne fait pas'],['../lot-32.html#autotoc_md511',1,'Ce que le lot ne fait pas'],['../lot-33.html#autotoc_md520',1,'Ce que le lot ne fait pas'],['../lot-34.html#autotoc_md530',1,'Ce que le lot ne fait pas'],['../lot-36.html#autotoc_md543',1,'Ce que le lot ne fait pas'],['../lot-38.html#autotoc_md564',1,'Ce que le lot ne fait pas'],['../lot-39.html#autotoc_md572',1,'Ce que le lot ne fait pas'],['../lot-43.html#autotoc_md580',1,'Ce que le lot ne fait pas'],['../lot-66.html#autotoc_md603',1,'Ce que le lot ne fait pas'],['../lot-67.html#autotoc_md611',1,'Ce que le lot ne fait pas'],['../lot-68.html#autotoc_md619',1,'Ce que le lot ne fait pas'],['../lot-76.html#autotoc_md627',1,'Ce que le lot ne fait pas']]],
  ['fait_20pas_20encore_14',['Ce qu&apos;il ne fait pas encore',['../classhmi_1_1GameViewportItem.html#autotoc_md1220',1,'']]],
  ['fait_20pas_20encore_20dans_20l_20éditeur_15',['Ce qui ne se fait pas encore dans l&apos;éditeur',['../guide-usage-editeur.html#autotoc_md1033',1,'']]],
  ['fait_20pas_20et_20pourquoi_16',['Ce que le lot ne fait pas, et pourquoi',['../lot-37.html#autotoc_md552',1,'']]],
  ['fait_20pas_20produire_17',['Ce que le cahier ne fait pas produire',['../lot-87-cahier-assets.html#lot-87-cahier-exclusions',1,'']]],
  ['fait_20sur_20la_20typographie_20pas_20sur_20des_20expressions_20régulières_18',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md515',1,'']]],
  ['fait_20un_20encadrement_20c_20est_20la_20réserve_19',['Ce qui fait un encadrement, c&apos;est la réserve',['../lot-66.html#autotoc_md598',1,'']]],
  ['faite_20',['Comment la classification a été faite',['../lot-78.html#autotoc_md635',1,'']]],
  ['fallait_20l_20écrire_21',['Pourquoi il fallait l&apos;écrire',['../classhmi_1_1GamepadNavigator.html#autotoc_md1216',1,'']]],
  ['familles_20d_20exigences_20sont_20fantômes_20—_20le_20lint_20le_20dit_20désormais_22',['9.1 Cinq familles d&apos;exigences sont fantômes — le lint le dit désormais',['../roadmap.html#autotoc_md946',1,'']]],
  ['fantômes_20—_20le_20lint_20le_20dit_20désormais_23',['9.1 Cinq familles d&apos;exigences sont fantômes — le lint le dit désormais',['../roadmap.html#autotoc_md946',1,'']]],
  ['fausses_20données_24',['Pourquoi un tiret cadratin et non de fausses données',['../classhmi_1_1PendingData.html#autotoc_md1224',1,'']]],
  ['faut_20anticiper_20tant_20que_20rien_20n_20est_20construit_25',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap.html#autotoc_md953',1,'']]],
  ['faut_20pas_20réécrire_26',['Ce qui existe déjà, et qu&apos;il ne faut pas réécrire',['../lot-06.html#autotoc_md344',1,'']]],
  ['faut_20pas_20se_20cacher_27',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md1219',1,'']]],
  ['faute_20de_20données_20à_20valider_28',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md510',1,'']]],
  ['faute_20de_20langue_20commune_29',['Refusé faute de langue commune',['../lot-15.html#autotoc_md420',1,'']]],
  ['fenêtre_30',['fenêtre',['../guide-editeur.html#autotoc_md95',1,'Cadrer une carte plus grande que la fenêtre'],['../lot-editor-13.html',1,'LOT-EDITOR-13 — L&apos;éditeur sans fenêtre'],['../roadmap-editeur.html#autotoc_md1015',1,'LOT-EDITOR-13 — L&apos;éditeur sans fenêtre']]],
  ['fenêtre_20lot_20editor_2013_31',['14. L&apos;éditeur sans fenêtre (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-13&lt;/span&gt;)',['../spec-editeur.html#autotoc_md235',1,'']]],
  ['fermée_32',['7. La revue par vision, contre une liste fermée',['../lot-91-poc.html#autotoc_md731',1,'']]],
  ['feuille_20de_20route_33',['Feuille de route',['../lots.html#autotoc_md908',1,'']]],
  ['feuille_20de_20route_34',['Écarts par rapport au texte de la feuille de route',['../lot-88.html#autotoc_md709',1,'']]],
  ['feuille_20de_20route_20—_20le_20bac_20à_20sable_20de_20tanares_35',['Feuille de route — le bac à sable de Tanares',['../roadmap.html',1,'lots']]],
  ['feuille_20de_20route_20de_20l_20éditeur_20de_20cartes_36',['Feuille de route de l&apos;éditeur de cartes',['../roadmap-editeur.html',1,'']]],
  ['feuille_20de_20route_20disait_20autrement_37',['Ce que le corpus dit, et que la feuille de route disait autrement',['../lot-36.html#autotoc_md539',1,'']]],
  ['feuille_20de_20route_20second_20audit_38',['Texte d&apos;origine (feuille de route, second audit)',['../lot-88.html#autotoc_md713',1,'']]],
  ['feuille_20de_20route_20supposait_20et_20ce_20que_20le_20dépôt_20contenait_39',['feuille de route supposait et ce que le dépôt contenait',['../lot-11.html#autotoc_md382',1,'Ce que la feuille de route supposait, et ce que le dépôt contenait'],['../lot-24.html#autotoc_md493',1,'Ce que la feuille de route supposait, et ce que le dépôt contenait']]],
  ['feuille_20de_20route_20supposait_20et_20qui_20n_20a_20pas_20tenu_40',['Ce que la feuille de route supposait, et qui n&apos;a pas tenu',['../lot-19.html#autotoc_md440',1,'']]],
  ['fiche_41',['1. La fiche',['../spec-rpg.html#autotoc_md291',1,'']]],
  ['fiche_20calcule_20et_20où_42',['Ce que la fiche calcule, et où',['../lot-38.html#autotoc_md561',1,'']]],
  ['fiche_20de_20personnage_43',['LOT-13 — Fiche de personnage',['../lot-13.html',1,'lots']]],
  ['fiche_20de_20personnage_20_3a_20maquette_20et_20interface_44',['LOT-38 — Fiche de personnage : maquette et interface',['../lot-38.html',1,'lots']]],
  ['fiche_20de_20personnage_20maquette_2003_45',['T3.4 — La fiche de personnage (maquette 03)',['../lot-87.html#autotoc_md687',1,'']]],
  ['fiche_20il_20la_20désigne_46',['Le composant ECS ne porte pas la fiche, il la désigne',['../lot-13.html#autotoc_md404',1,'']]],
  ['fichier_47',['fichier',['../AreaOfEffect_8h.html#autotoc_md1123',1,'Hors de ce fichier'],['../GestureScript_8h.html#autotoc_md1178',1,'Le fichier'],['../classhmi_1_1ScreenRouter.html#autotoc_md1228',1,'Pourquoi une énumération et non un nom de fichier'],['../ArenaAnimationDriver_8h.html#autotoc_md1187',1,'Une action, un fichier']]],
  ['fichier_20décide_20et_20que_20le_20guide_20ne_20dit_20pas_48',['Ce que ce fichier décide, et que le Guide ne dit pas',['../EnemyAi_8h.html#autotoc_md1142',1,'']]],
  ['fichier_20nommément_49',['Hors de ce fichier, nommément',['../Attack_8h.html#autotoc_md1128',1,'']]],
  ['fichiers_50',['fichiers',['../guide-conception-qds.html#autotoc_md48',1,'La règle des deux fichiers'],['../guide-rendu.html#autotoc_md161',1,'Les textures depuis fichiers']]],
  ['fichiers_20de_20niveaux_51',['Gérer ses fichiers de niveaux',['../guide-editeur.html#autotoc_md96',1,'']]],
  ['fichiers_20et_20replis_52',['Les textures : atlas procédural, fichiers et replis',['../guide-rendu.html#autotoc_md159',1,'']]],
  ['fiction_20qui_20l_20explique_53',['Personne n&apos;y meurt, et c&apos;est la fiction qui l&apos;explique',['../lot-50.html#autotoc_md586',1,'']]],
  ['figé_20ailleurs_20qu_20en_20dur_54',['Ce qui est figé ailleurs qu&apos;en dur',['../lot-12.html#autotoc_md396',1,'']]],
  ['figurines_20de_20l_20atelier_55',['Les habitants — les figurines de l&apos;atelier',['../roadmap.html#autotoc_md981',1,'']]],
  ['figurines_20du_20bestiaire_20depuis_20le_20texte_20seul_56',['LOT-93 — Atelier des monstres : les figurines du bestiaire, depuis le texte seul',['../lot-93.html',1,'lots']]],
  ['figurines_20du_20character_20compendium_57',['LOT-91 — Atelier des PNJ : les figurines du Character Compendium',['../lot-91.html',1,'lots']]],
  ['filière_20contenu_58',['5. Programme de lots proposé — la filière contenu',['../roadmap.html#autotoc_md924',1,'']]],
  ['fils_59',['fils',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1208',1,'Ce qui traverse la frontière entre les fils'],['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md1195',1,'Les trois temps, et les deux fils']]],
  ['filtrer_20puis_20diffuser_60',['&lt;a class=&quot;el&quot; href=&quot;classcore_1_1Logger.html&quot; title=&quot;core::Logger&quot;&gt;core::Logger&lt;/a&gt; : filtrer puis diffuser',['../guide-journalisation.html#autotoc_md120',1,'']]],
  ['finissent_20les_20messages_61',['Les sinks : où finissent les messages',['../guide-journalisation.html#autotoc_md121',1,'']]],
  ['fins_62',['fins',['../lot-20.html#autotoc_md457',1,'Les trois fins'],['../classcore_1_1CombatState.html#autotoc_md1136',1,'Les trois fins']]],
  ['fitzoom_20worldcamera_20arenacamera_63',['Cadrer une scène : &lt;span class=&quot;tt&quot;&gt;fitZoom&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;worldCamera&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;arenaCamera&lt;/span&gt;',['../guide-rendu.html#autotoc_md153',1,'']]],
  ['fixée_20_3a_20ce_20que_20cela_20achète_64',['Rejouable à graine fixée : ce que cela achète',['../lot-50.html#autotoc_md585',1,'']]],
  ['fixe_65',['fixe',['../guide-boucle.html',1,'Boucle de jeu et pas de temps fixe'],['../guide-boucle.html#autotoc_md38',1,'Le principe du pas de temps fixe']]],
  ['flottante_20_3a_20pourquoi_20l_20égalité_20stricte_20est_20dangereuse_66',['Comparaison flottante : pourquoi l&apos;égalité stricte est dangereuse',['../guide-maths.html#autotoc_md135',1,'']]],
  ['focus_20n_20est_20jamais_20perdu_20de_20vue_67',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md601',1,'']]],
  ['fois_68',['fois',['../lot-34.html#autotoc_md528',1,'Deux unités, converties une seule fois'],['../lot-36.html#autotoc_md538',1,'Le &lt;em&gt;Player&apos;s Guide&lt;/em&gt; dessine ses titres deux fois'],['../lot-10.html#autotoc_md374',1,'Le piège du lot : un coffre ouvert deux fois'],['../lot-32.html#autotoc_md508',1,'Le triangle, et pourquoi chaque arête n&apos;est contrôlée qu&apos;une fois'],['../guide-rendu.html#autotoc_md155',1,'Pourquoi « batcher » plutôt que dessiner un sprite à la fois']]],
  ['fois_20départagée_20par_20une_20règle_20écrite_69',['L&apos;initiative : jetée une fois, départagée par une règle écrite',['../lot-20.html#autotoc_md454',1,'']]],
  ['fois_20de_20plus_70',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md31',1,'']]],
  ['fonctionnelles_71',['fonctionnelles',['../spec-editeur.html#autotoc_md222',1,'1. Exigences fonctionnelles'],['../spec-exigences.html',1,'Exigences non fonctionnelles']]],
  ['fonctions_20libres_72',['Classes plutôt que fonctions libres',['../spec-conventions.html#autotoc_md210',1,'']]],
  ['fond_20et_20la_20frontière_20qu_20elle_20trace_73',['La carte du monde en fond, et la frontière qu&apos;elle trace',['../lot-67.html#autotoc_md607',1,'']]],
  ['fonds_74',['Fonds',['../lot-87-cahier-assets.html#lot-87-cahier-background',1,'']]],
  ['fondue_75',['Les couches, dans une scène fondue',['../CanvasScene_8h.html#autotoc_md1177',1,'']]],
  ['font_20dans_20l_20éditeur_20lot_20editor_2006_76',['15. Les cartes se font dans l&apos;éditeur (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-06&lt;/span&gt;)',['../spec-editeur.html#autotoc_md236',1,'']]],
  ['forcées_20du_20colisée_20—_20libérées_77',['Les 540 cases forcées du Colisée — libérées',['../lot-editor-03.html#autotoc_md1051',1,'']]],
  ['forest_78',['Forest',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md846',1,'Première série proposée — Sindile Forest'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html',1,'Sindile Forest']]],
  ['fork_20purge_20et_20remise_20à_20nu_79',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['format_80',['format',['../spec-niveaux.html',1,'Cartes &amp; format'],['../roadmap.html#autotoc_md965',1,'Règles de format']]],
  ['format_20d_20une_20ligne_20_3a_20core_3a_3aformatlogline_20core_3a_3aformatlogline_81',['Le format d&apos;une ligne : &lt;a class=&quot;el&quot; href=&quot;namespacecore.html#aafa85d91ee91c84b123fff01f147615e&quot; title=&quot;core::formatLogLine&quot;&gt;core::formatLogLine&lt;/a&gt;',['../guide-journalisation.html#autotoc_md125',1,'']]],
  ['format_20de_20carte_20version_3a_203_20multi_20couches_82',['LOT-04 — Format de carte `version: 3`, multi-couches',['../lot-04.html',1,'lots']]],
  ['format_20lot_20editor_2012_83',['10. La garde du format (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)',['../spec-editeur.html#autotoc_md231',1,'']]],
  ['format_20retenu_20json_20liste_20de_20tuiles_20objets_84',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md275',1,'']]],
  ['format_20v4_20et_20sa_20garde_20en_20ci_85',['format v4 et sa garde en CI',['../lot-editor-12.html',1,'LOT-EDITOR-12 — Le format v4 et sa garde en CI'],['../roadmap-editeur.html#autotoc_md1011',1,'LOT-EDITOR-12 — Le format v4 et sa garde en CI']]],
  ['format_20v4_20lot_20editor_2012_86',['Format v4 (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)',['../spec-niveaux.html#autotoc_md274',1,'']]],
  ['format_20v4_20lot_20editor_2012_87',['Depuis le format v4 (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)',['../PlaceAppearance_8h.html#autotoc_md1199',1,'']]],
  ['format_20v4_20lot_20editor_2012_20ex_20lvl_20019_88',['Une case = un type et une pièce (format v4, &lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-LVL-019&lt;/span&gt;)',['../structcore_1_1TileLayer.html#autotoc_md1161',1,'']]],
  ['formatage_20est_20ici_20la_20traduction_20reste_20dehors_89',['Le formatage est ici, la traduction reste dehors',['../structhmi_1_1CharacterSheetContext.html#autotoc_md1203',1,'']]],
  ['forme_90',['3. Mise en forme',['../spec-conventions.html#autotoc_md204',1,'']]],
  ['formes_20de_20la_20colonne_20ca_20disent_20trois_20règles_91',['Les trois formes de la colonne CA disent trois règles',['../lot-34.html#autotoc_md527',1,'']]],
  ['formules_92',['D&apos;où viennent les formules',['../IsoProjection_8h.html#autotoc_md1146',1,'']]],
  ['fort_20levier_20du_20programme_93',['9.3 L&apos;allègement est le geste à plus fort levier du programme',['../roadmap.html#autotoc_md948',1,'']]],
  ['fous_20contre_20la_20perte_20de_20travail_94',['Garde-fous contre la perte de travail',['../guide-editeur.html#autotoc_md94',1,'']]],
  ['fractionne_95',['Le déplacement se fractionne',['../classcore_1_1ActionEconomy.html#autotoc_md1119',1,'']]],
  ['frame_20complète_96',['Assembler la frame complète',['../guide-rendu.html#autotoc_md169',1,'']]],
  ['framerate_20variable_97',['Le piège du framerate variable',['../guide-boucle.html#autotoc_md37',1,'']]],
  ['frames_20sans_20pas_20de_20simulation_20et_20les_20entrées_98',['Les frames sans pas de simulation et les entrées',['../guide-boucle.html#autotoc_md43',1,'']]],
  ['freelands_99',['Freelands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md834',1,'Première série proposée — Republic of Freelands'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html',1,'Republic of Freelands']]],
  ['frontière_100',['Où passe la frontière',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1211',1,'']]],
  ['frontière_20entre_20les_20fils_101',['Ce qui traverse la frontière entre les fils',['../classhmi_1_1ArenaViewportItem.html#autotoc_md1208',1,'']]],
  ['frontière_20qu_20elle_20trace_102',['La carte du monde en fond, et la frontière qu&apos;elle trace',['../lot-67.html#autotoc_md607',1,'']]],
  ['frontière_20simulation_20↔_20rendu_103',['4. Frontière simulation ↔ rendu',['../spec-architecture.html#autotoc_md177',1,'']]],
  ['frontière_20telle_20qu_20elle_20est_20tenue_104',['La frontière, telle qu&apos;elle est tenue',['../spec-interface-ihm.html#autotoc_md265',1,'']]],
  ['fronts_20pas_20seulement_20l_20état_105',['Détecter les fronts, pas seulement l&apos;état',['../guide-entrees.html#autotoc_md101',1,'']]],
  ['fusionnée_20en_20lecture_20ex_20ctrl_20002_106',['La manette : une seconde source, fusionnée en lecture (EX-CTRL-002)',['../guide-entrees.html#autotoc_md103',1,'']]]
];
