var searchData=
[
  ['règle_0',['règle',['../roadmap.html#autotoc_md931',1,'La règle'],['../PieceFootprint_8h.html#autotoc_md1169',1,'La règle']]],
  ['règle_20écrite_1',['L&apos;initiative : jetée une fois, départagée par une règle écrite',['../lot-20.html#autotoc_md455',1,'']]],
  ['règle_20écrites_20là_20où_20on_20les_20lit_2',['Trois décisions de règle, écrites là où on les lit',['../lot-13.html#autotoc_md406',1,'']]],
  ['règle_2012_20empêche_3',['Ce que la règle 12 empêche',['../lot-78.html#autotoc_md637',1,'']]],
  ['règle_20case_20par_20case_4',['La règle, case par case',['../CollisionDerivation_8h.html#autotoc_md1166',1,'']]],
  ['règle_20décidée_20le_2017_20septembre_202026_20décision_20de_20l_20auteur_5',['La règle, décidée le 17 septembre 2026 (&lt;em&gt;décision de l&apos;auteur&lt;/em&gt;)',['../PlaceAppearance_8h.html#autotoc_md1207',1,'']]],
  ['règle_20d_20or_20une_20fois_20de_20plus_6',['La règle d&apos;or, une fois de plus',['../guide-audio.html#autotoc_md31',1,'']]],
  ['règle_20dans_20le_20c_20»_20se_20vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_7',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md403',1,'']]],
  ['règle_20de_20départage_8',['La règle de départage',['../namespacecore.html#autotoc_md1164',1,'']]],
  ['règle_20de_20performance_20à_20respecter_9',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md124',1,'']]],
  ['règle_20de_20superposition_20portée_20par_20l_20écran_20et_20non_20par_20l_20appelant_10',['La règle de superposition, portée par l&apos;écran et non par l&apos;appelant',['../lot-68.html#autotoc_md617',1,'']]],
  ['règle_20des_20deux_20fichiers_11',['La règle des deux fichiers',['../guide-conception-qds.html#autotoc_md48',1,'']]],
  ['règle_20dit_20et_20où_20elle_20est_20écrite_12',['Ce que la règle dit, et où elle est écrite',['../lot-14.html#autotoc_md411',1,'']]],
  ['règle_20du_20manuel_20et_20pourquoi_20elle_20n_20est_20pas_20un_20parcours_20en_20largeur_13',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md1160',1,'']]],
  ['règle_20et_20elle_20ne_20dépend_20pas_20de_20l_20algorithme_14',['Le départage est une règle, et elle ne dépend pas de l&apos;algorithme',['../lot-19.html#autotoc_md442',1,'']]],
  ['règle_20et_20pourquoi_20c_20est_20celle_20du_20jeu_15',['La règle, et pourquoi c&apos;est celle du jeu',['../ExplorationReach_8h.html#autotoc_md1178',1,'']]],
  ['règle_20pas_20un_20hasard_16',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md1161',1,'']]],
  ['règle_20pour_20«_20se_20tenir_20ici_20»_17',['Une seule règle pour « se tenir ici »',['../namespacecore.html#autotoc_md1162',1,'']]],
  ['règle_20qu_20il_20est_20le_20plus_20facile_20d_20implémenter_20de_20travers_18',['Le multiclassage, la règle qu&apos;il est le plus facile d&apos;implémenter de travers',['../lot-43.html#autotoc_md579',1,'']]],
  ['règle_20qui_20gouverne_20cette_20classe_19',['La règle qui gouverne cette classe',['../classhmi_1_1OptionsModel.html#autotoc_md1230',1,'']]],
  ['règle_20vit_20',['Ce que dit le Manuel, et où chaque règle vit',['../Attack_8h.html#autotoc_md1135',1,'']]],
  ['règles_21',['règles',['../lot-91.html#autotoc_md720',1,'Les règles'],['../lot-34.html#autotoc_md528',1,'Les trois formes de la colonne CA disent trois règles']]],
  ['règles_20d_20échelle_20lot_2066_22',['Deux identités, deux règles d&apos;échelle (LOT-66)',['../guide-design-ihm.html#autotoc_md65',1,'']]],
  ['règles_20d20_23',['Règles d20',['../spec-regles-d20.html',1,'specifications']]],
  ['règles_20de_20désignation_20une_20par_20critère_24',['Trois règles de désignation, une par critère',['../lot-10.html#autotoc_md377',1,'']]],
  ['règles_20de_20format_25',['Règles de format',['../roadmap.html#autotoc_md966',1,'']]],
  ['règles_20de_20zone_20des_20treize_20régions_26',['&lt;span class=&quot;tt&quot;&gt;LOT-81&lt;/span&gt; — Descripteurs de terrain et règles de zone des treize régions',['../roadmap.html#lot-81',1,'']]],
  ['règles_20du_20guide_20et_20où_20chacune_20vit_27',['Les règles du Guide, et où chacune vit',['../lot-23.html#autotoc_md486',1,'']]],
  ['règles_20du_20manuel_20et_20où_20chacune_20vit_28',['règles du Manuel et où chacune vit',['../lot-21.html#autotoc_md467',1,'Les règles du Manuel, et où chacune vit'],['../lot-22.html#autotoc_md476',1,'Les règles du Manuel, et où chacune vit']]],
  ['règles_20pour_20durer_29',['5. Cinq règles pour durer',['../roadmap-editeur.html#roadmap-editeur-perennite',1,'']]],
  ['réécrire_30',['Ce qui existe déjà, et qu&apos;il ne faut pas réécrire',['../lot-06.html#autotoc_md345',1,'']]],
  ['réactivité_31',['3. Réactivité',['../spec-controles.html#autotoc_md199',1,'']]],
  ['réactivité_20et_20réglages_20effectifs_32',['8. Taille, réactivité et réglages effectifs',['../spec-interface-ihm.html#autotoc_md263',1,'']]],
  ['réagir_20_3a_20hmi_3a_3ainputstate_20hmi_3a_3ainputstate_33',['Échantillonner plutôt que réagir : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1InputState.html&quot; title=&quot;hmi::InputState&quot;&gt;hmi::InputState&lt;/a&gt;',['../guide-entrees.html#autotoc_md100',1,'']]],
  ['réalisation_20a_20tranché_34',['réalisation a tranché',['../lot-04.html#autotoc_md336',1,'Ce que la réalisation a tranché'],['../lot-05.html#autotoc_md343',1,'Ce que la réalisation a tranché'],['../lot-06.html#autotoc_md350',1,'Ce que la réalisation a tranché'],['../lot-08.html#autotoc_md362',1,'Ce que la réalisation a tranché'],['../lot-32.html#autotoc_md510',1,'Ce que la réalisation a tranché'],['../lot-79.html#autotoc_md642',1,'Ce que la réalisation a tranché']]],
  ['réalisation_20a_20vérifié_20et_20ce_20qu_20elle_20a_20démenti_35',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md502',1,'']]],
  ['récapitulatif_20_3a_20qui_20dépend_20de_20qui_36',['Récapitulatif : qui dépend de qui',['../roadmap.html#autotoc_md937',1,'']]],
  ['réception_20des_20images_20produites_37',['T2.6 — La réception des images produites',['../lot-87.html#autotoc_md681',1,'']]],
  ['réception_20des_20images_20produites_2018_20septembre_202026_38',['La réception des images produites (18 septembre 2026)',['../lot-87.html#lot-87-reception',1,'']]],
  ['récupération_39',['4. Temps, repos et récupération',['../spec-regles-d20.html#autotoc_md282',1,'']]],
  ['récupérer_20le_20projet_40',['1. Récupérer le projet',['../manuel-partager-niveau.html#autotoc_md1117',1,'']]],
  ['récupérer_20les_20cartes_20des_20autres_41',['5. Récupérer les cartes des autres',['../manuel-partager-niveau.html#autotoc_md1121',1,'']]],
  ['rédaction_20a_20tranché_42',['Ce que la rédaction a tranché',['../lot-77.html#autotoc_md632',1,'']]],
  ['réel_20_3a_20sinks_20différents_20en_20développement_20et_20en_20release_43',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md127',1,'']]],
  ['réemploi_20et_20reste_20différé_44',['Réemploi et reste différé',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md792',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md799',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md805',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md811',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md817',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md824',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md830',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md836',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md842',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md848',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md854',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md860',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md866',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md872',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md878',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md885',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md891',1,'Réemploi et reste différé']]],
  ['réemploi_20histoire_20et_20contrôle_20de_20couverture_45',['Réemploi, histoire et contrôle de couverture',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md787',1,'']]],
  ['référence_20canonique_20_3a_20anariel_20étape_20r_46',['4. La référence canonique : Anariel (étape R)',['../lot-91-poc.html#autotoc_md729',1,'']]],
  ['références_20étape_20e1_20à_20la_20main_47',['2. Les références (étape E1, à la main)',['../lot-91-poc.html#autotoc_md727',1,'']]],
  ['références_20communes_20et_20préparation_20régionale_48',['Références communes et préparation régionale',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html',1,'']]],
  ['références_20visuelles_20hors_20git_20et_20mémoire_20versionnée_49',['Références visuelles hors Git et mémoire versionnée',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md784',1,'']]],
  ['références_20visuelles_20inspectées_50',['Références visuelles inspectées',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md790',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md796',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md803',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md809',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md821',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md834',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md882',1,'Références visuelles inspectées']]],
  ['région_20une_20ville_20lot_2094_51',['11. L&apos;écran « Carte » : le monde, une région, une ville (LOT-94)',['../spec-interface-ihm.html#ihm-carte',1,'']]],
  ['région_20ville_52',['LOT-94 — Les images du corpus quittent le dépôt ; l&apos;écran « Carte » revient sur les cartes de l&apos;auteur : monde, région, ville',['../lot-94.html',1,'lots']]],
  ['régionale_53',['Références communes et préparation régionale',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html',1,'']]],
  ['régions_54',['&lt;span class=&quot;tt&quot;&gt;LOT-81&lt;/span&gt; — Descripteurs de terrain et règles de zone des treize régions',['../roadmap.html#lot-81',1,'']]],
  ['régions_20et_20graphe_20de_20cartes_55',['LOT-37 — Atlas des régions et graphe de cartes',['../lot-37.html',1,'lots']]],
  ['régions_20jouées_56',['LOT-CREATION-ASSETS — Produire selon les régions jouées',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html',1,'']]],
  ['régions_20pas_20dix_57',['Treize régions, pas dix',['../lot-37.html#autotoc_md548',1,'']]],
  ['réglages_20effectifs_58',['8. Taille, réactivité et réglages effectifs',['../spec-interface-ihm.html#autotoc_md263',1,'']]],
  ['réglages_20et_20ce_20qu_20ils_20atteignent_59',['Les réglages, et ce qu&apos;ils atteignent',['../guide-ihm-qt.html#autotoc_md115',1,'']]],
  ['régulières_60',['L&apos;extraction se fait sur la typographie, pas sur des expressions régulières',['../lot-33.html#autotoc_md516',1,'']]],
  ['répéter_20ce_20qu_20on_20a_20composé_20_3a_20tampons_20et_20préfabriqués_61',['Répéter ce qu&apos;on a composé : tampons et préfabriqués',['../guide-usage-editeur.html#autotoc_md1033',1,'']]],
  ['réplique_62',['réplique',['../classcore_1_1DialogueRunner.html#autotoc_md1174',1,'Le joueur ne s&apos;arrête que sur une réplique'],['../lot-15.html#autotoc_md420',1,'Le runner : pur, et il ne s&apos;arrête que sur une réplique']]],
  ['réservée_20d11_63',['La hauteur, réservée (D11)',['../CanvasPicking_8h.html#autotoc_md1184',1,'']]],
  ['réserve_64',['Ce qui fait un encadrement, c&apos;est la réserve',['../lot-66.html#autotoc_md599',1,'']]],
  ['résout_65',['résout',['../classhmi_1_1PendingData.html#autotoc_md1232',1,'Le problème que cette classe résout'],['../guide-ecs.html#autotoc_md75',1,'Le problème que l&apos;ECS résout']]],
  ['réutilisation_20cohérence_66',['2. Réutilisation &amp;amp; cohérence',['../spec-editeur.html#autotoc_md223',1,'']]],
  ['révélé_67',['Ce que l&apos;ordre a révélé',['../roadmap.html#autotoc_md934',1,'']]],
  ['révélé_20sur_20l_20état_20du_20dépôt_68',['9. Ce que l&apos;audit a révélé sur l&apos;état du dépôt',['../roadmap.html#autotoc_md946',1,'']]],
  ['rôles_20de_20cadre_20changent_20de_20nom_20et_20c_20est_20le_20cœur_20du_20lot_69',['Les rôles de cadre changent de nom, et c&apos;est le cœur du lot',['../lot-66.html#autotoc_md598',1,'']]],
  ['r_70',['4. La référence canonique : Anariel (étape R)',['../lot-91-poc.html#autotoc_md729',1,'']]],
  ['r01_20—_20reprise_20intégrale_20de_20martpart_20arenarea_20et_20du_20colisée_71',['CE-R01 — Reprise intégrale de Martpart, Arenarea et du Colisée',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-r01-reprise-trois-sites.html',1,'']]],
  ['r02_20—_20refaire_20le_20soldat_20ironhand_72',['CE-R02 — Refaire le soldat Ironhand',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-r02-refonte-ironhand.html',1,'']]],
  ['raccourcis_20de_20l_20éditeur_20_3a_20hmi_3a_3aeditorkeybindings_20editorkeybindings_73',['Les raccourcis de l&apos;éditeur : &lt;a class=&quot;el&quot; href=&quot;classhmi_1_1EditorKeyBindings.html&quot; title=&quot;hmi::EditorKeyBindings&quot;&gt;EditorKeyBindings&lt;/a&gt;',['../guide-entrees.html#autotoc_md105',1,'']]],
  ['racine_20carrée_74',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html#a5f3517fe219407f73a3ed5542091c31c&quot; title=&quot;core::Vector2::lengthSquared&quot;&gt;lengthSquared&lt;/a&gt; : éviter la racine carrée',['../guide-maths.html#autotoc_md131',1,'']]],
  ['raii_20obligatoire_75',['RAII obligatoire',['../spec-conventions.html#autotoc_md211',1,'']]],
  ['raison_76',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md600',1,'']]],
  ['rangée_77',['Le groupe d&apos;une arme n&apos;est pas dans sa rangée',['../lot-34.html#autotoc_md526',1,'']]],
  ['rangs_20de_20guilde_20niveau_20d_20équipe_20et_20quartier_20général_78',['&lt;span class=&quot;tt&quot;&gt;LOT-83&lt;/span&gt; — Compagnie : rangs de Guilde, niveau d&apos;équipe et quartier général',['../roadmap.html#lot-83',1,'']]],
  ['rangs_20et_20contrats_79',['&lt;span class=&quot;tt&quot;&gt;LOT-45&lt;/span&gt; — Guilde des Aventuriers : rangs et contrats',['../roadmap.html#lot-45',1,'']]],
  ['rapport_20au_20texte_20de_20la_20feuille_20de_20route_80',['Écarts par rapport au texte de la feuille de route',['../lot-88.html#autotoc_md710',1,'']]],
  ['rater_81',['Le point à ne pas rater',['../lot-04.html#autotoc_md333',1,'']]],
  ['re_20coder_20le_20moteur_82',['Le problème : éditer une carte sans (re)coder le moteur',['../guide-editeur.html#autotoc_md84',1,'']]],
  ['reconstruire_83',['Éditer un écran sans rien reconstruire',['../guide-ihm-qt.html#autotoc_md111',1,'']]],
  ['rect_20_3a_20le_20rectangle_20aligné_20aux_20axes_84',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Rect.html&quot; title=&quot;core::Rect&quot;&gt;Rect&lt;/a&gt; : le rectangle aligné aux axes',['../guide-maths.html#autotoc_md133',1,'']]],
  ['rectangle_20aligné_20aux_20axes_85',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Rect.html&quot; title=&quot;core::Rect&quot;&gt;Rect&lt;/a&gt; : le rectangle aligné aux axes',['../guide-maths.html#autotoc_md133',1,'']]],
  ['rectangle_20texturé_86',['&lt;a class=&quot;el&quot; href=&quot;structhmi_1_1SpriteQuad.html&quot; title=&quot;hmi::SpriteQuad&quot;&gt;SpriteQuad&lt;/a&gt; : un rectangle texturé',['../guide-rendu.html#autotoc_md156',1,'']]],
  ['refaire_20_3a_20pourquoi_20des_20instantanés_20complets_87',['Annuler/refaire : pourquoi des instantanés complets',['../guide-editeur.html#autotoc_md91',1,'']]],
  ['refaire_20le_20soldat_20ironhand_88',['CE-R02 — Refaire le soldat Ironhand',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-r02-refonte-ironhand.html',1,'']]],
  ['refait_20pas_89',['Ce qu&apos;elle ne refait pas',['../classhmi_1_1CharacterSheetModel.html#autotoc_md1221',1,'']]],
  ['refermée_90',['La planche gravée : une piste ouverte, puis refermée',['../lot-38.html#autotoc_md558',1,'']]],
  ['refondues_91',['Exigences refondues',['../lot-87.html#autotoc_md676',1,'']]],
  ['refondues_20pour_20trois_92',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md610',1,'']]],
  ['refonte_93',['Pourquoi ce lot est un lot d&apos;&lt;b&gt;ajout&lt;/b&gt;, pas une refonte',['../roadmap.html#autotoc_md999',1,'']]],
  ['refonte_20de_20l_20ihm_20sur_20qt_20quick_94',['LOT-86 — Refonte de l&apos;IHM sur Qt Quick',['../lot-86.html',1,'lots']]],
  ['refusé_95',['Un geste refusé',['../GestureScript_8h.html#autotoc_md1188',1,'']]],
  ['refusé_20faute_20de_20langue_20commune_96',['Refusé faute de langue commune',['../lot-15.html#autotoc_md421',1,'']]],
  ['refus_97',['Le montage nomme ses refus',['../lot-50.html#autotoc_md590',1,'']]],
  ['refusait_98',['Trois cas que le livre écrit et qu&apos;un schéma refusait',['../lot-34.html#autotoc_md527',1,'']]],
  ['refuse_99',['Ce que le chargement refuse',['../lot-15.html#autotoc_md419',1,'']]],
  ['regardant_20l_20écran_100',['Trois défauts d&apos;agencement, trouvés en regardant l&apos;écran',['../lot-68.html#autotoc_md619',1,'']]],
  ['regarder_101',['Vérifier une interface sans la regarder',['../guide-ihm-qt.html#autotoc_md116',1,'']]],
  ['regroupement_20d_20intention_102',['Le regroupement d&apos;intention',['../roadmap.html#autotoc_md933',1,'']]],
  ['rejouable_103',['Rejouable',['../classcore_1_1DialogueRunner.html#autotoc_md1175',1,'']]],
  ['rejouable_20à_20graine_20fixée_20_3a_20ce_20que_20cela_20achète_104',['Rejouable à graine fixée : ce que cela achète',['../lot-50.html#autotoc_md586',1,'']]],
  ['relève_20dessus_105',['La maquette : cinq planches, et ce qu&apos;on relève dessus',['../lot-38.html#autotoc_md556',1,'']]],
  ['release_106',['Bootstrap réel : sinks différents en développement et en Release',['../guide-journalisation.html#autotoc_md127',1,'']]],
  ['relecture_20des_20livres_107',['Écarté à la relecture des livres',['../roadmap.html#autotoc_md943',1,'']]],
  ['relecture_20du_2014_20septembre_202026_108',['4bis. Ce que les deux livres imposent au moteur — relecture du 14 septembre 2026',['../roadmap.html#autotoc_md923',1,'']]],
  ['relecture_20n_20aurait_20pas_20vu_109',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md393',1,'']]],
  ['relevé_110',['relevé',['../guide-entrees.html#autotoc_md102',1,'Le cycle d&apos;un relevé'],['../lot-87-cahier-assets.html#autotoc_md658',1,'Vérifier le relevé']]],
  ['relevé_20en_20chemin_111',['Relevé en chemin',['../lot-15.html#autotoc_md425',1,'Relevé en chemin'],['../lot-19.html#autotoc_md451',1,'Relevé en chemin'],['../lot-50.html#autotoc_md591',1,'Relevé en chemin']]],
  ['relevé_20en_20chemin_20_3a_20la_20case_20d_20une_20créature_20coûte_20double_112',['Relevé en chemin : la case d&apos;une créature coûte double',['../lot-20.html#autotoc_md462',1,'']]],
  ['relevé_20provisoire_113',['Les blocs de Tanares (&lt;span class=&quot;tt&quot;&gt;LOT-46&lt;/span&gt;, relevé provisoire)',['../lot-93.html#autotoc_md758',1,'']]],
  ['relevée_114',['La palette relevée',['../lot-87.html#autotoc_md675',1,'']]],
  ['relevée_20pas_20choisie_115',['La palette est relevée, pas choisie',['../lot-66.html#autotoc_md597',1,'']]],
  ['relief_116',['3. Dresser le relief',['../guide-usage-editeur.html#autotoc_md1027',1,'']]],
  ['relief_20haut_20se_20désigne_20par_20son_20pied_117',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md1183',1,'']]],
  ['remarques_118',['Remarques',['../manuel-telecharger.html#autotoc_md1125',1,'']]],
  ['remise_20à_20nu_119',['LOT-01 — Fork, purge et remise à nu',['../lot-01.html',1,'lots']]],
  ['remplacent_20la_20charte_20parchemin_20pixel_120',['Pourquoi les maquettes remplacent la charte parchemin pixel',['../lot-87.html#autotoc_md662',1,'']]],
  ['remplacer_121',['remplacer',['../lot-editor-14.html',1,'LOT-EDITOR-14 — Renommer et remplacer'],['../roadmap-editeur.html#autotoc_md1019',1,'LOT-EDITOR-14 — Renommer et remplacer']]],
  ['remplacer_20changer_20de_20planche_122',['Renommer, remplacer, changer de planche',['../guide-usage-editeur.html#autotoc_md1034',1,'']]],
  ['remplacer_20lot_20editor_2014_123',['17. Renommer et remplacer (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-14&lt;/span&gt;)',['../spec-editeur.html#autotoc_md238',1,'']]],
  ['rencontre_20dit_20qui_20jamais_20où_124',['Une rencontre dit QUI, jamais OÙ',['../lot-18.html#autotoc_md435',1,'']]],
  ['rencontres_20et_20créatures_125',['&lt;span class=&quot;tt&quot;&gt;LOT-41&lt;/span&gt; — Peuplement : rencontres et créatures',['../roadmap.html#lot-41',1,'']]],
  ['rend_20ces_20exigences_20autre_20chose_20que_20des_20intentions_126',['Ce qui rend ces exigences autre chose que des intentions',['../spec-interface-ihm.html#autotoc_md268',1,'']]],
  ['rend_20vérifiable_127',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md430',1,'']]],
  ['rendu_128',['rendu',['../spec-architecture.html#autotoc_md177',1,'4. Frontière simulation ↔ rendu'],['../spec-architecture.html#autotoc_md179',1,'6. Abstraction de rendu'],['../spec-rendu-technique.html#autotoc_md290',1,'6. Surface de rendu'],['../guide-ihm-qt.html#autotoc_md113',1,'La surface de rendu']]],
  ['rendu_202d_129',['2. Rendu 2D',['../spec-rendu-technique.html#autotoc_md286',1,'']]],
  ['rendu_202d_20_3a_20de_20la_20scène_20à_20l_20écran_130',['Rendu 2D : de la scène à l&apos;écran',['../guide-rendu.html',1,'guide']]],
  ['rendu_20cible_20technique_131',['Rendu &amp;amp; cible technique',['../spec-rendu-technique.html',1,'specifications']]],
  ['rendu_20top_20down_20et_20tri_20par_20y_132',['LOT-07 — Rendu top-down et tri par Y',['../lot-07.html',1,'lots']]],
  ['renommer_20et_20remplacer_133',['Renommer et remplacer',['../lot-editor-14.html',1,'LOT-EDITOR-14 — Renommer et remplacer'],['../roadmap-editeur.html#autotoc_md1019',1,'LOT-EDITOR-14 — Renommer et remplacer']]],
  ['renommer_20et_20remplacer_20lot_20editor_2014_134',['17. Renommer et remplacer (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-14&lt;/span&gt;)',['../spec-editeur.html#autotoc_md238',1,'']]],
  ['renommer_20remplacer_20changer_20de_20planche_135',['Renommer, remplacer, changer de planche',['../guide-usage-editeur.html#autotoc_md1034',1,'']]],
  ['renversement_20du_20milieu_20du_20lot_20et_20pourquoi_20il_20valait_20mieux_136',['Le renversement du milieu du lot, et pourquoi il valait mieux',['../lot-76.html#autotoc_md623',1,'']]],
  ['renversement_20est_20assumé_20pas_20subi_137',['Le renversement est assumé, pas subi',['../lot-66.html#autotoc_md603',1,'']]],
  ['repère_138',['repère',['../guide-maths.html#autotoc_md134',1,'Conventions d&apos;unités et de repère'],['../IsoProjection_8h.html#autotoc_md1156',1,'Le repère'],['../ExplorationSession_8h.html#autotoc_md1180',1,'Le repère']]],
  ['repère_20de_20cases_139',['Deux vues, un repère de cases',['../CanvasPicking_8h.html#autotoc_md1182',1,'']]],
  ['repères_20d_20échelle_140',['2. Repères d&apos;échelle',['../spec-exploration.html#autotoc_md252',1,'']]],
  ['repaire_141',['CE-01 — Martpart, Myr et la piste du repaire',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-01-martpart-myr.html',1,'']]],
  ['replis_142',['Les textures : atlas procédural, fichiers et replis',['../guide-rendu.html#autotoc_md159',1,'']]],
  ['repos_20dans_20le_20monde_143',['&lt;span class=&quot;tt&quot;&gt;LOT-75&lt;/span&gt; — Campement et repos dans le monde',['../roadmap.html#lot-75',1,'']]],
  ['repos_20et_20récupération_144',['4. Temps, repos et récupération',['../spec-regles-d20.html#autotoc_md282',1,'']]],
  ['représentation_20des_20cartes_145',['1. Représentation des cartes',['../spec-niveaux.html#autotoc_md274',1,'']]],
  ['reprendre_20sa_20partie_20dans_20la_20capitale_20_3a_20sauvegarde_20riche_146',['LOT-17 — Reprendre sa partie dans la Capitale : sauvegarde riche',['../roadmap.html#lot-17',1,'']]],
  ['reprise_20des_20cinq_20pnj_20du_20poc_147',['T00 — Socle et reprise des cinq PNJ du PoC',['../md_Lot_2LOT-CREATION-ASSETS_2tache-00-socle-pilote-pnj.html',1,'']]],
  ['reprise_20des_20maquettes_20supprimées_148',['La direction artistique, reprise des maquettes supprimées',['../lot-86.html#autotoc_md646',1,'']]],
  ['reprise_20intégrale_20de_20martpart_20arenarea_20et_20du_20colisée_149',['CE-R01 — Reprise intégrale de Martpart, Arenarea et du Colisée',['../md_Lot_2LOT-CREATION-ASSETS_2tache-ce-r01-reprise-trois-sites.html',1,'']]],
  ['reproductibilité_150',['4. Portabilité &amp;amp; reproductibilité',['../spec-exigences.html#autotoc_md245',1,'']]],
  ['republic_20of_20freelands_151',['Republic of Freelands',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md835',1,'Première série proposée — Republic of Freelands'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html',1,'Republic of Freelands']]],
  ['resources_2012_152',['Resources (12)',['../cahiertest.html#autotoc_md13',1,'']]],
  ['respecter_153',['Une règle de performance à respecter',['../guide-journalisation.html#autotoc_md124',1,'']]],
  ['ressource_20revient_154',['Quand une ressource revient',['../classcore_1_1ActionEconomy.html#autotoc_md1127',1,'']]],
  ['ressources_155',['9. Gestion des ressources',['../spec-architecture.html#autotoc_md182',1,'']]],
  ['ressources_20de_20table_20virtuelle_20ajoutées_20le_207_20septembre_202026_156',['Les ressources de table virtuelle (ajoutées le 7 septembre 2026)',['../roadmap.html#autotoc_md916',1,'']]],
  ['restantes_157',['8. Décisions prises et questions restantes',['../roadmap.html#autotoc_md941',1,'']]],
  ['reste_20à_20brancher_158',['Comment on retrouve ce qu&apos;il reste à brancher',['../classhmi_1_1PendingData.html#autotoc_md1234',1,'']]],
  ['reste_20ce_20qui_20commande_20est_20unique_159',['Architecture de l&apos;information : ce qui informe reste, ce qui commande est unique',['../guide-design-ihm.html#autotoc_md61',1,'']]],
  ['reste_20dehors_160',['Le formatage est ici, la traduction reste dehors',['../structhmi_1_1CharacterSheetContext.html#autotoc_md1212',1,'']]],
  ['reste_20différé_161',['reste différé',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md792',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md799',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md805',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md811',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2magocracy-of-mage-tower_2preparation.html#autotoc_md817',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md824',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2penumbra_2preparation.html#autotoc_md830',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md836',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2seashores_2preparation.html#autotoc_md842',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2sindile-forest_2preparation.html#autotoc_md848',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2storm-islands_2preparation.html#autotoc_md854',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2stravian-domains_2preparation.html#autotoc_md860',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2taii-maku-city-states_2preparation.html#autotoc_md866',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2theocracy-of-kepesh_2preparation.html#autotoc_md872',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2tsvetan_2preparation.html#autotoc_md878',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md885',1,'Réemploi et reste différé'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2yama_2preparation.html#autotoc_md891',1,'Réemploi et reste différé']]],
  ['reste_20entier_20après_20la_20sortie_20du_20pixel_20art_162',['Pourquoi le facteur reste entier après la sortie du pixel art',['../guide-design-ihm.html#autotoc_md66',1,'']]],
  ['reste_20entier_20pour_20une_20autre_20raison_163',['Le facteur d&apos;agrandissement reste entier, pour une autre raison',['../lot-66.html#autotoc_md600',1,'']]],
  ['reste_20hors_20du_20lot_20nommément_164',['reste hors du lot nommément',['../lot-11.html#autotoc_md389',1,'Ce qui reste hors du lot, nommément'],['../lot-15.html#autotoc_md426',1,'Ce qui reste hors du lot, nommément'],['../lot-19.html#autotoc_md449',1,'Ce qui reste hors du lot, nommément'],['../lot-20.html#autotoc_md463',1,'Ce qui reste hors du lot, nommément'],['../lot-21.html#autotoc_md472',1,'Ce qui reste hors du lot, nommément'],['../lot-22.html#autotoc_md482',1,'Ce qui reste hors du lot, nommément'],['../lot-23.html#autotoc_md491',1,'Ce qui reste hors du lot, nommément'],['../lot-24.html#autotoc_md498',1,'Ce qui reste hors du lot, nommément'],['../lot-50.html#autotoc_md593',1,'Ce qui reste hors du lot, nommément'],['../lot-92.html#autotoc_md740',1,'Ce qui reste hors du lot, nommément'],['../lot-94.html#autotoc_md764',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-01.html#autotoc_md1042',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-02.html#autotoc_md1048',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-03.html#autotoc_md1055',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-04.html#autotoc_md1061',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-05.html#autotoc_md1067',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-06.html#autotoc_md1073',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-07.html#autotoc_md1079',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-08.html#autotoc_md1085',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-09.html#autotoc_md1091',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-12.html#autotoc_md1098',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-13.html#autotoc_md1104',1,'Ce qui reste hors du lot, nommément'],['../lot-editor-14.html#autotoc_md1110',1,'Ce qui reste hors du lot, nommément']]],
  ['reste_20tracé_20à_20l_20ancienne_20et_20ce_20n_20est_20pas_20un_20oubli_165',['L&apos;accentué reste tracé à l&apos;ancienne, et ce n&apos;est pas un oubli',['../lot-76.html#autotoc_md626',1,'']]],
  ['restent_20tracés_20et_20ex_20ihm_20075_20avec_20eux_166',['Les ornements restent tracés, et &lt;span class=&quot;tt&quot;&gt;EX-IHM-075&lt;/span&gt; avec eux',['../spec-interface-ihm.html#autotoc_md267',1,'']]],
  ['restes_20de_20code_167',['3. Assets, scripts et restes de code',['../lot-88.html#autotoc_md708',1,'']]],
  ['restitution_20n_20est_20pas_20un_20journal_20c_20est_20une_20exigence_168',['La restitution n&apos;est pas un journal, c&apos;est une exigence',['../lot-12.html#autotoc_md396',1,'']]],
  ['restylés_169',['T3.9 — Pause, dialogue, marchand, journal : restylés',['../lot-87.html#autotoc_md693',1,'']]],
  ['retenu_20—_20et_20pourquoi_20il_20n_20est_20pas_20«_20une_20seule_20hmilib_20»_170',['Le découpage retenu — et pourquoi il n&apos;est pas « une seule &lt;span class=&quot;tt&quot;&gt;HmiLib&lt;/span&gt; »',['../lot-02.html#autotoc_md319',1,'']]],
  ['retenu_20json_20liste_20de_20tuiles_20objets_171',['Format retenu (JSON, liste de tuiles-objets)',['../spec-niveaux.html#autotoc_md276',1,'']]],
  ['retenue_172',['9. La découpe d&apos;une planche retenue',['../lot-91-poc.html#autotoc_md734',1,'']]],
  ['retiré_173',['Ce que le &lt;span class=&quot;tt&quot;&gt;LOT-67&lt;/span&gt; a retiré',['../guide-ecrans.html#autotoc_md72',1,'']]],
  ['retiré_20du_20code_174',['Ce qui a été retiré du code',['../lot-67.html#autotoc_md609',1,'']]],
  ['retirées_175',['retirées',['../spec-retirees.html',1,'Exigences retirées'],['../spec-architecture.html#arch-retirees',1,'Exigences retirées'],['../spec-controles.html#ctrl-retirees',1,'Exigences retirées'],['../spec-editeur.html#edit-retirees',1,'Exigences retirées'],['../spec-exigences.html#nfr-retirees',1,'Exigences retirées'],['../spec-gameplay.html#gp-retirees',1,'Exigences retirées'],['../spec-interface-ihm.html#ihm-retirees',1,'Exigences retirées'],['../spec-niveaux.html#lvl-retirees',1,'Exigences retirées'],['../spec-rendu-technique.html#ren-retirees',1,'Exigences retirées']]],
  ['retirées_20pour_20douze_20refondues_20pour_20trois_176',['Les seize exigences : retirées pour douze, refondues pour trois',['../lot-67.html#autotoc_md610',1,'']]],
  ['retirer_20ce_20qui_20ne_20sert_20plus_177',['Phase 5 — retirer ce qui ne sert plus',['../lot-87.html#autotoc_md697',1,'']]],
  ['retoucher_20en_20masse_20sans_20la_20souris_178',['Retoucher en masse, sans la souris',['../guide-usage-editeur.html#autotoc_md1032',1,'']]],
  ['retour_20est_20pur_20et_20c_20est_20ce_20qui_20le_20rend_20vérifiable_179',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md430',1,'']]],
  ['retrait_20de_20l_20héritage_20_3a_20code_20assets_20et_20spécifications_180',['LOT-88 — Retrait de l&apos;héritage : code, assets et spécifications',['../lot-88.html',1,'lots']]],
  ['retraits_181',['Retraits',['../roadmap.html#autotoc_md985',1,'']]],
  ['retrouve_20ce_20qu_20il_20reste_20à_20brancher_182',['Comment on retrouve ce qu&apos;il reste à brancher',['../classhmi_1_1PendingData.html#autotoc_md1234',1,'']]],
  ['revient_183',['Quand une ressource revient',['../classcore_1_1ActionEconomy.html#autotoc_md1127',1,'']]],
  ['revient_20sur_20les_20cartes_20de_20l_20auteur_20_3a_20monde_20région_20ville_184',['LOT-94 — Les images du corpus quittent le dépôt ; l&apos;écran « Carte » revient sur les cartes de l&apos;auteur : monde, région, ville',['../lot-94.html',1,'lots']]],
  ['revue_20huit_20«_20oui_20»_185',['La revue (huit « oui »)',['../lot-93.html#autotoc_md751',1,'']]],
  ['revue_20neuf_20«_20oui_20»_186',['La revue (neuf « oui »)',['../lot-91.html#autotoc_md721',1,'']]],
  ['revue_20par_20vision_20contre_20une_20liste_20fermée_187',['7. La revue par vision, contre une liste fermée',['../lot-91-poc.html#autotoc_md732',1,'']]],
  ['riche_188',['LOT-17 — Reprendre sa partie dans la Capitale : sauvegarde riche',['../roadmap.html#lot-17',1,'']]],
  ['rien_20n_20est_20construit_189',['10. Ce qu&apos;il faut anticiper, tant que rien n&apos;est construit',['../roadmap.html#autotoc_md954',1,'']]],
  ['rien_20reconstruire_190',['Éditer un écran sans rien reconstruire',['../guide-ihm-qt.html#autotoc_md111',1,'']]],
  ['risque_20_3a_20l_20angle_200_2062_20en_20pixel_20art_191',['Risque : l&apos;angle 0,62 en pixel art',['../lot-92.html#autotoc_md742',1,'']]],
  ['risques_20et_20pistes_20écartées_192',['8. Risques et pistes écartées',['../roadmap-editeur.html#roadmap-editeur-risques',1,'']]],
  ['robustesse_193',['5. Robustesse',['../spec-exigences.html#autotoc_md246',1,'']]],
  ['robustesse_20et_20confort_20d_20édition_194',['6. Robustesse et confort d&apos;édition',['../spec-editeur.html#autotoc_md227',1,'']]],
  ['route_195',['route',['../lot-88.html#autotoc_md710',1,'Écarts par rapport au texte de la feuille de route'],['../lot-11.html#autotoc_md388',1,'Décisions prises en route'],['../lot-21.html#autotoc_md471',1,'Décisions prises en route'],['../lot-22.html#autotoc_md481',1,'Décisions prises en route'],['../lot-23.html#autotoc_md490',1,'Décisions prises en route'],['../lot-24.html#autotoc_md497',1,'Décisions prises en route'],['../lots.html#autotoc_md909',1,'Feuille de route']]],
  ['route_20—_20le_20bac_20à_20sable_20de_20tanares_196',['Feuille de route — le bac à sable de Tanares',['../roadmap.html',1,'lots']]],
  ['route_20de_20l_20éditeur_20de_20cartes_197',['Feuille de route de l&apos;éditeur de cartes',['../roadmap-editeur.html',1,'']]],
  ['route_20disait_20autrement_198',['Ce que le corpus dit, et que la feuille de route disait autrement',['../lot-36.html#autotoc_md540',1,'']]],
  ['route_20second_20audit_199',['Texte d&apos;origine (feuille de route, second audit)',['../lot-88.html#autotoc_md714',1,'']]],
  ['route_20supposait_20et_20ce_20que_20le_20dépôt_20contenait_200',['route supposait et ce que le dépôt contenait',['../lot-11.html#autotoc_md383',1,'Ce que la feuille de route supposait, et ce que le dépôt contenait'],['../lot-24.html#autotoc_md494',1,'Ce que la feuille de route supposait, et ce que le dépôt contenait']]],
  ['route_20supposait_20et_20qui_20n_20a_20pas_20tenu_201',['Ce que la feuille de route supposait, et qui n&apos;a pas tenu',['../lot-19.html#autotoc_md441',1,'']]],
  ['routeur_20et_20la_20pile_20d_20écrans_202',['Le routeur et la pile d&apos;écrans',['../guide-ecrans.html#autotoc_md69',1,'']]],
  ['rpg_203',['RPG',['../lot-88.html#autotoc_md707',1,'2. Le modèle de carte ne porte plus que le RPG'],['../lot-08.html',1,'LOT-08 — Vocabulaire de tuiles RPG'],['../lot-32.html',1,'LOT-32 — Schémas de données RPG'],['../lot-67.html',1,'LOT-67 — Menus et vocabulaire d&apos;un RPG'],['../lot-68.html',1,'LOT-68 — Le châssis des écrans du RPG']]],
  ['rpg_2081_204',['Rpg (81)',['../cahiertest.html#autotoc_md14',1,'']]],
  ['rpg_20de_20la_20spécification_205',['LOT-77 — La moitié RPG de la spécification',['../lot-77.html',1,'lots']]],
  ['rpg_20lot_2068_206',['9. Le châssis des écrans du RPG (LOT-68)',['../spec-interface-ihm.html#autotoc_md264',1,'']]],
  ['rules_20est_20attesté_20pas_20saisi_207',['Le complément des &lt;em&gt;Basic Rules&lt;/em&gt; est attesté, pas saisi',['../lot-30.html#autotoc_md503',1,'']]],
  ['runner_20_3a_20pur_20et_20il_20ne_20s_20arrête_20que_20sur_20une_20réplique_208',['Le runner : pur, et il ne s&apos;arrête que sur une réplique',['../lot-15.html#autotoc_md420',1,'']]],
  ['runtime_203_209',['Runtime (3)',['../cahiertest.html#autotoc_md26',1,'']]]
];
