var searchData=
[
  ['vérifié_0',['Livré, et vérifié',['../lot-09.html#autotoc_md367',1,'']]],
  ['vérifié_20et_20ce_20qu_20elle_20a_20démenti_1',['Ce que la réalisation a vérifié, et ce qu&apos;elle a démenti',['../lot-30.html#autotoc_md501',1,'']]],
  ['vérifié_20le_2013_20septembre_202026_2',['Où en est la phase 2 — vérifié le 13 septembre 2026',['../lot-87.html#autotoc_md682',1,'']]],
  ['vérifiée_3',['Acceptation, telle que vérifiée',['../lot-94.html#autotoc_md765',1,'']]],
  ['vérifiable_4',['L&apos;aller-retour est PUR, et c&apos;est ce qui le rend vérifiable',['../lot-18.html#autotoc_md429',1,'']]],
  ['vérification_5',['Vérification',['../lot-88.html#autotoc_md712',1,'']]],
  ['vérification_6',['3. Qualité &amp;amp; vérification',['../spec-exigences.html#autotoc_md243',1,'']]],
  ['vérifie_20et_20pourquoi_20il_20s_20auto_20teste_7',['Ce que le contrôle vérifie, et pourquoi il s&apos;auto-teste',['../lot-30.html#autotoc_md503',1,'']]],
  ['vérifie_20pas_8',['Ce qu&apos;elle ne vérifie pas',['../namespacecore.html#autotoc_md1154',1,'']]],
  ['vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_9',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md402',1,'']]],
  ['vérifier_20le_20relevé_10',['Vérifier le relevé',['../lot-87-cahier-assets.html#autotoc_md657',1,'']]],
  ['vérifier_20une_20interface_20sans_20la_20regarder_11',['Vérifier une interface sans la regarder',['../guide-ihm-qt.html#autotoc_md116',1,'']]],
  ['vérité_20pour_20«_20peut_20on_20se_20tenir_20ici_20»_12',['vérité pour « peut on se tenir ici »',['../lot-19.html#autotoc_md447',1,'Une seule source de vérité pour « peut-on se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md1130',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['v1_20étape_20e2_20bloc_20a_13',['3. Le style commun v1 (étape E2, bloc A)',['../lot-91-poc.html#autotoc_md727',1,'']]],
  ['v2_14',['v2',['../lot-87-cahier-assets.html',1,'LOT-87 — Cahier des assets de la charte v2'],['../lot-87.html#autotoc_md670',1,'T2.1 — La charte v2'],['../lot-87.html#autotoc_md681',1,'T2.7 — Les briques de la charte v2']]],
  ['v2_20et_20intégration_20des_20maquettes_15',['LOT-87 — Charte v2 et intégration des maquettes',['../lot-87.html',1,'lots']]],
  ['v2_20et_20matière_20première_16',['Phase 2 — charte v2 et matière première',['../lot-87.html#autotoc_md669',1,'']]],
  ['v4_20et_20sa_20garde_20en_20ci_17',['v4 et sa garde en CI',['../lot-editor-12.html',1,'LOT-EDITOR-12 — Le format v4 et sa garde en CI'],['../roadmap-editeur.html#autotoc_md1011',1,'LOT-EDITOR-12 — Le format v4 et sa garde en CI']]],
  ['v4_20lot_20editor_2012_18',['v4 LOT EDITOR 12',['../PlaceAppearance_8h.html#autotoc_md1199',1,'Depuis le format v4 (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)'],['../spec-niveaux.html#autotoc_md274',1,'Format v4 (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)']]],
  ['v4_20lot_20editor_2012_20ex_20lvl_20019_19',['Une case = un type et une pièce (format v4, &lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-LVL-019&lt;/span&gt;)',['../structcore_1_1TileLayer.html#autotoc_md1161',1,'']]],
  ['va_20le_20geste_20',['Où va le geste',['../BrushGesture_8h.html#autotoc_md1172',1,'']]],
  ['va_20où_21',['va où',['../ArenaSceneComposer_8h.html#autotoc_md1189',1,'Ce qui va où'],['../WorldSceneComposer_8h.html#autotoc_md1200',1,'Ce qui va où']]],
  ['vaincu_20est_20un_20drapeau_20de_20monde_20pas_20un_20booléen_22',['Un ennemi vaincu est un drapeau de monde, pas un booléen',['../lot-18.html#autotoc_md431',1,'']]],
  ['valait_20mieux_23',['Le renversement du milieu du lot, et pourquoi il valait mieux',['../lot-76.html#autotoc_md622',1,'']]],
  ['valeur_20de_20règle_20dans_20le_20c_20»_20se_20vérifie_20sur_20le_20diff_20pas_20sur_20l_20intention_24',['« Aucune valeur de règle dans le C++ » se vérifie sur le diff, pas sur l&apos;intention',['../lot-13.html#autotoc_md402',1,'']]],
  ['valeur_20jamais_20dessus_25',['Un seuil de corps se pose sous la valeur, jamais dessus',['../lot-36.html#autotoc_md542',1,'']]],
  ['validateur_20s_20auto_20teste_20faute_20de_20données_20à_20valider_26',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md510',1,'']]],
  ['validation_27',['Validation',['../guide-niveaux.html#autotoc_md146',1,'']]],
  ['validation_28',['Capacités, branches et validation',['../md_Lot_2LOT-CREATION-ASSETS_2epic.html#autotoc_md780',1,'']]],
  ['valider_29',['Le validateur s&apos;auto-teste, faute de données à valider',['../lot-32.html#autotoc_md510',1,'']]],
  ['valider_20avant_20d_20écrire_20jamais_20l_20inverse_30',['Enregistrer : valider avant d&apos;écrire, jamais l&apos;inverse',['../guide-editeur.html#autotoc_md93',1,'']]],
  ['variable_31',['Le piège du framerate variable',['../guide-boucle.html#autotoc_md37',1,'']]],
  ['vector2_20_3a_20un_20point_20ou_20une_20direction_20dans_20le_20monde_32',['&lt;a class=&quot;el&quot; href=&quot;structcore_1_1Vector2.html&quot; title=&quot;core::Vector2&quot;&gt;Vector2&lt;/a&gt; : un point ou une direction dans le monde',['../guide-maths.html#autotoc_md130',1,'']]],
  ['verdict_2016_20septembre_33',['Verdict (16 septembre)',['../lot-91-poc.html#autotoc_md736',1,'']]],
  ['verdict_20bloquant_34',['Verdict bloquant',['../md_Lot_2LOT-CREATION-ASSETS_2tache-01-carte-test-textures.html#autotoc_md897',1,'']]],
  ['verdict_20et_20ce_20qu_20il_20déclenche_35',['10. Le verdict, et ce qu&apos;il déclenche',['../lot-91-poc.html#autotoc_md734',1,'']]],
  ['version_200_200_201_36',['version 0 0 1',['../lot-93.html#autotoc_md755',1,'Les trois de la version 0.0.1'],['../roadmap.html#lot-28',1,'LOT-28 — Audio, effets et version &lt;span class=&quot;tt&quot;&gt;0.0.1&lt;/span&gt;']]],
  ['version_3a_203_20multi_20couches_37',['LOT-04 — Format de carte `version: 3`, multi-couches',['../lot-04.html',1,'lots']]],
  ['versionné_38',['1. Le corpus n&apos;est pas versionné',['../roadmap.html#autotoc_md912',1,'']]],
  ['versionnée_39',['Références visuelles hors Git et mémoire versionnée',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md783',1,'']]],
  ['vertical_20slice_40',['vertical slice',['../spec-vision.html#autotoc_md304',1,'Hors périmètre (&lt;em&gt;vertical slice&lt;/em&gt;)'],['../roadmap.html#autotoc_md934',1,'Le chemin critique jusqu&apos;au &lt;em&gt;vertical slice&lt;/em&gt;'],['../roadmap.html#lot-27',1,'LOT-27 — La Capitale : contenu du &lt;em&gt;vertical slice&lt;/em&gt;'],['../spec-vision.html#autotoc_md302',1,'Objectifs (&lt;em&gt;vertical slice&lt;/em&gt;)']]],
  ['victoire_20l_20acquiert_41',['Seule une victoire l&apos;acquiert',['../lot-18.html#autotoc_md432',1,'']]],
  ['vidé_20n_20est_20plus_20une_20cible_42',['Un coffre vidé n&apos;est plus une cible',['../lot-10.html#autotoc_md375',1,'']]],
  ['vidéo_43',['Pourquoi journaliser dans un jeu vidéo',['../guide-journalisation.html#autotoc_md118',1,'']]],
  ['viennent_20les_20formules_44',['D&apos;où viennent les formules',['../IsoProjection_8h.html#autotoc_md1146',1,'']]],
  ['vigilance_45',['Points de vigilance',['../lot-02.html#autotoc_md320',1,'']]],
  ['ville_46',['ville',['../lot-94.html',1,'LOT-94 — Les images du corpus quittent le dépôt ; l&apos;écran « Carte » revient sur les cartes de l&apos;auteur : monde, région, ville'],['../roadmap-editeur.html#lot-editor-09',1,'LOT-EDITOR-09 — Le monde : onglets, portails, ville']]],
  ['ville_20lot_2094_47',['11. L&apos;écran « Carte » : le monde, une région, une ville (LOT-94)',['../spec-interface-ihm.html#ihm-carte',1,'']]],
  ['virtuelle_20ajoutées_20le_207_20septembre_202026_48',['Les ressources de table virtuelle (ajoutées le 7 septembre 2026)',['../roadmap.html#autotoc_md915',1,'']]],
  ['vision_20contre_20une_20liste_20fermée_49',['7. La revue par vision, contre une liste fermée',['../lot-91-poc.html#autotoc_md731',1,'']]],
  ['vision_20périmètre_50',['Vision &amp;amp; périmètre',['../spec-vision.html',1,'specifications']]],
  ['visuelle_20_3a_20sortir_20de_20l_20identité_20pixel_20art_51',['LOT-66 — Charte visuelle : sortir de l&apos;identité pixel art',['../lot-66.html',1,'lots']]],
  ['visuelle_20des_20écrans_20du_20jeu_52',['7. Identité visuelle des écrans du jeu',['../spec-interface-ihm.html#autotoc_md261',1,'']]],
  ['visuelles_53',['Identités visuelles',['../spec-vision.html#autotoc_md300',1,'']]],
  ['visuelles_20hors_20git_20et_20mémoire_20versionnée_54',['Références visuelles hors Git et mémoire versionnée',['../md_Lot_2LOT-CREATION-ASSETS_2preparation-regionale.html#autotoc_md783',1,'']]],
  ['visuelles_20inspectées_55',['visuelles inspectées',['../md_Lot_2LOT-CREATION-ASSETS_2regions_2central-empire_2preparation.html#autotoc_md789',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2darkall_2preparation.html#autotoc_md795',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2imperial-benenet_2preparation.html#autotoc_md802',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2kingdom-of-kolbjorn_2preparation.html#autotoc_md808',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2mystical-wasteland_2preparation.html#autotoc_md820',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2republic-of-freelands_2preparation.html#autotoc_md833',1,'Références visuelles inspectées'],['../md_Lot_2LOT-CREATION-ASSETS_2regions_2undertanares_2preparation.html#autotoc_md881',1,'Références visuelles inspectées']]],
  ['vit_56',['vit',['../Attack_8h.html#autotoc_md1126',1,'Ce que dit le Manuel, et où chaque règle vit'],['../lot-23.html#autotoc_md485',1,'Les règles du Guide, et où chacune vit'],['../lot-21.html#autotoc_md466',1,'Les règles du Manuel, et où chacune vit'],['../lot-22.html#autotoc_md475',1,'Les règles du Manuel, et où chacune vit']]],
  ['vocabulaire_20_3a_20«_20niveau_20»_20devient_20«_20carte_20»_20partout_57',['Le vocabulaire : « niveau » devient « carte », partout',['../lot-67.html#autotoc_md610',1,'']]],
  ['vocabulaire_20d_20un_20rpg_58',['LOT-67 — Menus et vocabulaire d&apos;un RPG',['../lot-67.html',1,'lots']]],
  ['vocabulaire_20de_20base_20_3a_20gpu_20swap_20chain_20back_20buffer_59',['Vocabulaire de base : GPU, swap chain, back buffer',['../guide-rendu.html#autotoc_md149',1,'']]],
  ['vocabulaire_20de_20tuiles_20rpg_60',['LOT-08 — Vocabulaire de tuiles RPG',['../lot-08.html',1,'lots']]],
  ['vocabulaire_20des_20cases_61',['&lt;a class=&quot;el&quot; href=&quot;namespacecore.html#ace99a1be913e6294e42e9ebb145eb875&quot; title=&quot;core::TileType&quot;&gt;core::TileType&lt;/a&gt; : le vocabulaire des cases',['../guide-niveaux.html#autotoc_md139',1,'']]],
  ['voient_20pas_62',['Deux arrondis qui ne se voient pas',['../lot-12.html#autotoc_md393',1,'']]],
  ['voir_20aussi_63',['Voir aussi',['../guide-audio.html#autotoc_md35',1,'Voir aussi'],['../guide-boucle.html#autotoc_md45',1,'Voir aussi'],['../guide-conception-qds.html#autotoc_md59',1,'Voir aussi'],['../guide-design-ihm.html#autotoc_md67',1,'Voir aussi'],['../guide-ecrans.html#autotoc_md74',1,'Voir aussi'],['../guide-ecs.html#autotoc_md83',1,'Voir aussi'],['../guide-editeur.html#autotoc_md97',1,'Voir aussi'],['../guide-entrees.html#autotoc_md107',1,'Voir aussi'],['../guide-ihm-qt.html#autotoc_md117',1,'Voir aussi'],['../guide-journalisation.html#autotoc_md129',1,'Voir aussi'],['../guide-maths.html#autotoc_md136',1,'Voir aussi'],['../guide-niveaux.html#autotoc_md148',1,'Voir aussi'],['../guide-rendu.html#autotoc_md170',1,'Voir aussi']]],
  ['voisinage_20est_20déclaré_20et_20c_20est_20écrit_64',['Le voisinage est déclaré, et c&apos;est écrit',['../lot-37.html#autotoc_md550',1,'']]],
  ['voit_65',['voit',['../lot-67.html#autotoc_md606',1,'Ce que le joueur voit'],['../lot-68.html#autotoc_md614',1,'Ce que le joueur voit'],['../guide-rendu.html#autotoc_md162',1,'Ce qui manque se voit']]],
  ['voit_20_3a_20le_20culling_66',['Ne dessiner que ce qui se voit : le culling',['../guide-rendu.html#autotoc_md167',1,'']]],
  ['voit_20n_20est_20pas_20ce_20qui_20bloque_67',['Couches : ce qu&apos;on voit n&apos;est pas ce qui bloque',['../guide-niveaux.html#autotoc_md142',1,'']]],
  ['volume_20_3a_20de_20l_20écran_20des_20options_20au_20moteur_68',['Le volume : de l&apos;écran des options au moteur',['../guide-audio.html#autotoc_md33',1,'']]],
  ['votre_20carte_69',['4. Publier votre carte',['../manuel-partager-niveau.html#autotoc_md1111',1,'']]],
  ['vous_20cache_70',['Ce que le projet vous montre, et ce qu&apos;il vous cache',['../guide-conception-qds.html#autotoc_md47',1,'']]],
  ['vous_20montre_20et_20ce_20qu_20il_20vous_20cache_71',['Ce que le projet vous montre, et ce qu&apos;il vous cache',['../guide-conception-qds.html#autotoc_md47',1,'']]],
  ['vous_20pouvez_20importer_72',['Les modules que vous pouvez importer',['../guide-conception-qds.html#autotoc_md55',1,'']]],
  ['voyage_20et_20carte_20du_20monde_73',['&lt;span class=&quot;tt&quot;&gt;LOT-42&lt;/span&gt; — Voyage et carte du monde',['../roadmap.html#lot-42',1,'']]],
  ['vraiment_20et_20qu_20il_20ne_20faut_20pas_20se_20cacher_74',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md1219',1,'']]],
  ['vu_75',['Le défaut que les tests ont trouvé, et que la relecture n&apos;aurait pas vu',['../lot-12.html#autotoc_md392',1,'']]],
  ['vue_76',['Le focus n&apos;est jamais perdu de vue',['../lot-66.html#autotoc_md601',1,'']]],
  ['vue_20de_20jeu_20et_20la_20session_20qui_20lui_20survit_77',['La vue de jeu et la session qui lui survit',['../guide-ecrans.html#autotoc_md70',1,'']]],
  ['vue_20et_20zones_20d_20effet_78',['LOT-22 — Portée, ligne de vue et zones d&apos;effet',['../lot-22.html',1,'lots']]],
  ['vues_20_3a_20core_3a_3aview_79',['Les vues : core::View&amp;lt;Components...&amp;gt;',['../guide-ecs.html#autotoc_md81',1,'']]],
  ['vues_20un_20repère_20de_20cases_80',['Deux vues, un repère de cases',['../CanvasPicking_8h.html#autotoc_md1173',1,'']]]
];
