var searchData=
[
  ['s_20applique_20quand_0',['Ce qui s&apos;applique quand',['../classhmi_1_1OptionsModel.html#autotoc_md122',1,'']]],
  ['s_20arrête_20que_20sur_20une_20réplique_1',['Le joueur ne s&apos;arrête que sur une réplique',['../classcore_1_1DialogueRunner.html#autotoc_md57',1,'']]],
  ['s_20y_20retrouver_2',['S&apos;y retrouver',['../index.html#autotoc_md1',1,'']]],
  ['sans_20héros_20unique_3',['Sans héros unique',['../classcore_1_1CombatState.html#autotoc_md25',1,'']]],
  ['scène_20fondue_4',['Les couches, dans une scène fondue',['../CanvasScene_8h.html#autotoc_md69',1,'']]],
  ['scène_20que_20le_20jeu_5',['La même scène que le jeu',['../CanvasScene_8h.html#autotoc_md68',1,'']]],
  ['se_20cacher_6',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md119',1,'']]],
  ['se_20désigne_20par_20son_20pied_7',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md66',1,'']]],
  ['se_20fractionne_8',['Le déplacement se fractionne',['../classcore_1_1ActionEconomy.html#autotoc_md6',1,'']]],
  ['se_20tenir_20ici_20»_9',['se tenir ici »',['../namespacecore.html#autotoc_md43',1,'Une seule règle pour « se tenir ici »'],['../classcore_1_1BattleGrid.html#autotoc_md17',1,'Une seule source de vérité pour « peut-on se tenir ici »']]],
  ['segment_10',['Ce qui coupe un segment',['../LineOfSight_8h.html#autotoc_md37',1,'']]],
  ['septembre_202026_20décision_20de_20l_20auteur_11',['La règle, décidée le 17 septembre 2026 (&lt;em&gt;décision de l&apos;auteur&lt;/em&gt;)',['../PlaceAppearance_8h.html#autotoc_md96',1,'']]],
  ['session_20à_20part_12',['Pourquoi une session à part',['../ExplorationSession_8h.html#autotoc_md62',1,'']]],
  ['seule_20et_20par_20instantané_13',['Lecture seule, et par instantané',['../ArenaSceneComposer_8h.html#autotoc_md87',1,'']]],
  ['seule_20règle_20pour_20«_20se_20tenir_20ici_20»_14',['Une seule règle pour « se tenir ici »',['../namespacecore.html#autotoc_md43',1,'']]],
  ['seule_20source_20de_20vérité_20pour_20«_20peut_20on_20se_20tenir_20ici_20»_15',['Une seule source de vérité pour « peut-on se tenir ici »',['../classcore_1_1BattleGrid.html#autotoc_md17',1,'']]],
  ['signaux_16',['Signaux',['../classhmi_1_1CombatModel.html#autotoc_md110',1,'']]],
  ['singleton_20comme_20la_20partie_17',['Un singleton, comme la partie',['../classhmi_1_1EncounterModel.html#autotoc_md114',1,'']]],
  ['son_20intérêt_18',['Pure, et c&apos;est tout son intérêt',['../classcore_1_1DialogueRunner.html#autotoc_md56',1,'']]],
  ['son_20pied_19',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md66',1,'']]],
  ['source_20de_20vérité_20pour_20«_20peut_20on_20se_20tenir_20ici_20»_20',['Une seule source de vérité pour « peut-on se tenir ici »',['../classcore_1_1BattleGrid.html#autotoc_md17',1,'']]],
  ['soustraction_21',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md27',1,'']]],
  ['statistique_20n_20est_20stockée_20ici_22',['Aucune statistique n&apos;est stockée ici',['../structcore_1_1Inventory.html#autotoc_md59',1,'']]],
  ['stockée_20ici_23',['Aucune statistique n&apos;est stockée ici',['../structcore_1_1Inventory.html#autotoc_md59',1,'']]],
  ['structure_20de_20champs_24',['Pourquoi une table de chaînes, et non une structure de champs',['../structhmi_1_1CharacterSheetContext.html#autotoc_md102',1,'']]],
  ['suit_20les_20gestes_20lot_20editor_2003_20ex_20edit_20064_20ex_20edit_20065_25',['La collision suit les gestes (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-03&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-EDIT-064&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-EDIT-065&lt;/span&gt;)',['../classcore_1_1LevelDraft.html#autotoc_md48',1,'']]],
  ['sur_20la_20grille_20_3a_20la_20moitié_20d_20une_20case_26',['Sur la grille : la moitié d&apos;une case',['../AreaOfEffect_8h.html#autotoc_md8',1,'']]],
  ['sur_20une_20réplique_27',['Le joueur ne s&apos;arrête que sur une réplique',['../classcore_1_1DialogueRunner.html#autotoc_md57',1,'']]],
  ['symétrie_20par_20construction_28',['La symétrie, par construction',['../LineOfSight_8h.html#autotoc_md36',1,'']]]
];
