var searchData=
[
  ['règle_0',['La règle',['../PieceFootprint_8h.html#autotoc_md47',1,'']]],
  ['règle_20case_20par_20case_1',['La règle, case par case',['../CollisionDerivation_8h.html#autotoc_md44',1,'']]],
  ['règle_20décidée_20le_2017_20septembre_202026_20décision_20de_20l_20auteur_2',['La règle, décidée le 17 septembre 2026 (&lt;em&gt;décision de l&apos;auteur&lt;/em&gt;)',['../PlaceAppearance_8h.html#autotoc_md89',1,'']]],
  ['règle_20de_20départage_3',['La règle de départage',['../namespacecore.html#autotoc_md42',1,'']]],
  ['règle_20du_20manuel_20et_20pourquoi_20elle_20n_20est_20pas_20un_20parcours_20en_20largeur_4',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md38',1,'']]],
  ['règle_20et_20pourquoi_20c_20est_20celle_20du_20jeu_5',['La règle, et pourquoi c&apos;est celle du jeu',['../ExplorationReach_8h.html#autotoc_md56',1,'']]],
  ['règle_20pas_20un_20hasard_6',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md39',1,'']]],
  ['règle_20pour_20«_20se_20tenir_20ici_20»_7',['Une seule règle pour « se tenir ici »',['../namespacecore.html#autotoc_md40',1,'']]],
  ['règle_20qui_20gouverne_20cette_20classe_8',['La règle qui gouverne cette classe',['../classhmi_1_1OptionsModel.html#autotoc_md113',1,'']]],
  ['règle_20vit_9',['Ce que dit le Manuel, et où chaque règle vit',['../Attack_8h.html#autotoc_md13',1,'']]],
  ['référence_20du_20code_10',['Référence du code',['../index.html',1,'']]],
  ['réplique_11',['Le joueur ne s&apos;arrête que sur une réplique',['../classcore_1_1DialogueRunner.html#autotoc_md52',1,'']]],
  ['réservée_20d11_12',['La hauteur, réservée (D11)',['../CanvasPicking_8h.html#autotoc_md62',1,'']]],
  ['résout_13',['Le problème que cette classe résout',['../classhmi_1_1PendingData.html#autotoc_md115',1,'']]],
  ['refait_20pas_14',['Ce qu&apos;elle ne refait pas',['../classhmi_1_1CharacterSheetModel.html#autotoc_md104',1,'']]],
  ['refusé_15',['Un geste refusé',['../GestureScript_8h.html#autotoc_md66',1,'']]],
  ['rejouable_16',['Rejouable',['../classcore_1_1DialogueRunner.html#autotoc_md53',1,'']]],
  ['relief_20haut_20se_20désigne_20par_20son_20pied_17',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md61',1,'']]],
  ['rendu_20de_20texte_18',['Une image engendrée, pas un rendu de texte',['../MaquetteTokens_8h.html#autotoc_md87',1,'']]],
  ['repère_19',['repère',['../IsoProjection_8h.html#autotoc_md34',1,'Le repère'],['../ExplorationSession_8h.html#autotoc_md58',1,'Le repère']]],
  ['repère_20de_20cases_20',['Deux vues, un repère de cases',['../CanvasPicking_8h.html#autotoc_md60',1,'']]],
  ['ressource_20revient_21',['Quand une ressource revient',['../classcore_1_1ActionEconomy.html#autotoc_md5',1,'']]],
  ['reste_20à_20brancher_22',['Comment on retrouve ce qu&apos;il reste à brancher',['../classhmi_1_1PendingData.html#autotoc_md117',1,'']]],
  ['reste_20dehors_23',['Le formatage est ici, la traduction reste dehors',['../structhmi_1_1CharacterSheetContext.html#autotoc_md95',1,'']]],
  ['retrouve_20ce_20qu_20il_20reste_20à_20brancher_24',['Comment on retrouve ce qu&apos;il reste à brancher',['../classhmi_1_1PendingData.html#autotoc_md117',1,'']]],
  ['retrouver_25',['S&apos;y retrouver',['../index.html#autotoc_md1',1,'']]],
  ['revient_26',['Quand une ressource revient',['../classcore_1_1ActionEconomy.html#autotoc_md5',1,'']]]
];
