var searchData=
[
  ['règle_0',['La règle',['../PieceFootprint_8h.html#autotoc_md55',1,'']]],
  ['règle_20case_20par_20case_1',['La règle, case par case',['../CollisionDerivation_8h.html#autotoc_md52',1,'']]],
  ['règle_20décidée_20le_2017_20septembre_202026_20décision_20de_20l_20auteur_2',['La règle, décidée le 17 septembre 2026 (&lt;em&gt;décision de l&apos;auteur&lt;/em&gt;)',['../PlaceAppearance_8h.html#autotoc_md107',1,'']]],
  ['règle_20de_20départage_3',['La règle de départage',['../namespacecore.html#autotoc_md50',1,'']]],
  ['règle_20du_20manuel_20et_20pourquoi_20elle_20n_20est_20pas_20un_20parcours_20en_20largeur_4',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md46',1,'']]],
  ['règle_20en_20trois_20temps_5',['La règle, en trois temps',['../FigureResolver_8h.html#autotoc_md96',1,'']]],
  ['règle_20et_20pourquoi_20c_20est_20celle_20du_20jeu_6',['La règle, et pourquoi c&apos;est celle du jeu',['../ExplorationReach_8h.html#autotoc_md72',1,'']]],
  ['règle_20pas_20un_20hasard_7',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md47',1,'']]],
  ['règle_20pour_20«_20se_20tenir_20ici_20»_8',['Une seule règle pour « se tenir ici »',['../namespacecore.html#autotoc_md48',1,'']]],
  ['règle_20qui_20gouverne_20cette_20classe_9',['La règle qui gouverne cette classe',['../classhmi_1_1OptionsModel.html#autotoc_md134',1,'']]],
  ['règle_20vit_10',['Ce que dit le Manuel, et où chaque règle vit',['../Attack_8h.html#autotoc_md13',1,'']]],
  ['référence_20du_20code_11',['Référence du code',['../index.html',1,'']]],
  ['réplique_12',['Le joueur ne s&apos;arrête que sur une réplique',['../classcore_1_1DialogueRunner.html#autotoc_md67',1,'']]],
  ['réservée_20d11_13',['La hauteur, réservée (D11)',['../CanvasPicking_8h.html#autotoc_md79',1,'']]],
  ['résolu_20d_20un_20lieu_20lot_20124_14',['Le catalogue résolu d&apos;un lieu (&lt;span class=&quot;tt&quot;&gt;LOT-124&lt;/span&gt;)',['../ScenePieceManifest_8h.html#autotoc_md62',1,'']]],
  ['résout_15',['Le problème que cette classe résout',['../classhmi_1_1PendingData.html#autotoc_md137',1,'']]],
  ['redit_20pas_16',['Ce qu&apos;elle ne redit pas',['../PartyDeployment_8h.html#autotoc_md45',1,'']]],
  ['refait_20et_20ce_20qu_20elle_20ne_20refait_20pas_17',['Ce qu&apos;une image refait, et ce qu&apos;elle ne refait pas',['../WorldSceneRenderer_8h.html#autotoc_md113',1,'']]],
  ['refait_20pas_18',['refait pas',['../classhmi_1_1CharacterSheetModel.html#autotoc_md121',1,'Ce qu&apos;elle ne refait pas'],['../WorldSceneRenderer_8h.html#autotoc_md113',1,'Ce qu&apos;une image refait, et ce qu&apos;elle ne refait pas']]],
  ['refusé_19',['Un geste refusé',['../GestureScript_8h.html#autotoc_md86',1,'']]],
  ['refusé_20et_20dit_20',['Ce qui est refusé, et dit',['../MeshFile_8h.html#autotoc_md60',1,'']]],
  ['rejouable_21',['Rejouable',['../classcore_1_1DialogueRunner.html#autotoc_md68',1,'']]],
  ['relief_20haut_20se_20désigne_20par_20son_20pied_22',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md78',1,'']]],
  ['rencontre_23',['La zone d&apos;une rencontre',['../PartyDeployment_8h.html#autotoc_md43',1,'']]],
  ['rendu_20de_20l_20éditeur_20aussi_20lot_201002_24',['Le rendu de l&apos;éditeur aussi (&lt;span class=&quot;tt&quot;&gt;LOT-1002&lt;/span&gt;)',['../WorldSceneRenderer_8h.html#autotoc_md114',1,'']]],
  ['rendu_20de_20texte_25',['Une image engendrée, pas un rendu de texte',['../MaquetteTokens_8h.html#autotoc_md104',1,'']]],
  ['repère_26',['repère',['../IsoProjection_8h.html#autotoc_md36',1,'Le repère'],['../ExplorationSession_8h.html#autotoc_md74',1,'Le repère']]],
  ['repère_20de_20cases_27',['Deux vues, un repère de cases',['../CanvasPicking_8h.html#autotoc_md77',1,'']]],
  ['repère_20de_20la_20vue_28',['Le repère de la vue',['../IsoView_8h.html#autotoc_md100',1,'']]],
  ['ressource_20revient_29',['Quand une ressource revient',['../classcore_1_1ActionEconomy.html#autotoc_md5',1,'']]],
  ['reste_20à_20brancher_30',['Comment on retrouve ce qu&apos;il reste à brancher',['../classhmi_1_1PendingData.html#autotoc_md139',1,'']]],
  ['reste_20dehors_31',['Le formatage est ici, la traduction reste dehors',['../structhmi_1_1CharacterSheetContext.html#autotoc_md118',1,'']]],
  ['retrouve_20ce_20qu_20il_20reste_20à_20brancher_32',['Comment on retrouve ce qu&apos;il reste à brancher',['../classhmi_1_1PendingData.html#autotoc_md139',1,'']]],
  ['retrouver_33',['S&apos;y retrouver',['../index.html#autotoc_md1',1,'']]],
  ['revient_34',['Quand une ressource revient',['../classcore_1_1ActionEconomy.html#autotoc_md5',1,'']]],
  ['rien_20d_20autre_35',['Un ordre, et rien d&apos;autre',['../Party_8h.html#autotoc_md70',1,'']]]
];
