var searchData=
[
  ['par_20case_0',['La règle, case par case',['../CollisionDerivation_8h.html#autotoc_md52',1,'']]],
  ['par_20construction_1',['La symétrie, par construction',['../LineOfSight_8h.html#autotoc_md38',1,'']]],
  ['par_20instantané_20comme_20l_20arène_2',['Par instantané, comme l&apos;arène',['../WorldSceneComposer_8h.html#autotoc_md97',1,'']]],
  ['par_20qstr_3',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md124',1,'']]],
  ['par_20son_20pied_4',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md73',1,'']]],
  ['parcours_20en_20largeur_5',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md46',1,'']]],
  ['part_6',['Pourquoi une session à part',['../ExplorationSession_8h.html#autotoc_md68',1,'']]],
  ['partie_7',['Un singleton, comme la partie',['../classhmi_1_1EncounterModel.html#autotoc_md111',1,'']]],
  ['pas_8',['pas',['../classcore_1_1BattleGrid.html#autotoc_md19',1,'Ce qu&apos;elle ne fait pas'],['../PartyDeployment_8h.html#autotoc_md45',1,'Ce qu&apos;elle ne redit pas'],['../classhmi_1_1CharacterSheetModel.html#autotoc_md103',1,'Ce qu&apos;elle ne refait pas'],['../namespacecore.html#autotoc_md49',1,'Ce qu&apos;elle ne vérifie pas'],['../classhmi_1_1CombatModel.html#autotoc_md105',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1WorldModel.html#autotoc_md127',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1PartyModel.html#autotoc_md120',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne tient pas'],['../classhmi_1_1GamepadNavigator.html#autotoc_md114',1,'Ce qu&apos;il fait, et ce qu&apos;il ne fait pas'],['../classhmi_1_1ScreenRouter.html#autotoc_md125',1,'Ce qu&apos;il n&apos;est pas'],['../structcore_1_1ExplorationSnapshot.html#autotoc_md27',1,'Ce qu&apos;il porte, et ce qu&apos;il ne porte pas'],['../WorldSceneRenderer_8h.html#autotoc_md98',1,'Ce qu&apos;une image refait, et ce qu&apos;elle ne refait pas'],['../EnemyAi_8h.html#autotoc_md30',1,'Ce que ce fichier décide, et que le Guide ne dit pas'],['../Arena_8h.html#autotoc_md11',1,'Ce que l&apos;arène est, et ce qu&apos;elle n&apos;est pas'],['../CombatPreview_8h.html#autotoc_md20',1,'Une prévisualisation qui ne ment pas']]],
  ['pas_20dans_20un_20fichier_9',['Pourquoi dans le code, et pas dans un fichier',['../MaquettePalette_8h.html#autotoc_md89',1,'']]],
  ['pas_20encore_10',['Ce qu&apos;il ne fait pas encore',['../classhmi_1_1GameViewportItem.html#autotoc_md117',1,'']]],
  ['pas_20les_20couleurs_20de_20l_20atlas_20procédural_11',['Pourquoi pas les couleurs de l&apos;atlas procédural',['../MaquettePalette_8h.html#autotoc_md90',1,'']]],
  ['pas_20par_20qstr_12',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md124',1,'']]],
  ['pas_20se_20cacher_13',['Ce qui change vraiment, et qu&apos;il ne faut pas se cacher',['../classhmi_1_1GameViewportItem.html#autotoc_md116',1,'']]],
  ['pas_20un_20hasard_14',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md47',1,'']]],
  ['pas_20un_20indice_15',['Une place, pas un indice',['../classcore_1_1TurnOrder.html#autotoc_md51',1,'']]],
  ['pas_20un_20parcours_20en_20largeur_16',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md46',1,'']]],
  ['pas_20un_20rendu_20de_20texte_17',['Une image engendrée, pas un rendu de texte',['../MaquetteTokens_8h.html#autotoc_md91',1,'']]],
  ['pas_20une_20poursuite_18',['Pourquoi une trace, et pas une poursuite',['../FollowTrail_8h.html#autotoc_md70',1,'']]],
  ['pas_20une_20soustraction_19',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md28',1,'']]],
  ['passe_20la_20frontière_20',['Où passe la frontière',['../classhmi_1_1CharacterSheetModel.html#autotoc_md102',1,'']]],
  ['passent_20pas_20par_20qstr_21',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md124',1,'']]],
  ['peut_20on_20se_20tenir_20ici_20»_22',['Une seule source de vérité pour « peut-on se tenir ici »',['../classcore_1_1BattleGrid.html#autotoc_md17',1,'']]],
  ['pièce_20format_20v4_20lot_20editor_2012_20ex_20lvl_20019_23',['Une case = un type et une pièce (format v4, &lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;EX-LVL-019&lt;/span&gt;)',['../structcore_1_1TileLayer.html#autotoc_md56',1,'']]],
  ['pied_24',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md73',1,'']]],
  ['pipeline_20et_20pas_20une_20soustraction_25',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md28',1,'']]],
  ['place_20pas_20un_20indice_26',['Une place, pas un indice',['../classcore_1_1TurnOrder.html#autotoc_md51',1,'']]],
  ['places_27',['Les places',['../namespacecore.html#autotoc_md42',1,'']]],
  ['places_20du_20groupe_28',['Les places du groupe',['../PartyDeployment_8h.html#autotoc_md44',1,'']]],
  ['planche_29',['Adressé comme une planche',['../MaquetteTokens_8h.html#autotoc_md92',1,'']]],
  ['plutôt_20qu_20une_20image_20manquante_30',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md57',1,'']]],
  ['plutôt_20que_20la_20table_20brute_31',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md104',1,'']]],
  ['point_32',['Déterministe, et c&apos;est le point',['../namespacecore.html#autotoc_md58',1,'']]],
  ['porte_20et_20ce_20qu_20il_20ne_20porte_20pas_33',['Ce qu&apos;il porte, et ce qu&apos;il ne porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md27',1,'']]],
  ['porte_20pas_34',['Ce qu&apos;il porte, et ce qu&apos;il ne porte pas',['../structcore_1_1ExplorationSnapshot.html#autotoc_md27',1,'']]],
  ['pose_20écrit_35',['Ce que la pose écrit',['../Stamps_8h.html#autotoc_md83',1,'']]],
  ['pour_20«_20peut_20on_20se_20tenir_20ici_20»_36',['Une seule source de vérité pour « peut-on se tenir ici »',['../classcore_1_1BattleGrid.html#autotoc_md17',1,'']]],
  ['pour_20«_20se_20tenir_20ici_20»_37',['Une seule règle pour « se tenir ici »',['../namespacecore.html#autotoc_md48',1,'']]],
  ['pourquoi_20c_20est_20celle_20du_20jeu_38',['La règle, et pourquoi c&apos;est celle du jeu',['../ExplorationReach_8h.html#autotoc_md67',1,'']]],
  ['pourquoi_20ceux_20là_20ne_20passent_20pas_20par_20qstr_39',['Pourquoi ceux-là ne passent pas par &lt;span class=&quot;tt&quot;&gt;qsTr&lt;/span&gt;',['../namespacehmi.html#autotoc_md124',1,'']]],
  ['pourquoi_20dans_20le_20code_20et_20pas_20dans_20un_20fichier_40',['Pourquoi dans le code, et pas dans un fichier',['../MaquettePalette_8h.html#autotoc_md89',1,'']]],
  ['pourquoi_20des_20propriétés_20nommées_20plutôt_20que_20la_20table_20brute_41',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md104',1,'']]],
  ['pourquoi_20elle_20n_20est_20pas_20un_20parcours_20en_20largeur_42',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md46',1,'']]],
  ['pourquoi_20il_20fallait_20l_20écrire_43',['Pourquoi il fallait l&apos;écrire',['../classhmi_1_1GamepadNavigator.html#autotoc_md113',1,'']]],
  ['pourquoi_20pas_20les_20couleurs_20de_20l_20atlas_20procédural_44',['Pourquoi pas les couleurs de l&apos;atlas procédural',['../MaquettePalette_8h.html#autotoc_md90',1,'']]],
  ['pourquoi_20un_20marqueur_20plutôt_20qu_20une_20image_20manquante_45',['Pourquoi un marqueur plutôt qu&apos;une image manquante',['../namespacecore.html#autotoc_md57',1,'']]],
  ['pourquoi_20un_20pipeline_20et_20pas_20une_20soustraction_46',['Pourquoi un pipeline, et pas une soustraction',['../Damage_8h.html#autotoc_md28',1,'']]],
  ['pourquoi_20un_20tiret_20cadratin_20et_20non_20de_20fausses_20données_47',['Pourquoi un tiret cadratin et non de fausses données',['../classhmi_1_1PendingData.html#autotoc_md122',1,'']]],
  ['pourquoi_20une_20énumération_20et_20non_20un_20nom_20de_20fichier_48',['Pourquoi une énumération et non un nom de fichier',['../classhmi_1_1ScreenRouter.html#autotoc_md126',1,'']]],
  ['pourquoi_20une_20file_49',['Pourquoi une file',['../CombatCues_8h.html#autotoc_md86',1,'']]],
  ['pourquoi_20une_20liste_50',['Pourquoi une liste',['../classcore_1_1ActionEconomy.html#autotoc_md4',1,'']]],
  ['pourquoi_20une_20session_20à_20part_51',['Pourquoi une session à part',['../ExplorationSession_8h.html#autotoc_md68',1,'']]],
  ['pourquoi_20une_20table_20de_20chaînes_20et_20non_20une_20structure_20de_20champs_52',['Pourquoi une table de chaînes, et non une structure de champs',['../structhmi_1_1CharacterSheetContext.html#autotoc_md99',1,'']]],
  ['pourquoi_20une_20trace_20et_20pas_20une_20poursuite_53',['Pourquoi une trace, et pas une poursuite',['../FollowTrail_8h.html#autotoc_md70',1,'']]],
  ['pourquoi_20une_20zone_20et_20non_20la_20carte_20entière_54',['Pourquoi une zone, et non la carte entière',['../CombatZone_8h.html#autotoc_md66',1,'']]],
  ['poursuite_55',['Pourquoi une trace, et pas une poursuite',['../FollowTrail_8h.html#autotoc_md70',1,'']]],
  ['prévisualisation_20qui_20ne_20ment_20pas_56',['Une prévisualisation qui ne ment pas',['../CombatPreview_8h.html#autotoc_md20',1,'']]],
  ['prend_57',['Ce que le découpage prend',['../Stamps_8h.html#autotoc_md82',1,'']]],
  ['problème_20que_20cette_20classe_20résout_58',['Le problème que cette classe résout',['../classhmi_1_1PendingData.html#autotoc_md121',1,'']]],
  ['procédural_59',['Pourquoi pas les couleurs de l&apos;atlas procédural',['../MaquettePalette_8h.html#autotoc_md90',1,'']]],
  ['propriétés_20de_20zone_60',['Les propriétés de zone',['../classcore_1_1BattleGrid.html#autotoc_md18',1,'']]],
  ['propriétés_20nommées_20plutôt_20que_20la_20table_20brute_61',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md104',1,'']]],
  ['pure_20et_20c_20est_20tout_20son_20intérêt_62',['Pure, et c&apos;est tout son intérêt',['../classcore_1_1DialogueRunner.html#autotoc_md61',1,'']]]
];
