var searchData=
[
  ['décidée_20le_2017_20septembre_202026_20décision_20de_20l_20auteur_0',['La règle, décidée le 17 septembre 2026 (&lt;em&gt;décision de l&apos;auteur&lt;/em&gt;)',['../PlaceAppearance_8h.html#autotoc_md91',1,'']]],
  ['décide_20et_20que_20le_20guide_20ne_20dit_20pas_1',['Ce que ce fichier décide, et que le Guide ne dit pas',['../EnemyAi_8h.html#autotoc_md29',1,'']]],
  ['décide_20pas_2',['décide pas',['../classhmi_1_1ArenaModel.html#autotoc_md99',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas'],['../classhmi_1_1WorldModel.html#autotoc_md123',1,'Ce qu&apos;elle tient, et ce qu&apos;elle ne décide pas']]],
  ['décide_20quoi_3',['Qui décide quoi',['../classhmi_1_1AssetGalleryItem.html#autotoc_md104',1,'']]],
  ['décision_20de_20l_20auteur_4',['La règle, décidée le 17 septembre 2026 (&lt;em&gt;décision de l&apos;auteur&lt;/em&gt;)',['../PlaceAppearance_8h.html#autotoc_md91',1,'']]],
  ['découpage_20prend_5',['Ce que le découpage prend',['../Stamps_8h.html#autotoc_md72',1,'']]],
  ['départage_6',['La règle de départage',['../namespacecore.html#autotoc_md42',1,'']]],
  ['départage_20est_20une_20règle_20pas_20un_20hasard_7',['Le départage est une règle, pas un hasard',['../classcore_1_1ReachableArea.html#autotoc_md39',1,'']]],
  ['déplacement_8',['Le déplacement',['../CombatPreview_8h.html#autotoc_md21',1,'']]],
  ['déplacement_20se_20fractionne_9',['Le déplacement se fractionne',['../classcore_1_1ActionEconomy.html#autotoc_md6',1,'']]],
  ['désigne_20par_20son_20pied_10',['Un relief haut se désigne par son pied',['../CanvasPicking_8h.html#autotoc_md63',1,'']]],
  ['déterministe_20en_20entiers_11',['Déterministe, en entiers',['../EnemyAi_8h.html#autotoc_md30',1,'']]],
  ['déterministe_20et_20c_20est_20le_20point_12',['Déterministe, et c&apos;est le point',['../namespacecore.html#autotoc_md50',1,'']]],
  ['d_20où_20viennent_20les_20formules_13',['D&apos;où viennent les formules',['../IsoProjection_8h.html#autotoc_md33',1,'']]],
  ['d_20un_20lieu_20lot_20124_14',['Le catalogue résolu d&apos;un lieu (&lt;span class=&quot;tt&quot;&gt;LOT-124&lt;/span&gt;)',['../ScenePieceManifest_8h.html#autotoc_md51',1,'']]],
  ['d_20une_20case_15',['Sur la grille : la moitié d&apos;une case',['../AreaOfEffect_8h.html#autotoc_md8',1,'']]],
  ['d11_16',['La hauteur, réservée (D11)',['../CanvasPicking_8h.html#autotoc_md64',1,'']]],
  ['dans_20l_20item_20qt_20quick_17',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md83',1,'']]],
  ['dans_20le_20code_20et_20pas_20dans_20un_20fichier_18',['Pourquoi dans le code, et pas dans un fichier',['../MaquettePalette_8h.html#autotoc_md87',1,'']]],
  ['dans_20un_20fichier_19',['Pourquoi dans le code, et pas dans un fichier',['../MaquettePalette_8h.html#autotoc_md87',1,'']]],
  ['dans_20une_20scène_20fondue_20',['Les couches, dans une scène fondue',['../CanvasScene_8h.html#autotoc_md66',1,'']]],
  ['de_20cases_21',['Deux vues, un repère de cases',['../CanvasPicking_8h.html#autotoc_md62',1,'']]],
  ['de_20ce_20fichier_22',['Hors de ce fichier',['../AreaOfEffect_8h.html#autotoc_md10',1,'']]],
  ['de_20ce_20fichier_20nommément_23',['Hors de ce fichier, nommément',['../Attack_8h.html#autotoc_md15',1,'']]],
  ['de_20chaînes_20et_20non_20une_20structure_20de_20champs_24',['Pourquoi une table de chaînes, et non une structure de champs',['../structhmi_1_1CharacterSheetContext.html#autotoc_md96',1,'']]],
  ['de_20champs_25',['Pourquoi une table de chaînes, et non une structure de champs',['../structhmi_1_1CharacterSheetContext.html#autotoc_md96',1,'']]],
  ['de_20changement_26',['Signal et notification de changement',['../classhmi_1_1ArenaModel.html#autotoc_md100',1,'']]],
  ['de_20commentaire_27',['Convention de commentaire',['../index.html#autotoc_md3',1,'']]],
  ['de_20départage_28',['La règle de départage',['../namespacecore.html#autotoc_md42',1,'']]],
  ['de_20fausses_20données_29',['Pourquoi un tiret cadratin et non de fausses données',['../classhmi_1_1PendingData.html#autotoc_md118',1,'']]],
  ['de_20fichier_30',['Pourquoi une énumération et non un nom de fichier',['../classhmi_1_1ScreenRouter.html#autotoc_md122',1,'']]],
  ['de_20l_20atlas_20procédural_31',['Pourquoi pas les couleurs de l&apos;atlas procédural',['../MaquettePalette_8h.html#autotoc_md88',1,'']]],
  ['de_20l_20auteur_32',['La règle, décidée le 17 septembre 2026 (&lt;em&gt;décision de l&apos;auteur&lt;/em&gt;)',['../PlaceAppearance_8h.html#autotoc_md91',1,'']]],
  ['de_20libération_33',['L&apos;ordre de libération',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md85',1,'']]],
  ['de_20qrhiwidget_34',['Le jumeau Qt Quick de &lt;span class=&quot;tt&quot;&gt;QRhiWidget&lt;/span&gt;',['../classhmi_1_1GameViewportItem.html#autotoc_md112',1,'']]],
  ['de_20texte_35',['Une image engendrée, pas un rendu de texte',['../MaquetteTokens_8h.html#autotoc_md89',1,'']]],
  ['de_20vérité_20pour_20«_20peut_20on_20se_20tenir_20ici_20»_36',['Une seule source de vérité pour « peut-on se tenir ici »',['../classcore_1_1BattleGrid.html#autotoc_md17',1,'']]],
  ['de_20zone_37',['Les propriétés de zone',['../classcore_1_1BattleGrid.html#autotoc_md18',1,'']]],
  ['dehors_38',['Le formatage est ici, la traduction reste dehors',['../structhmi_1_1CharacterSheetContext.html#autotoc_md97',1,'']]],
  ['depuis_20le_20format_20v4_20lot_20editor_2012_39',['Depuis le format v4 (&lt;span class=&quot;tt&quot;&gt;LOT-EDITOR-12&lt;/span&gt;)',['../PlaceAppearance_8h.html#autotoc_md92',1,'']]],
  ['des_20propriétés_20nommées_20plutôt_20que_20la_20table_20brute_40',['Pourquoi des propriétés nommées plutôt que la table brute',['../classhmi_1_1CharacterSheetModel.html#autotoc_md107',1,'']]],
  ['deux_20fils_41',['Les trois temps, et les deux fils',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md84',1,'']]],
  ['deux_20vues_20un_20repère_20de_20cases_42',['Deux vues, un repère de cases',['../CanvasPicking_8h.html#autotoc_md62',1,'']]],
  ['directement_20dans_20l_20item_20qt_20quick_43',['Pourquoi pas directement dans l&apos;item Qt Quick',['../classhmi_1_1ArenaSceneRenderer.html#autotoc_md83',1,'']]],
  ['dit_44',['dit',['../EnemyAi_8h.html#autotoc_md28',1,'Ce que le &lt;em&gt;Guide du Maître&lt;/em&gt; en dit'],['../classhmi_1_1DialogueModel.html#autotoc_md109',1,'Ce qui est un échafaudage, et le dit']]],
  ['dit_20le_20guide_45',['Ce que dit le Guide',['../Flanking_8h.html#autotoc_md31',1,'']]],
  ['dit_20le_20manuel_46',['Ce que dit le Manuel',['../AreaOfEffect_8h.html#autotoc_md7',1,'']]],
  ['dit_20le_20manuel_20et_20ce_20qu_20il_20laisse_20à_20trancher_47',['Ce que dit le Manuel, et ce qu&apos;il laisse à trancher',['../LineOfSight_8h.html#autotoc_md35',1,'']]],
  ['dit_20le_20manuel_20et_20où_20chaque_20règle_20vit_48',['Ce que dit le Manuel, et où chaque règle vit',['../Attack_8h.html#autotoc_md13',1,'']]],
  ['dit_20pas_49',['Ce que ce fichier décide, et que le Guide ne dit pas',['../EnemyAi_8h.html#autotoc_md29',1,'']]],
  ['donnée_20du_20lieu_50',['L&apos;échelle, une donnée du lieu',['../SceneTextureTraits_8h.html#autotoc_md93',1,'']]],
  ['données_51',['Pourquoi un tiret cadratin et non de fausses données',['../classhmi_1_1PendingData.html#autotoc_md118',1,'']]],
  ['du_20code_52',['Référence du code',['../index.html',1,'']]],
  ['du_20jeu_53',['La règle, et pourquoi c&apos;est celle du jeu',['../ExplorationReach_8h.html#autotoc_md58',1,'']]],
  ['du_20lieu_54',['L&apos;échelle, une donnée du lieu',['../SceneTextureTraits_8h.html#autotoc_md93',1,'']]],
  ['du_20maître_20en_20dit_55',['Ce que le &lt;em&gt;Guide du Maître&lt;/em&gt; en dit',['../EnemyAi_8h.html#autotoc_md28',1,'']]],
  ['du_20manuel_56',['Les attaques du Manuel',['../Arena_8h.html#autotoc_md12',1,'']]],
  ['du_20manuel_20et_20pourquoi_20elle_20n_20est_20pas_20un_20parcours_20en_20largeur_57',['La règle du Manuel, et pourquoi elle n&apos;est pas un parcours en largeur',['../classcore_1_1ReachableArea.html#autotoc_md38',1,'']]]
];
